#!/usr/bin/env python3
"""Generate small independent DFT-D4 4.2.0 EEQ energy/gradient/charge fixtures."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BOHR_PER_ANGSTROM = 1.8897261246257702

CASES = [
    {
        "name": "water_r2scan3c",
        "functional": "r2scan-3c",
        "profile": "r2scan3c",
        "charge": 0.0,
        "z": [8, 1, 1],
        "symbols": ["O", "H", "H"],
        "xyz": [(0.0, 0.0, 0.0), (0.756950, 0.0, 0.582089), (-0.756950, 0.0, 0.582089)],
        "parameters": [1.0, 0.0, 2.0, 0.42, 5.65, 2.0, 1.0],
    },
    {
        "name": "asymmetric_pbe",
        "functional": "pbe",
        "profile": "standard",
        "charge": 0.0,
        "z": [6, 8, 7, 1],
        "symbols": ["C", "O", "N", "H"],
        "xyz": [
            (0.0, 0.0, 0.0),
            (1.19, 0.13, -0.04),
            (-0.47, 1.31, 0.22),
            (0.31, -0.63, 0.89),
        ],
        "parameters": [1.0, 0.95948085, 1.0, 0.38574991, 4.80688534, 3.0, 2.0],
    },
    {
        "name": "charged_zinc_ammonia_pbe",
        "functional": "pbe",
        "profile": "standard",
        "charge": 1.0,
        "z": [30, 7, 1, 1, 1],
        "symbols": ["Zn", "N", "H", "H", "H"],
        "xyz": [
            (0.0, 0.0, 0.0),
            (2.05, 0.0, 0.0),
            (2.39, 0.94, 0.0),
            (2.39, -0.47, 0.814),
            (2.39, -0.47, -0.814),
        ],
        "parameters": [1.0, 0.95948085, 1.0, 0.38574991, 4.80688534, 3.0, 2.0],
    },
]


def fmt(value: float) -> str:
    text = format(float(value), ".17g")
    if "." not in text and "e" not in text:
        text += ".0"
    return text


def run_case(executable: Path, prefix: Path, case: dict) -> dict:
    with tempfile.TemporaryDirectory(prefix="vibeqc-d4-eeq-") as td:
        work = Path(td)
        xyz = work / "input.xyz"
        lines = [str(len(case["z"])), case["name"]]
        lines += [
            f"{s} {x:.15f} {y:.15f} {z:.15f}"
            for s, (x, y, z) in zip(case["symbols"], case["xyz"], strict=True)
        ]
        xyz.write_text("\n".join(lines) + "\n")
        out = work / "result.json"
        env = dict(os.environ)
        env["LD_LIBRARY_PATH"] = str(prefix / "lib") + (
            ":" + env["LD_LIBRARY_PATH"] if env.get("LD_LIBRARY_PATH") else ""
        )
        cmd = [
            str(executable),
            str(xyz),
            "--func",
            case["functional"],
            "--charge",
            fmt(case["charge"]),
            "--property",
            "--grad",
            str(work / "gradient.txt"),
            "--json",
            str(out),
            "-s",
        ]
        subprocess.run(
            cmd,
            cwd=work,
            env=env,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        result = json.loads(out.read_text())
        if result["version"] != "4.2.0":
            raise RuntimeError(f"unexpected DFT-D4 version {result['version']}")
        return {
            **case,
            "xyz_bohr": [v * BOHR_PER_ANGSTROM for row in case["xyz"] for v in row],
            "energy": result["energy"],
            "gradient": result["gradient"],
            "charges": result["partial charges"],
        }


def render(records: list[dict]) -> str:
    rows = []
    max_atoms = max(len(r["z"]) for r in records)
    for r in records:
        z = r["z"] + [0] * (max_atoms - len(r["z"]))
        xyz = r["xyz_bohr"] + [0.0] * (3 * (max_atoms - len(r["z"])))
        grad = r["gradient"] + [0.0] * (3 * (max_atoms - len(r["z"])))
        q = r["charges"] + [0.0] * (max_atoms - len(r["z"]))
        p = r["parameters"]
        profile = (
            "D4EEQProfile::r2scan3c"
            if r["profile"] == "r2scan3c"
            else "D4EEQProfile::standard"
        )
        rows.append(
            "  EEQOracleFixture{"
            + f'"{r["name"]}", {len(r["z"])}, {fmt(r["charge"])}, '
            + "{"
            + ", ".join(map(str, z))
            + "}, "
            + "{"
            + ", ".join(fmt(v) for v in xyz)
            + "}, "
            + "D4Parameters{D4ReferenceModel::eeq, "
            + ", ".join(fmt(v) for v in p[:5])
            + ", 30.0, 60.0, 40.0, "
            + ", ".join(fmt(v) for v in p[5:])
            + "}, "
            + profile
            + f", {fmt(r['energy'])}, "
            + "{"
            + ", ".join(fmt(v) for v in grad)
            + "}, "
            + "{"
            + ", ".join(fmt(v) for v in q)
            + "}},"
        )
    return f"""// Generated by tools/oracle/generate_d4_eeq_reference.py; do not edit.
// clang-format off
#pragma once

#include <array>
#include <cstdint>
#include "dft/dispersion/d4_eeq.hpp"

namespace d4_eeq_tests {{
using namespace vibeqc::dft::dispersion;
inline constexpr int kMaxAtoms = {max_atoms};
struct EEQOracleFixture {{
  const char* name;
  int atoms;
  double total_charge;
  std::array<std::int32_t, kMaxAtoms> z;
  std::array<double, 3 * kMaxAtoms> xyz;
  D4Parameters parameters;
  D4EEQProfile profile;
  double energy;
  std::array<double, 3 * kMaxAtoms> gradient;
  std::array<double, kMaxAtoms> charges;
}};
inline constexpr std::array<EEQOracleFixture, {len(rows)}> kEEQOracleFixtures{{{{
{chr(10).join(rows)}
}}}};
}}  // namespace d4_eeq_tests
// clang-format on
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", type=Path, required=True)
    args = parser.parse_args()
    executable = args.prefix / "bin/dftd4"
    if not executable.is_file():
        raise FileNotFoundError(executable)
    records = [run_case(executable, args.prefix, case) for case in CASES]
    header = render(records)
    out = ROOT / "tests/native/d4_eeq_oracle_fixtures.hpp"
    out.write_text(header, encoding="utf-8", newline="\n")
    version_env = dict(os.environ)
    version_env["LD_LIBRARY_PATH"] = str(args.prefix / "lib")
    version = subprocess.run(
        [str(executable), "--version"],
        env=version_env,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    libraries = {}
    for name in ("libdftd4.so", "libmctc-lib.so", "libmulticharge.so"):
        path = args.prefix / "lib" / name
        if not path.exists():
            raise FileNotFoundError(path)
        libraries[name] = hashlib.sha256(path.read_bytes()).hexdigest()
    manifest = {
        "oracle": "independent dftd4 CLI",
        "oracle_version": version,
        "binary_sha256": hashlib.sha256(executable.read_bytes()).hexdigest(),
        "libraries": libraries,
        "generator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "fixture_sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        "cases": [r["name"] for r in records],
        "scope": "EEQ charges plus complete D4 energy/Cartesian gradient; no VibeQC mathematics",
    }
    manifest_out = ROOT / "tests/data/d4/eeq_oracle_manifest.json"
    manifest_out.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
