#!/usr/bin/env python3
"""Build a test-only DFT-D4 adapter and record independent fixed-charge fixtures.

Requires an external prefix containing DFT-D4 4.2.0, its Fortran module files,
mctc-lib, multicharge and a compatible Fortran compiler. Not a runtime dependency.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PARAMETERS = [1.0, 2.7, 5.0, 0.52, 5.0]
CASES = [
    (
        "asymmetric",
        [8, 1, 1, 6],
        [0.0, 0.0, 0.0, 1.43, 0.0, 1.1, -1.43, 0.0, 1.1, 2.7, 1.2, -0.4],
        [-0.6, 0.25, 0.25, 0.1],
        DEFAULT_PARAMETERS,
    ),
    (
        "water_dimer",
        [8, 1, 1, 8, 1, 1],
        [
            0.0,
            0.0,
            0.0,
            1.43,
            0.0,
            1.1,
            -1.43,
            0.0,
            1.1,
            7.0,
            0.5,
            0.0,
            8.43,
            0.5,
            1.1,
            5.57,
            0.5,
            1.1,
        ],
        [-0.8, 0.4, 0.4, -0.7, 0.35, 0.35],
        DEFAULT_PARAMETERS,
    ),
    (
        "charged_zinc_ammonia",
        [30, 7, 1, 1, 1],
        [
            0.0,
            0.0,
            0.0,
            4.5,
            0.0,
            0.0,
            5.3,
            1.7,
            0.0,
            5.3,
            -0.85,
            1.47,
            5.3,
            -0.85,
            -1.47,
        ],
        [1.2, -0.7, 0.2, 0.2, 0.1],
        DEFAULT_PARAMETERS,
    ),
    (
        "signed_s8_no_atm",
        [8, 1, 1, 6],
        [0.0, 0.0, 0.0, 1.43, 0.0, 1.1, -1.43, 0.0, 1.1, 2.7, 1.2, -0.4],
        [-0.6, 0.25, 0.25, 0.1],
        [1.0, -2.7, 0.0, 0.52, 5.0],
    ),
    (
        "bromide_contact",
        [35, 1, 6, 1],
        [0.0, 0.0, 0.0, 4.0, 0.0, 0.3, 6.0, 0.1, 0.2, 7.1, 1.7, -0.2],
        [-0.6, 0.2, 0.3, 0.1],
        DEFAULT_PARAMETERS,
    ),
]


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def array(values: list, size: int) -> str:
    return "{{" + ", ".join(repr(v) for v in values + [0] * (size - len(values))) + "}}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", type=Path, required=True)
    args = parser.parse_args()
    prefix = args.prefix.resolve()
    compilers = sorted((prefix / "bin").glob("*gfortran"))
    modules = sorted((prefix / "include/dftd4").glob("*/dftd4_model.mod"))
    if not compilers or len(modules) != 1:
        raise RuntimeError(
            "A compatible Fortran compiler and unambiguous dftd4 module directory are required"
        )
    version = subprocess.check_output(
        [str(prefix / "bin/dftd4"), "--version"], text=True
    ).strip()
    if version != "dftd4 version 4.2.0":
        raise RuntimeError(
            f"Unexpected oracle version: {version}; audit before changing the pin"
        )
    adapter = ROOT / "tools/oracle/d4_fixed_charge.f90"
    records = []
    with tempfile.TemporaryDirectory(prefix="vibeqc-d4-oracle-") as tmp:
        exe = Path(tmp) / "oracle"
        subprocess.run(
            [
                str(compilers[0]),
                "-O2",
                f"-I{modules[0].parent}",
                f"-I{prefix / 'include/mctc-lib/modules'}",
                str(adapter),
                f"-L{prefix / 'lib'}",
                f"-Wl,-rpath,{prefix / 'lib'}",
                "-ldftd4",
                "-lmctc-lib",
                "-lmulticharge",
                "-lblas",
                "-fopenmp",
                "-o",
                str(exe),
            ],
            check=True,
        )
        for name, numbers, xyz, charges, params in CASES:
            n = len(numbers)
            lines = [str(n), " ".join(map(str, params))]
            lines += [
                " ".join(map(str, [numbers[i], *xyz[3 * i : 3 * i + 3], charges[i]]))
                for i in range(n)
            ]
            result = subprocess.check_output(
                [str(exe)],
                input="\n".join(lines) + "\n",
                text=True,
                env={**os.environ, "OMP_NUM_THREADS": "1", "OPENBLAS_NUM_THREADS": "1"},
            )
            values = list(map(float, result.split()))
            if len(values) != 2 + 4 * n or not all(math.isfinite(x) for x in values):
                raise RuntimeError(f"Invalid independent oracle output for {name}")
            records.append((name, n, numbers, xyz, charges, params, values))
    header = """// clang-format off
// Generated by tools/oracle/generate_d4_reference.py; do not edit.
// Independent DFT-D4 4.2.0, GFN2 reference model and supplied charges.
#pragma once
#include <array>
#include <cstdint>
#include "dft/dispersion/d4_reference.hpp"
namespace d4_tests {
struct OracleFixture {
  const char* name;
  int n;
  vibeqc::dft::dispersion::D4Parameters parameters;
  std::array<std::int32_t, 8> z;
  std::array<double, 24> xyz;
  std::array<double, 8> q;
  std::array<double, 2> energy;
  std::array<double, 24> gradient;
  std::array<double, 8> dq;
};
inline const OracleFixture kOracleFixtures[] = {
"""
    for name, n, numbers, xyz, charges, params, values in records:
        par = (
            "{vibeqc::dft::dispersion::D4ReferenceModel::gfn2, "
            + ", ".join(map(repr, params))
            + ", 30.0, 50.0, 25.0}"
        )
        header += (
            "  {"
            + f'"{name}", {n}, {par},\n    '
            + ",\n    ".join(
                [
                    array(numbers, 8),
                    array(xyz, 24),
                    array(charges, 8),
                    array(values[:2], 2),
                    array(values[2 : 2 + 3 * n], 24),
                    array(values[2 + 3 * n :], 8),
                ]
            )
            + "},\n"
        )
    header += "};\n}  // namespace d4_tests\n// clang-format on\n"
    output = ROOT / "tests/native/d4_oracle_fixtures.hpp"
    output.write_text(header)
    package_records = []
    for path in sorted((prefix / "conda-meta").glob("*.json")):
        record = json.loads(path.read_text())
        if record["name"] in {
            "dftd4",
            "mctc-lib",
            "multicharge",
            "gfortran_impl_linux-64",
        }:
            package_records.append({k: record[k] for k in ("name", "version", "build")})
    manifest = {
        "reference_model": "gfn2",
        "charges": "independent supplied inputs; no EEQ response",
        "oracle_version": version,
        "adapter_sha256": sha(adapter),
        "generator_sha256": sha(Path(__file__)),
        "fixture_sha256": sha(output),
        "libraries": {
            name: sha(prefix / "lib" / name)
            for name in ("libdftd4.so", "libmctc-lib.so", "libmulticharge.so")
        },
        "packages": package_records,
        "cases": [r[0] for r in records],
        "command": "python tools/oracle/generate_d4_reference.py --prefix /path/to/reference-prefix",
    }
    folder = ROOT / "tests/data/d4"
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "oracle_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    print(f"Wrote {len(records)} independent DFT-D4 fixtures")


if __name__ == "__main__":
    main()
