// Generated by tools/generate_mp2_native.py; equations are TensorIR.
#pragma once
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <stdexcept>
#include <vector>
namespace vibeqc::mp2::generated {
using CpuRun = void (*)(const double*, const double*, double, double, const double*, const double*,
                        double*);
struct CpuPlan {
  CpuRun run;
  std::size_t numeric_bytes;
  const char* equation_hash;
};
// TensorIR equation e1b9599ab4f5a727d10d66d3a1b2eddc572b14b5b55173cd70f3b50975a1a673
inline void tile_1(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(1);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 1; ++z) v6[z] = v2[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(1);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 1; ++z)
    v7[z] = (0x1.0000000000000p+0 * v5[z]) + (-0x1.0000000000000p+0 * v1[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage8(1);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 1; ++z) v8[z] = v3[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(1);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 1; ++z) v9[z] = v0[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage10(1);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 1; ++z) v10[z] = v4[((z / 1) % 1) * 1];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(1);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 1; ++z)
    v11[z] = (0x1.0000000000000p+0 * v8[z]) + (0x1.0000000000000p+0 * v10[z]) +
             (-0x1.0000000000000p+0 * v9[z]) + (-0x1.0000000000000p+0 * v6[z]);
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(1);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 1; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 1; ++z) v12[z] = v5[z] / v11[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(1);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 1; ++z) v13[z] = v12[z] * v7[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(1);
  double* v14 = storage14.data();
  for (size_t z = 0; z < 1; ++z) v14[z] = v12[z] * v5[z];
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t q = 0; q < 1; ++q) {
    v15[0] += v14[q];
    if (!std::isfinite(v15[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage16(1);
  double* v16 = storage16.data();
  for (size_t q = 0; q < 1; ++q) {
    v16[0] += v13[q];
    if (!std::isfinite(v16[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v16[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::copy_n(v15, 1, outputs[0]);
  std::copy_n(v16, 1, outputs[1]);
}

inline void run_1(const double* g, const double* x, double ei, double ej, const double* ea,
                  const double* eb, double* out) {
  const double* inputs[] = {ea, x, eb, &ei, &ej, g};
  double* outputs[] = {out, out + 1};
  tile_1(inputs, outputs);
}
// TensorIR equation 2e48d48c98be350c27b6928523d3c296effdbb922b4342873795f85033b3323b
inline void tile_2(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 2; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 2; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(4);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 4; ++z) v6[z] = v4[((z / 2) % 2) * 1];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(4);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 4; ++z)
    v7[z] = (0x1.0000000000000p+0 * v1[z]) + (-0x1.0000000000000p+0 * v0[z]);
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage8(4);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 4; ++z) v8[z] = v5[((z / 1) % 2) * 1];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(4);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 4; ++z) v9[z] = v2[((z / 4) % 1) * 1];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage10(4);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 4; ++z) v10[z] = v3[((z / 4) % 1) * 1];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(4);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 4; ++z)
    v11[z] = (0x1.0000000000000p+0 * v9[z]) + (0x1.0000000000000p+0 * v10[z]) +
             (-0x1.0000000000000p+0 * v6[z]) + (-0x1.0000000000000p+0 * v8[z]);
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(4);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 4; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 4; ++z) v12[z] = v1[z] / v11[z];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(4);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 4; ++z) v13[z] = v12[z] * v1[z];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(4);
  double* v14 = storage14.data();
  for (size_t z = 0; z < 4; ++z) v14[z] = v12[z] * v7[z];
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t q = 0; q < 4; ++q) {
    v15[0] += v13[q];
    if (!std::isfinite(v15[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage16(1);
  double* v16 = storage16.data();
  for (size_t q = 0; q < 4; ++q) {
    v16[0] += v14[q];
    if (!std::isfinite(v16[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v16[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::copy_n(v15, 1, outputs[0]);
  std::copy_n(v16, 1, outputs[1]);
}

inline void run_2(const double* g, const double* x, double ei, double ej, const double* ea,
                  const double* eb, double* out) {
  const double* inputs[] = {x, g, &ei, &ej, ea, eb};
  double* outputs[] = {out, out + 1};
  tile_2(inputs, outputs);
}
// TensorIR equation 9878b88969e70606ed7ddae54a0c1f1ecf57cd2b4fabe8d72f8cb37fe42fc16c
inline void tile_4(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 4; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(16);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 16; ++z) v6[z] = v5[((z / 1) % 4) * 1];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(16);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 16; ++z) v7[z] = v0[((z / 16) % 1) * 1];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage8(16);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 16; ++z)
    v8[z] = (0x1.0000000000000p+0 * v2[z]) + (-0x1.0000000000000p+0 * v3[z]);
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage9(16);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 16; ++z) v9[z] = v1[((z / 16) % 1) * 1];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage10(16);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 16; ++z) v10[z] = v4[((z / 4) % 4) * 1];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(16);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 16; ++z)
    v11[z] = (0x1.0000000000000p+0 * v7[z]) + (0x1.0000000000000p+0 * v9[z]) +
             (-0x1.0000000000000p+0 * v10[z]) + (-0x1.0000000000000p+0 * v6[z]);
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(16);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 16; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 16; ++z) v12[z] = v2[z] / v11[z];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(16);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 16; ++z) v13[z] = v12[z] * v8[z];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(16);
  double* v14 = storage14.data();
  for (size_t z = 0; z < 16; ++z) v14[z] = v12[z] * v2[z];
  for (size_t z = 0; z < 16; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t q = 0; q < 16; ++q) {
    v15[0] += v13[q];
    if (!std::isfinite(v15[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage16(1);
  double* v16 = storage16.data();
  for (size_t q = 0; q < 16; ++q) {
    v16[0] += v14[q];
    if (!std::isfinite(v16[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v16[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::copy_n(v16, 1, outputs[0]);
  std::copy_n(v15, 1, outputs[1]);
}

inline void run_4(const double* g, const double* x, double ei, double ej, const double* ea,
                  const double* eb, double* out) {
  const double* inputs[] = {&ei, &ej, g, x, ea, eb};
  double* outputs[] = {out, out + 1};
  tile_4(inputs, outputs);
}
// TensorIR equation 88ae7fcb2aee0410f171b7617387b57006536098c84f6f3c0d91641046da0073
inline void tile_8(const double* const* inputs, double* const* outputs) {
  const double* v0 = inputs[0];
  if (!v0) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v0[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v1 = inputs[1];
  if (!v1) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v1[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v2 = inputs[2];
  if (!v2) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v2[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v3 = inputs[3];
  if (!v3) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 8; ++z)
    if (!std::isfinite(v3[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v4 = inputs[4];
  if (!v4) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 8; ++z)
    if (!std::isfinite(v4[z])) throw std::runtime_error("nonfinite TensorIR input");
  const double* v5 = inputs[5];
  if (!v5) throw std::invalid_argument("null tensor input");
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v5[z])) throw std::runtime_error("nonfinite TensorIR input");
  std::vector<double> storage6(64);
  double* v6 = storage6.data();
  for (size_t z = 0; z < 64; ++z) v6[z] = v0[((z / 64) % 1) * 1];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v6[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage7(64);
  double* v7 = storage7.data();
  for (size_t z = 0; z < 64; ++z) v7[z] = v4[((z / 8) % 8) * 1];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v7[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage8(64);
  double* v8 = storage8.data();
  for (size_t z = 0; z < 64; ++z) v8[z] = v3[((z / 1) % 8) * 1];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v8[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage9(64);
  double* v9 = storage9.data();
  for (size_t z = 0; z < 64; ++z)
    v9[z] = (0x1.0000000000000p+0 * v1[z]) + (-0x1.0000000000000p+0 * v5[z]);
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v9[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage10(64);
  double* v10 = storage10.data();
  for (size_t z = 0; z < 64; ++z) v10[z] = v2[((z / 64) % 1) * 1];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v10[z])) throw std::runtime_error("nonfinite TensorIR broadcast");
  std::vector<double> storage11(64);
  double* v11 = storage11.data();
  for (size_t z = 0; z < 64; ++z)
    v11[z] = (0x1.0000000000000p+0 * v6[z]) + (0x1.0000000000000p+0 * v10[z]) +
             (-0x1.0000000000000p+0 * v7[z]) + (-0x1.0000000000000p+0 * v8[z]);
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v11[z])) throw std::runtime_error("nonfinite TensorIR add");
  std::vector<double> storage12(64);
  double* v12 = storage12.data();
  for (size_t z = 0; z < 64; ++z)
    if (v11[z] == 0) throw std::runtime_error("zero tensor denominator");
  for (size_t z = 0; z < 64; ++z) v12[z] = v1[z] / v11[z];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v12[z])) throw std::runtime_error("nonfinite TensorIR divide");
  std::vector<double> storage13(64);
  double* v13 = storage13.data();
  for (size_t z = 0; z < 64; ++z) v13[z] = v12[z] * v1[z];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v13[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage14(64);
  double* v14 = storage14.data();
  for (size_t z = 0; z < 64; ++z) v14[z] = v12[z] * v9[z];
  for (size_t z = 0; z < 64; ++z)
    if (!std::isfinite(v14[z])) throw std::runtime_error("nonfinite TensorIR multiply");
  std::vector<double> storage15(1);
  double* v15 = storage15.data();
  for (size_t q = 0; q < 64; ++q) {
    v15[0] += v14[q];
    if (!std::isfinite(v15[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v15[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::vector<double> storage16(1);
  double* v16 = storage16.data();
  for (size_t q = 0; q < 64; ++q) {
    v16[0] += v13[q];
    if (!std::isfinite(v16[0])) throw std::runtime_error("nonfinite tensor reduction");
  }
  for (size_t z = 0; z < 1; ++z)
    if (!std::isfinite(v16[z])) throw std::runtime_error("nonfinite TensorIR reduce");
  std::copy_n(v16, 1, outputs[0]);
  std::copy_n(v15, 1, outputs[1]);
}

inline void run_8(const double* g, const double* x, double ei, double ej, const double* ea,
                  const double* eb, double* out) {
  const double* inputs[] = {&ei, g, &ej, eb, ea, x};
  double* outputs[] = {out, out + 1};
  tile_8(inputs, outputs);
}
inline CpuPlan cpu_plan(unsigned tile) {
  switch (tile) {
    case 1:
      return {run_1, 216ULL, "e1b9599ab4f5a727d10d66d3a1b2eddc572b14b5b55173cd70f3b50975a1a673"};
    case 2:
      return {run_2, 544ULL, "2e48d48c98be350c27b6928523d3c296effdbb922b4342873795f85033b3323b"};
    case 4:
      return {run_4, 1824ULL, "9878b88969e70606ed7ddae54a0c1f1ecf57cd2b4fabe8d72f8cb37fe42fc16c"};
    case 8:
      return {run_8, 6880ULL, "88ae7fcb2aee0410f171b7617387b57006536098c84f6f3c0d91641046da0073"};
    default:
      throw std::invalid_argument("unsupported MP2 tile");
  }
}
}  // namespace vibeqc::mp2::generated
