"""Regression gates for the native GFN2 S/D/Q primitive lowering."""

from vibeqc_compiler.integral.gfn2_sdq_cpu import (
    emit_gfn2_sdq_cpu,
    gfn2_sdq_cpu_inventory,
)


def test_gfn2_sdq_cpu_inventory_is_bounded_to_public_spd() -> None:
    inventory = gfn2_sdq_cpu_inventory()
    assert inventory["schema"] == "vibeqc.gfn2_sdq_cpu"
    assert inventory["version"] == 1
    assert inventory["precision"] == "fp64"
    assert inventory["public_maximum_angular"] == 2
    assert inventory["operator_origin"] == "ket"
    assert inventory["gradient_center"] == "ket"
    assert inventory["component_pairs"] == 100


def test_gfn2_sdq_cpu_emitter_is_deterministic_generated_math() -> None:
    source = emit_gfn2_sdq_cpu()
    assert source == emit_gfn2_sdq_cpu()
    assert "Generated by tools/generate_gfn2_sdq_native.py" in source
    assert "Gfn2SdqPrimitive" in source
    assert "evaluate_gfn2_sdq_primitive" in source
    assert "make_axis_overlap" not in source
    assert "__device__" not in source
