"""Regression gates for the native GFN2 S/D/Q primitive lowering."""

import shutil
import subprocess
from pathlib import Path

import pytest
from vibeqc_compiler.integral.gfn2_sdq_cpu import (
    emit_gfn2_sdq_cpu,
    emit_gfn2_sdq_cuda,
    gfn2_sdq_cpu_inventory,
)


def test_gfn2_sdq_cpu_inventory_is_bounded_to_public_spd() -> None:
    inventory = gfn2_sdq_cpu_inventory()
    assert inventory["schema"] == "vibeqc.gfn2_sdq_cpu"
    assert inventory["version"] == 1
    assert inventory["precision"] == "fp64"
    assert inventory["public_maximum_angular"] == 2
    assert inventory["operator_origin"] == "ket"
    assert inventory["gradient_center"] == "ket"
    assert inventory["component_pairs"] == 100


def test_gfn2_sdq_cpu_emitter_is_deterministic_generated_math() -> None:
    source = emit_gfn2_sdq_cpu()
    assert source == emit_gfn2_sdq_cpu()
    assert "Generated by tools/generate_gfn2_sdq_native.py" in source
    assert "Gfn2SdqPrimitive" in source
    assert "evaluate_gfn2_sdq_primitive" in source
    assert "make_axis_overlap" not in source
    assert "__device__" not in source


def test_gfn2_sdq_cuda_emitter_is_device_generated_math() -> None:
    source = emit_gfn2_sdq_cuda()
    assert source == emit_gfn2_sdq_cuda()
    assert "Generated by tools/generate_gfn2_sdq_native.py for CUDA" in source
    assert "__device__ inline bool evaluate_gfn2_sdq_primitive" in source
    assert "__device__ inline bool evaluate_gfn2_sdq_values_primitive" in source
    assert "std::isfinite" not in source
    assert "make_axis_overlap" not in source


def test_cuda_integral_consumer_has_no_handwritten_primitive_recurrence() -> None:
    root = Path(__file__).resolve().parents[2]
    source = (
        root / "src/xtb/gfn2_runtime/src/backends/cuda/gfn2_integrals.cu"
    ).read_text()
    assert '#include "generated_gfn2_sdq_cuda.cuh"' in source
    assert "evaluate_gfn2_sdq_values_primitive" in source
    assert "evaluate_gfn2_sdq_primitive" in source
    assert "make_axis_overlap" not in source
    assert "multipole_power" not in source


def test_generated_dispatch_rejects_aliasing_and_invalid_inputs(tmp_path: Path) -> None:
    compiler = shutil.which("c++")
    if compiler is None:
        pytest.skip("host C++ compiler required")
    (tmp_path / "sdq.hpp").write_text(emit_gfn2_sdq_cpu())
    source = tmp_path / "check.cpp"
    source.write_text(r"""
#include <limits>
#include "sdq.hpp"
int main() {
  using namespace vibeqc::xtb::generated;
  using Fn=bool(*)(unsigned,unsigned,unsigned,unsigned,double,double,const double*,Gfn2SdqPrimitive&);
  const Fn functions[]{evaluate_gfn2_overlap_primitive,evaluate_gfn2_overlap_gradient_primitive,evaluate_gfn2_sdq_values_primitive,evaluate_gfn2_sdq_primitive};
  double r[]{.1,.2,.3};Gfn2SdqPrimitive out{};out.values[0]=123.;
  for(const auto fn:functions) {
    if(fn(0,3,0,0,1.,1.,r,out))return 1;
    if(fn(1,1,0,3,1.,1.,r,out))return 2;
    if(fn(0,0,0,0,std::numeric_limits<double>::quiet_NaN(),1.,r,out))return 3;
    if(fn(0,0,0,0,1.,1.,nullptr,out))return 4;
    if(fn(0,0,0,0,-1.,1.,r,out))return 5;
    if(out.values[0]!=123.)return 6;
  }
}
""")
    binary = tmp_path / "check"
    subprocess.run(
        [compiler, "-std=c++20", "-O0", str(source), "-o", str(binary)],
        check=True,
        capture_output=True,
        timeout=60,
    )
    result = subprocess.run(
        [str(binary)], check=False, capture_output=True, text=True, timeout=10
    )
    assert result.returncode == 0, (result.returncode, result.stdout, result.stderr)
