# Generated by tools/generate_libxc_methods.py; do not edit.
import json
from types import MappingProxyType

METHOD_METADATA_SEMANTICS = "libxc-hybrid-method-metadata/v1"

_RAW_LIBXC_METHODS: dict[str, dict[str, object]] = json.loads(
    r"""{
  "B3LYP": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN_RPA",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 402,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3LYP-MCM1": {
    "components": [
      [
        "LDA_X",
        "33/250"
      ],
      [
        "GGA_X_B88",
        "6709/10000"
      ],
      [
        "LDA_C_VWN_RPA",
        "-1779/10000"
      ],
      [
        "GGA_C_LYP",
        "11383/10000"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "993/5000",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 461,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYP_MCM1",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3LYP-MCM2": {
    "components": [
      [
        "LDA_X",
        "79/1000"
      ],
      [
        "GGA_X_B88",
        "729/1000"
      ],
      [
        "LDA_C_VWN_RPA",
        "21/1250"
      ],
      [
        "GGA_C_LYP",
        "9421/10000"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "557/2500",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 462,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYP_MCM2",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3LYP3": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN_3",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 394,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYP3",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3LYP5": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 475,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYP5",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3LYPS": {
    "components": [
      [
        "LDA_X",
        "13/100"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN_RPA",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "3/20",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 459,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3LYPS",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3P86": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN_RPA",
        "19/100"
      ],
      [
        "GGA_C_P86",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 403,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3P86",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3P86-NWCHEM": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_VWN_RPA",
        "1"
      ],
      [
        "GGA_C_P86",
        "81/100"
      ],
      [
        "LDA_C_PZ",
        "-81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 315,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3P86_NWCHEM",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B3PW91": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_PW",
        "19/100"
      ],
      [
        "GGA_C_PW91",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 401,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B3PW91",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "B5050LYP": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "21/50"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/2",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 572,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_B5050LYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "CAM-B3LYP": {
    "components": [
      [
        "GGA_X_B88",
        "7/20"
      ],
      [
        "GGA_X_ITYH",
        "23/50"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 433,
    "long_range_exchange": "13/20",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "33/100",
    "registration": "HYB_GGA_XC_CAM_B3LYP",
    "short_range_exchange": "19/100",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "CAM-PBEH": {
    "components": [
      [
        "GGA_X_PBE",
        "4/5"
      ],
      [
        "GGA_X_HJS_PBE",
        "-4/5"
      ],
      [
        "GGA_C_PBE",
        "1"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 681,
    "long_range_exchange": "1/5",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "7/10",
    "registration": "HYB_GGA_XC_CAM_PBEH",
    "short_range_exchange": "1",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "CAM-QTP-00": {
    "components": [
      [
        "GGA_X_B88",
        "9/100"
      ],
      [
        "GGA_X_ITYH",
        "37/100"
      ],
      [
        "LDA_C_VWN",
        "1/5"
      ],
      [
        "GGA_C_LYP",
        "4/5"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 490,
    "long_range_exchange": "91/100",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "29/100",
    "registration": "HYB_GGA_XC_CAM_QTP_00",
    "short_range_exchange": "27/50",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "CAM-QTP-01": {
    "components": [
      [
        "GGA_X_ITYH",
        "77/100"
      ],
      [
        "LDA_C_VWN",
        "1/5"
      ],
      [
        "GGA_C_LYP",
        "4/5"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 482,
    "long_range_exchange": "1",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "31/100",
    "registration": "HYB_GGA_XC_CAM_QTP_01",
    "short_range_exchange": "23/100",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "CAM-QTP-02": {
    "components": [
      [
        "GGA_X_ITYH",
        "18/25"
      ],
      [
        "GGA_C_LYP",
        "1"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 491,
    "long_range_exchange": "1",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "67/200",
    "registration": "HYB_GGA_XC_CAM_QTP_02",
    "short_range_exchange": "7/25",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "CAMH-B3LYP": {
    "components": [
      [
        "GGA_X_B88",
        "1/2"
      ],
      [
        "GGA_X_ITYH",
        "31/100"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 614,
    "long_range_exchange": "1/2",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "33/100",
    "registration": "HYB_GGA_XC_CAMH_B3LYP",
    "short_range_exchange": "19/100",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "KMLYP": {
    "components": [
      [
        "LDA_X",
        "443/1000"
      ],
      [
        "LDA_C_VWN_RPA",
        "69/125"
      ],
      [
        "GGA_C_LYP",
        "56/125"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "557/1000",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 485,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_KMLYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "LC-QTP": {
    "components": [
      [
        "GGA_X_ITYH",
        "1"
      ],
      [
        "GGA_C_LYP",
        "1"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 492,
    "long_range_exchange": "1",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "19/40",
    "registration": "HYB_GGA_XC_LC_QTP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "MB3LYP-RC04": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_B88",
        "18/25"
      ],
      [
        "LDA_C_RC04",
        "5383/10000"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 437,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_MB3LYP_RC04",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "MCAM-B3LYP": {
    "components": [
      [
        "GGA_X_B88",
        "31/50"
      ],
      [
        "GGA_X_ITYH",
        "19/100"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 640,
    "long_range_exchange": "19/50",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "33/100",
    "registration": "HYB_GGA_XC_MCAM_B3LYP",
    "short_range_exchange": "19/100",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "MPW3LYP": {
    "components": [
      [
        "LDA_X",
        "73/1000"
      ],
      [
        "GGA_X_MPW91",
        "709/1000"
      ],
      [
        "LDA_C_VWN_RPA",
        "129/1000"
      ],
      [
        "GGA_C_LYP",
        "871/1000"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "109/500",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 419,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_MPW3LYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "MPW3PW": {
    "components": [
      [
        "LDA_X",
        "2/25"
      ],
      [
        "GGA_X_MPW91",
        "18/25"
      ],
      [
        "LDA_C_VWN_RPA",
        "19/100"
      ],
      [
        "GGA_C_PW91",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 415,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_MPW3PW",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "OPB3LYP": {
    "components": [
      [
        "LDA_X",
        "13/100"
      ],
      [
        "GGA_X_B88",
        "67/100"
      ],
      [
        "LDA_C_VWN_RPA",
        "4/25"
      ],
      [
        "GGA_C_LYP",
        "21/25"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 386,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_OPB3LYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "QTP17": {
    "components": [
      [
        "LDA_X",
        "19/50"
      ],
      [
        "LDA_C_VWN_RPA",
        "1/5"
      ],
      [
        "GGA_C_LYP",
        "4/5"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "31/50",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 460,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_QTP17",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "RCAM-B3LYP": {
    "components": [
      [
        "LDA_X",
        "-1359/10000"
      ],
      [
        "GGA_X_B88",
        "259/100000"
      ],
      [
        "GGA_X_ITYH",
        "94979/100000"
      ],
      [
        "GGA_C_LYP",
        "1"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 610,
    "long_range_exchange": "113331/100000",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "33/100",
    "registration": "HYB_GGA_XC_RCAM_B3LYP",
    "short_range_exchange": "1147/6250",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "REVB3LYP": {
    "components": [
      [
        "LDA_X",
        "13/100"
      ],
      [
        "GGA_X_B88",
        "67/100"
      ],
      [
        "LDA_C_VWN_RPA",
        "4/25"
      ],
      [
        "GGA_C_LYP",
        "21/25"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "1/5",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 454,
    "long_range_exchange": "0",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "0",
    "registration": "HYB_GGA_XC_REVB3LYP",
    "short_range_exchange": "0",
    "source": "hyb_gga_xc_b3lyp.c",
    "source_sha256": "0f481a2b55787ce7d6aac346c1c29987dd4f83c70c64ff1b7e90f6ee09ef1e3f"
  },
  "TUNED-CAM-B3LYP": {
    "components": [
      [
        "GGA_X_ITYH",
        "9201/10000"
      ],
      [
        "LDA_C_VWN",
        "19/100"
      ],
      [
        "GGA_C_LYP",
        "81/100"
      ]
    ],
    "direct_semilocal_stem": null,
    "exact_exchange": "0",
    "family": "hyb_gga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_I_HAVE_ALL",
    "libxc_id": 434,
    "long_range_exchange": "1",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": null,
    "nlc_c": null,
    "nonlocal_variant": null,
    "range_omega": "3/20",
    "registration": "HYB_GGA_XC_TUNED_CAM_B3LYP",
    "short_range_exchange": "799/10000",
    "source": "hyb_gga_xc_cam_b3lyp.c",
    "source_sha256": "8f542a15f19f084246b038905d04f67afc01bd3720de8e7110e8ae0a86d19384"
  },
  "WB97M-V": {
    "components": [],
    "direct_semilocal_stem": "WB97M_V",
    "exact_exchange": "0",
    "family": "hyb_mgga",
    "flags": "XC_FLAGS_3D | XC_FLAGS_HYB_CAM | XC_FLAGS_NEEDS_TAU | XC_FLAGS_VV10 | MAPLE2C_FLAGS",
    "libxc_id": 531,
    "long_range_exchange": "1",
    "metadata_semantics": "libxc-hybrid-method-metadata/v1",
    "nlc_b": "6",
    "nlc_c": "1/100",
    "nonlocal_variant": "vv10",
    "range_omega": "3/10",
    "registration": "HYB_MGGA_XC_WB97M_V",
    "short_range_exchange": "3/20",
    "source": "hyb_mgga_xc_wb97mv.c",
    "source_sha256": "896263dad36b75bbb9d42b5e4718d62e8d57e261fd326ebcfc0350c80d39c3d2"
  }
}"""
)
LIBXC_METHODS = MappingProxyType(
    {
        name: MappingProxyType(
            {
                **record,
                "components": tuple(tuple(item) for item in record["components"]),
            }
        )
        for name, record in _RAW_LIBXC_METHODS.items()
    }
)

_RAW_BLOCKED_LIBXC_METHODS: dict[str, str] = json.loads(
    r"""{
  "HYB_GGA_XC_APF": "missing or ambiguous parameter array: funcs_coef",
  "HYB_GGA_XC_WC04": "missing or ambiguous parameter array: funcs_coef",
  "HYB_GGA_XC_WP04": "missing or ambiguous parameter array: funcs_coef"
}"""
)
BLOCKED_LIBXC_METHODS = MappingProxyType(_RAW_BLOCKED_LIBXC_METHODS)
