"""CUDA lowering for symmetric matrix-function custom rules.

The scientific rule identity lives in :mod:`matrix_function`.  This module
emits runtime-sized first-order inverse-square-root and pseudoinverse adapters.
Allocation, eigensolver ownership, streams, and branch validation remain native
runtime responsibilities.
"""

from __future__ import annotations

from .matrix_function_contract import RULE_VERSIONS


def emit_symmetric_matrix_function_vjp_cuda() -> str:
    """Emit one dynamic-size CUDA header for both supported first-order rules."""
    inverse_rule = RULE_VERSIONS["inverse_sqrt"]
    pseudo_rule = RULE_VERSIONS["pseudoinverse"]
    return f"""// Generated by vibeqc_compiler.method.matrix_function_cuda.
// custom-rule: {inverse_rule}
// custom-rule: {pseudo_rule}
#ifndef VIBEQC_GENERATED_SYMMETRIC_MATRIX_FUNCTION_CUH
#define VIBEQC_GENERATED_SYMMETRIC_MATRIX_FUNCTION_CUH

#include <cuda_runtime.h>

#include <cmath>
#include <cstddef>

namespace vibeqc::tensor {{
namespace detail {{
// Evaluate a seeded product without materializing an unrepresentable coefficient.
static __device__ double scaled_response(double seed, double a, double b, double c) {{
  if (seed == 0.0) return seed;
  int es=0, ea=0, eb=0, ec=0;
  const double ms=frexp(seed,&es), ma=frexp(a,&ea);
  const double mb=frexp(b,&eb), mc=frexp(c,&ec);
  return scalbn(((ms/ma)/mb)/mc, es-ea-eb-ec);
}}
static __device__ double matrix_function_value(
    double eigenvalue, bool retained, unsigned function) {{
  if (!retained) return 0.0;
  return function == 0 ? 1.0 / sqrt(eigenvalue) : 1.0 / eigenvalue;
}}

static __global__ void symmetric_matrix_function_vjp_stage(
    std::size_t n, unsigned stage, unsigned function,
    const double* eigenvectors, const double* eigenvalues,
    double relative_threshold, const double* input, double* output) {{
  const auto ij = std::size_t{{blockIdx.x}} * blockDim.x + threadIdx.x;
  if (ij >= n * n) return;
  const auto i = ij / n, j = ij % n;
  double value = 0.0;
  for (std::size_t k = 0; k < n; ++k) {{
    if (stage == 0)
      value += (.5 * input[i * n + k] + .5 * input[k * n + i]) *
               eigenvectors[k + j * n];
    if (stage == 1) value += eigenvectors[k + i * n] * input[k * n + j];
    if (stage == 2) value += eigenvectors[i + k * n] * input[k * n + j];
    if (stage == 3) value += input[i * n + k] * eigenvectors[j + k * n];
  }}
  if (stage == 1) {{
    const double li = eigenvalues[i], lj = eigenvalues[j];
    const double cutoff = relative_threshold * eigenvalues[n - 1];
    const bool ki = li > cutoff, kj = lj > cutoff;
    double divided = 0.0;
    if (ki && kj) {{
      if (function == 0) {{
        const double si = sqrt(li), sj = sqrt(lj);
        divided = -1.0 / si / sj / (si + sj);
      }} else {{
        divided = -1.0 / li / lj;
      }}
    }} else if (ki != kj) {{
      const double fi = matrix_function_value(li, ki, function);
      const double fj = matrix_function_value(lj, kj, function);
      divided = (fi - fj) / (li - lj);
    }}
    if (value == 0.0 || (!ki && !kj)) {{
      value = 0.0;
    }} else if (isfinite(divided) && fabs(divided) >= 0x1p-1022) {{
      value *= divided;
    }} else if (ki && kj) {{
      if (function == 0) {{
        const double si=sqrt(li), sj=sqrt(lj);
        value=scaled_response(-value,si,sj,si+sj);
      }} else value=scaled_response(-value,li,lj,1.0);
    }} else {{
      const double kept=ki?li:lj;
      const double denominator=function==0?sqrt(kept):kept;
      value=scaled_response(ki?value:-value,denominator,li-lj,1.0);
    }}
  }}
  output[ij] = value;
}}

static __global__ void symmetrize_response(std::size_t n, double* values) {{
  const auto ij = std::size_t{{blockIdx.x}} * blockDim.x + threadIdx.x;
  if (ij >= n * n || ij / n >= ij % n) return;
  const auto ji = (ij % n) * n + ij / n;
  values[ij] = values[ji] = .5 * values[ij] + .5 * values[ji];
}}
}}  // namespace detail

inline void launch_symmetric_matrix_function_vjp(
    std::size_t n, unsigned function, const double* eigenvectors,
    const double* eigenvalues, double relative_threshold, const double* input,
    double* scratch0, double* scratch1, double* output, cudaStream_t stream) {{
  constexpr unsigned threads = 128;
  const auto blocks = static_cast<unsigned>((n * n + threads - 1) / threads);
  detail::symmetric_matrix_function_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 0, function, eigenvectors, eigenvalues, relative_threshold, input, scratch0);
  detail::symmetric_matrix_function_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 1, function, eigenvectors, eigenvalues, relative_threshold, scratch0, scratch1);
  detail::symmetric_matrix_function_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 2, function, eigenvectors, eigenvalues, relative_threshold, scratch1, scratch0);
  detail::symmetric_matrix_function_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 3, function, eigenvectors, eigenvalues, relative_threshold, scratch0, output);
  detail::symmetrize_response<<<blocks, threads, 0, stream>>>(n, output);
}}

inline void launch_symmetric_inverse_sqrt_vjp(
    std::size_t n, const double* eigenvectors, const double* eigenvalues,
    double relative_threshold, const double* input, double* scratch0,
    double* scratch1, double* output, cudaStream_t stream) {{
  launch_symmetric_matrix_function_vjp(
      n, 0, eigenvectors, eigenvalues, relative_threshold, input,
      scratch0, scratch1, output, stream);
}}

inline void launch_symmetric_pseudoinverse_vjp(
    std::size_t n, const double* eigenvectors, const double* eigenvalues,
    double relative_threshold, const double* input, double* scratch0,
    double* scratch1, double* output, cudaStream_t stream) {{
  launch_symmetric_matrix_function_vjp(
      n, 1, eigenvectors, eigenvalues, relative_threshold, input,
      scratch0, scratch1, output, stream);
}}

}}  // namespace vibeqc::tensor
#endif
"""


def emit_pseudoinverse_vjp_cuda() -> str:
    """Backward-compatible name for the shared generated custom-rule header."""
    return emit_symmetric_matrix_function_vjp_cuda()
