"""CUDA lowering for the symmetric matrix-function custom rule.

The scientific rule identity lives in :mod:`matrix_function`.  This module
emits the runtime-sized first-order pseudoinverse adapter used by native DF
plans; allocation, eigensolver ownership, streams, and branch validation stay
native runtime responsibilities.
"""

from __future__ import annotations

from .matrix_function_contract import RULE_VERSIONS


def emit_pseudoinverse_vjp_cuda() -> str:
    """Emit the dynamic-size CUDA lowering for the pseudoinverse VJP."""
    rule = RULE_VERSIONS["pseudoinverse"]
    return f"""// Generated by vibeqc_compiler.method.matrix_function_cuda.
// custom-rule: {rule}
#ifndef VIBEQC_GENERATED_SYMMETRIC_MATRIX_FUNCTION_CUH
#define VIBEQC_GENERATED_SYMMETRIC_MATRIX_FUNCTION_CUH

#include <cuda_runtime.h>

#include <cstddef>

namespace vibeqc::tensor {{
namespace detail {{
static __global__ void pseudoinverse_vjp_stage(
    std::size_t n, unsigned stage, const double* eigenvectors,
    const double* eigenvalues, double relative_threshold,
    const double* input, double* output) {{
  const auto ij = std::size_t{{blockIdx.x}} * blockDim.x + threadIdx.x;
  if (ij >= n * n) return;
  const auto i = ij / n, j = ij % n;
  double value = 0.0;
  for (std::size_t k = 0; k < n; ++k) {{
    if (stage == 0)
      value += (.5 * input[i * n + k] + .5 * input[k * n + i]) *
               eigenvectors[k + j * n];
    if (stage == 1) value += eigenvectors[k + i * n] * input[k * n + j];
    if (stage == 2) value += eigenvectors[i + k * n] * input[k * n + j];
    if (stage == 3) value += input[i * n + k] * eigenvectors[j + k * n];
  }}
  if (stage == 1) {{
    const double li = eigenvalues[i], lj = eigenvalues[j];
    const double cutoff = relative_threshold * eigenvalues[n - 1];
    const bool ki = li > cutoff, kj = lj > cutoff;
    double divided = 0.0;
    if (ki && kj)
      divided = -1.0 / li / lj;
    else if (ki != kj)
      divided = ((ki ? 1.0 / li : 0.0) - (kj ? 1.0 / lj : 0.0)) /
                (li - lj);
    value *= divided;
  }}
  output[ij] = value;
}}

static __global__ void symmetrize_response(std::size_t n, double* values) {{
  const auto ij = std::size_t{{blockIdx.x}} * blockDim.x + threadIdx.x;
  if (ij >= n * n || ij / n >= ij % n) return;
  const auto ji = (ij % n) * n + ij / n;
  values[ij] = values[ji] = .5 * values[ij] + .5 * values[ji];
}}
}}  // namespace detail

inline void launch_symmetric_pseudoinverse_vjp(
    std::size_t n, const double* eigenvectors, const double* eigenvalues,
    double relative_threshold, const double* input, double* scratch0,
    double* scratch1, double* output, cudaStream_t stream) {{
  constexpr unsigned threads = 128;
  const auto blocks = static_cast<unsigned>((n * n + threads - 1) / threads);
  detail::pseudoinverse_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 0, eigenvectors, eigenvalues, relative_threshold, input, scratch0);
  detail::pseudoinverse_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 1, eigenvectors, eigenvalues, relative_threshold, scratch0, scratch1);
  detail::pseudoinverse_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 2, eigenvectors, eigenvalues, relative_threshold, scratch1, scratch0);
  detail::pseudoinverse_vjp_stage<<<blocks, threads, 0, stream>>>(
      n, 3, eigenvectors, eigenvalues, relative_threshold, scratch0, output);
  detail::symmetrize_response<<<blocks, threads, 0, stream>>>(n, output);
}}

}}  // namespace vibeqc::tensor
#endif
"""
