"""Compact semilocal tile contractions on one fixed quadrature/mask branch.

Scalar functional derivatives and ingredient pullbacks are generated by the
existing Graph. This module owns their AO contractions, including response
and explicit geometry sources; it owns no SCF/response solver or AO^4 kernel.
"""

from dataclasses import dataclass

import numpy as np

from vibeqc_compiler.common.arrays import immutable
from vibeqc_compiler.dft.ao import jet_indices
from vibeqc_compiler.dft.features import density_features, spin_densities

from .coefficients import coefficient_program, jet_pullback_program
from .contracts import DerivativeRequest, DiscreteEnergyContract
from .potential import assemble_coefficients
from .program import build_program
from .spec import UnsupportedXC


def _pack(spec, features):
    """Use the existing scalar ABI without evaluating unused sigma/tau reductions.

    Zero placeholders occupy inactive ABI slots only. The typed functional
    contract proves that the requested energy/derivatives do not depend on
    those slots; unsupported physical derivatives are never filled with zeros.
    """
    rho = features["rho"]
    result = np.zeros((len(spec.features), rho.shape[1]))
    if spec.spin == "polarized":
        result[:2] = rho
        if "sigma" in features:
            result[2:5] = features["sigma"]
    else:
        result[0] = rho.sum(axis=0)
        if "sigma" in features:
            aa, ab, bb = features["sigma"]
            result[1] = aa + 2 * ab + bb
    return result


def _functional_gradient(spec, features):
    gradient = features.get("gradient")
    return (
        gradient
        if gradient is None or spec.spin == "polarized"
        else gradient.sum(axis=0)
    )


def _weighted_energy(weights, values):
    """Reject overflow in quadrature even when every scalar point is finite."""
    with np.errstate(over="ignore", invalid="ignore"):
        energy = float(weights @ values)
    if not np.isfinite(energy):
        raise ArithmeticError("nonfinite integrated XC energy")
    return energy


def _response_features(reference, linear):
    """Differentiate nonlinear sigma at the reference, keeping linear fields."""
    result = dict(linear)
    if "gradient" in linear:
        g, dg = reference["gradient"], linear["gradient"]
        result["sigma"] = immutable(
            np.stack(
                [
                    np.sum(g[a] * dg[b] + dg[a] * g[b], axis=1)
                    for a, b in ((0, 0), (0, 1), (1, 1))
                ]
            )
        )
    return result


def density_feature_response(jets, density, delta_density):
    """Legacy full-feature response adapter with one common scientific owner.

    The semilocal contraction consumer below prunes tau and LDA gradients;
    this diagnostic helper preserves the existing full feature API.
    """
    reference = density_features(jets, density, ingredients=("gradient",))
    linear = density_features(
        jets, delta_density, ingredients=("rho", "gradient", "tau")
    )
    return _response_features(reference, linear)


@dataclass(frozen=True, eq=False)
class GeometryPartials:
    """Explicit gradients at fixed D, normalization parameters and mask.

    ``centers`` is [atom,xyz], ``points`` is [point,xyz], and ``weights`` is
    [point]. Supplied physical motion contracts with these sources once each.
    They exclude orbital response, other energies and stationary/Pulay terms.
    """

    centers: np.ndarray
    points: np.ndarray
    weights: np.ndarray

    def directional(self, *, centers, points, weights):
        """Contract independently supplied basis, grid and measure motion."""
        return float(
            np.sum(self.centers * immutable(centers, shape=self.centers.shape))
            + np.sum(self.points * immutable(points, shape=self.points.shape))
            + np.sum(self.weights * immutable(weights, shape=self.weights.shape))
        )


class ContractionProgram:
    """Generate minimal tile E/V, density response or explicit geometric partials.

    Arrays are bounded by the caller's tile. Potentials/responses retain
    functional-spin layout (one channel for unpolarized, two for polarized);
    integration adapters own conversion back to the caller's density layout.
    The diagnostic scalar evaluator is replaceable by the matching native
    program without changing any scientific contraction.
    """

    def __init__(self, spec, observable="potential"):
        self.contract = DiscreteEnergyContract(spec, DerivativeRequest(observable))
        self.program = build_program(
            spec,
            order=self.contract.request.scalar_order,
            outputs=self.contract.scalar_outputs,
        )
        ingredients = self.contract.ingredients
        self.coefficients = coefficient_program(spec.spin, ingredients.family)
        self.response_coefficients = (
            coefficient_program(spec.spin, ingredients.family, response=True)
            if observable == "response"
            else None
        )
        self.jet_pullback = (
            jet_pullback_program(ingredients.family)
            if observable == "geometry"
            else None
        )

    @property
    def spec(self):
        return self.contract.functional

    def features(self, jets, density):
        """Perform only the ingredient reductions declared by this functional."""
        requested = (
            ("rho",)
            if self.contract.ingredients.family == "lda"
            else ("rho", "gradient", "sigma")
        )
        return density_features(jets, density, ingredients=requested)

    def scalar_values(self, features):
        """Evaluate only declared roots; keep their derivative labels explicit."""
        raw = self.program.evaluate(_pack(self.spec, features))
        return dict(zip(self.program.outputs, raw, strict=True))

    def _gradient(self, rows, npoint):
        result = np.zeros((len(self.spec.features), npoint))
        for index in self.contract.ingredients.feature_indices:
            result[index] = rows[(index,)]
        return result

    def potential_tile(self, jets, features, weights):
        """Consume complete-density features from a validated collocation owner.

        FixedDensityXC and local-task adapters share this entry point so
        native collocation does not have to repeat its feature reductions.
        Partial AO density contributions must be combined before this call.
        """
        if self.contract.request.observable != "potential":
            raise ValueError("potential tile requires a potential request")
        weights = immutable(weights, shape=(jets.shape[1],))
        rows = self.scalar_values(features)
        v = self._gradient(rows, jets.shape[1])
        coefficients = self.coefficients.evaluate(
            _functional_gradient(self.spec, features), v
        )
        return {
            "energy": _weighted_energy(weights, rows[()]),
            "potential": assemble_coefficients(jets, coefficients, weights),
            "electrons": immutable(features["rho"] @ weights),
        }

    def evaluate(
        self, jets, density, weights, *, delta_density=None, ao_atoms=None, natom=None
    ):
        """Return exactly the requested observable for a complete-density tile.

        Geometry requires one extra spatial jet and an explicit AO-to-atom
        map. Response directions may be indefinite but must be real symmetric;
        cross-spin Hessian terms are preserved before AO assembly.
        """
        jets, weights = immutable(jets), immutable(weights)
        required = len(jet_indices(self.contract.ao_order))
        if (
            jets.ndim != 3
            or jets.shape[0] not in (1, 4, 10, 20)
            or jets.shape[0] < required
            or weights.shape != (jets.shape[1],)
        ):
            raise ValueError("XC contraction requires its declared AO/point domain")
        d = spin_densities(density, jets.shape[2])
        if self.spec.spin == "unpolarized" and not np.array_equal(d[0], d[1]):
            raise UnsupportedXC("unpolarized contractions require equal spin matrices")
        observable = self.contract.request.observable
        if observable != "response" and delta_density is not None:
            raise ValueError("density direction requires a response request")
        if observable != "geometry" and (ao_atoms is not None or natom is not None):
            raise ValueError("AO-center map requires a geometric request")
        features = self.features(jets, d)
        if observable == "potential":
            return self.potential_tile(jets, features, weights)
        rows = self.scalar_values(features)
        result = {
            "energy": _weighted_energy(weights, rows[()]),
            "electrons": immutable(features["rho"] @ weights),
        }
        if observable == "energy":
            return result
        v = self._gradient(rows, jets.shape[1])
        gradient = _functional_gradient(self.spec, features)
        if observable == "response":
            dd = spin_densities(delta_density, jets.shape[2])
            if self.spec.spin == "unpolarized" and not np.array_equal(dd[0], dd[1]):
                raise UnsupportedXC(
                    "unpolarized response requires equal spin directions"
                )
            # rho and grad(rho) are linear in D. Sigma is differentiated at
            # the reference gradients, not evaluated nonlinearly at delta-D.
            requested = ("rho",) if gradient is None else ("rho", "gradient")
            delta = _response_features(
                features, density_features(jets, dd, ingredients=requested)
            )
            direction = _pack(self.spec, delta)
            dv = np.zeros_like(v)
            indices = self.contract.ingredients.feature_indices
            for i in indices:
                for j in indices:
                    dv[i] += rows[(min(i, j), max(i, j))] * direction[j]
            response = self.response_coefficients.evaluate(
                gradient,
                v,
                delta_gradient=_functional_gradient(self.spec, delta),
                delta_v=dv,
            )
            result["response"] = assemble_coefficients(jets, response, weights)
        else:
            coefficients = self.coefficients.evaluate(gradient, v)
            result["geometry"] = self._geometry(
                jets, d, weights, coefficients, rows[()], ao_atoms, natom
            )
        return result

    def _geometry(self, jets, density, weights, coefficients, energy, ao_atoms, natom):
        """Pull back compact AO bilinears, then split translation sources.

        A normalized AO depends on r-R_A; ordinary spatial jets therefore
        supply point motion with positive sign and its own center motion with
        negative sign. Weight derivatives are e_xc, without a second weight.
        """
        atoms = np.asarray(ao_atoms)
        if (
            type(natom) is not int
            or natom < 1
            or atoms.shape != (jets.shape[2],)
            or atoms.dtype.kind not in "iu"
            or np.any(atoms < 0)
            or np.any(atoms >= natom)
        ):
            raise ValueError("geometry requires a valid integer AO-to-atom map")
        order = self.contract.ingredients.ao_order
        domain = jet_indices(order)
        lookup = {axis: i for i, axis in enumerate(jet_indices(self.contract.ao_order))}
        d = density if self.spec.spin == "polarized" else density.sum(axis=0)[None]
        pullback = np.zeros((len(domain), *jets.shape[1:]))
        for spin in range(len(d)):
            work = np.stack([jets[j] @ d[spin] for j in range(len(domain))])
            weighted = {"rho": weights * coefficients["rho"][spin]}
            if order:
                weighted["gradient"] = weights[:, None] * coefficients["gradient"][spin]
            pullback += self.jet_pullback.evaluate(weighted, work)
        centers = np.zeros((natom, 3))
        points = np.zeros((jets.shape[1], 3))
        for k in range(3):
            # Retain only one point-by-AO directional panel at a time.
            panel = np.zeros(jets.shape[1:])
            for j, axis in enumerate(domain):
                shifted = list(axis)
                shifted[k] += 1
                panel += pullback[j] * jets[lookup[tuple(shifted)]]
            points[:, k] = panel.sum(axis=1)
            np.add.at(centers[:, k], atoms, -panel.sum(axis=0))
        return GeometryPartials(
            immutable(centers), immutable(points), immutable(energy)
        )
