"""Generate the compact production D3(BJ) table from pinned xTBloom data."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import source_registry

_D3_SOURCE_ID = "xtbloom-gfn1-d3"
_MODEL_SOURCE_ID = "xtbloom-gfn1-parameters"
_REQUIRED_SOURCE_FILES = frozenset({"gfn1_d3.json", "gfn1.json"})
MANIFEST = ROOT / "manifests" / "xtbloom-d3.json"
DEFAULT_OUTPUT = ROOT / "src" / "dft" / "dispersion" / "d3_data.hpp"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _registered_source_texts() -> tuple[dict[str, str], str]:
    """Load exact D3/GFN1 texts through their common-registry owners."""
    registry = source_registry._load(source_registry.REGISTRY)
    result: dict[str, str] = {}
    common_revision: str | None = None
    for source_id, required in (
        (_D3_SOURCE_ID, ("gfn1_d3.json",)),
        (_MODEL_SOURCE_ID, ("gfn1.json",)),
    ):
        source = registry["sources"].get(source_id)
        if not isinstance(source, dict):
            raise source_registry.SourceRegistryError(
                f"source registry is missing {source_id!r}"
            )
        revision = source.get("revision")
        if not isinstance(revision, str) or not revision:
            raise source_registry.SourceRegistryError(
                f"source registry has invalid revision for {source_id!r}"
            )
        if common_revision is None:
            common_revision = revision
        elif revision != common_revision:
            raise source_registry.SourceRegistryError(
                "D3 and GFN1 source owners must pin the same upstream revision"
            )
        texts = source_registry.read_source_texts(source_id, source)
        missing = set(required) - texts.keys()
        if missing:
            raise source_registry.SourceRegistryError(
                f"{source_id!r} is missing required files: {sorted(missing)}"
            )
        result.update({name: texts[name] for name in required})
    if common_revision is None:
        raise source_registry.SourceRegistryError("registered D3 sources are empty")
    return (
        {name: result[name] for name in sorted(_REQUIRED_SOURCE_FILES)},
        common_revision,
    )


def _real(value: float) -> str:
    value = float(value)
    if value == 0.0:
        return "0.0"
    return value.hex()


def render() -> str:
    manifest = json.loads(MANIFEST.read_text())
    expected = manifest["data"]
    source_texts, source_revision = _registered_source_texts()
    table_raw = source_texts["gfn1_d3.json"].encode("utf-8")
    model_raw = source_texts["gfn1.json"].encode("utf-8")
    if sha256(table_raw) != expected["gfn1_d3.json"]:
        raise RuntimeError("gfn1_d3.json digest mismatch")
    if sha256(model_raw) != manifest["sources"]["data/parameters/gfn1.json"]["sha256"]:
        raise RuntimeError("gfn1.json digest mismatch")

    source = json.loads(table_raw)
    model = json.loads(model_raw)
    if [item["atomic_number"] for item in model["elements"]] != list(range(1, 87)):
        raise RuntimeError("upstream GFN1 element order changed")
    radii = [item["covalent_radius_bohr"] for item in model["elements"]]
    radii_bytes = (json.dumps(radii, indent=2) + "\n").encode()
    if hashlib.sha256(radii_bytes).hexdigest() != expected["covalent_radii.json"]:
        raise RuntimeError("derived covalent radii digest mismatch")
    elements = source["elements"]
    pairs = source["pair_records"]
    refs = source["coordination_numbers"]
    c6 = source["c6"]
    r4r2 = source["r4r2"]
    vdw = source["vdw_radii"]
    if len(elements) != 86 or len(radii) != 86 or len(r4r2) != 86:
        raise RuntimeError("production D3 table must cover exactly H through Rn")
    if len(pairs) != 86 * 87 // 2 or len(vdw) != len(pairs):
        raise RuntimeError("unexpected packed element-pair count")
    if any(e["reference_count"] > 7 for e in elements):
        raise RuntimeError(
            "D3 production layout supports at most seven references per element"
        )

    out = [
        "// Generated by tools/vibeqc_d3/generate_native_data.py; do not edit.",
        "// Source/provenance: manifests/xtbloom-d3.json.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace vibeqc::dft::dispersion::d3_data {",
        f'inline constexpr char kTableSha256[] = "{expected["gfn1_d3.json"]}";',
        f'inline constexpr char kRadiiSha256[] = "{expected["covalent_radii.json"]}";',
        f'inline constexpr char kVersion[] = "xtbloom-d3-{source_revision[:7]}-production-v1";',
        "",
        "struct ElementData {",
        "  std::uint32_t reference_offset;",
        "  std::uint8_t reference_count;",
        "  double covalent_radius;",
        "  double r4r2;",
        "};",
        "struct PairData {",
        "  std::uint32_t c6_offset;",
        "  std::uint8_t first_reference_count;",
        "  std::uint8_t second_reference_count;",
        "  double vdw_radius;",
        "};",
        "",
        f"inline constexpr std::array<ElementData, {len(elements)}> kElements{{{{",
    ]
    for i, e in enumerate(elements):
        out.append(
            "    ElementData{"
            f"{int(e['reference_offset'])}u, {int(e['reference_count'])}u, "
            f"{_real(radii[i])}, {_real(r4r2[i])}"
            "},"
        )
    out.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<double, {len(refs)}> kReferenceCn{{{{",
        ]
    )
    for i in range(0, len(refs), 4):
        out.append("    " + ", ".join(_real(x) for x in refs[i : i + 4]) + ",")
    out.extend(
        ["}};", "", f"inline constexpr std::array<PairData, {len(pairs)}> kPairs{{{{"]
    )
    for p, radius in zip(pairs, vdw):
        out.append(
            "    PairData{"
            f"{int(p['c6_offset'])}u, {int(p['first_reference_count'])}u, "
            f"{int(p['second_reference_count'])}u, {_real(radius)}"
            "},"
        )
    out.extend(
        ["}};", "", f"inline constexpr std::array<double, {len(c6)}> kReferenceC6{{{{"]
    )
    for i in range(0, len(c6), 4):
        out.append("    " + ", ".join(_real(x) for x in c6[i : i + 4]) + ",")
    out.extend(
        [
            "}};",
            "",
            "}  // namespace vibeqc::dft::dispersion::d3_data",
            "",
        ]
    )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            raise SystemExit(f"{args.output} is stale; regenerate it")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)


if __name__ == "__main__":
    main()
