"""Generate the compact production D3(BJ) table from pinned xTBloom data."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "external" / "xtbloom-d3"
DEFAULT_OUTPUT = ROOT / "src" / "dft" / "dispersion" / "d3_data.hpp"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _real(value: float) -> str:
    value = float(value)
    if value == 0.0:
        return "0.0"
    return value.hex()


def render() -> str:
    manifest = json.loads((DATA / "manifest.json").read_text())
    expected = manifest["data"]
    for name, digest in expected.items():
        actual = sha256(DATA / name)
        if actual != digest:
            raise RuntimeError(f"{name} digest mismatch: {actual} != {digest}")

    source = json.loads((DATA / "gfn1_d3.json").read_text())
    radii = json.loads((DATA / "covalent_radii.json").read_text())
    elements = source["elements"]
    pairs = source["pair_records"]
    refs = source["coordination_numbers"]
    c6 = source["c6"]
    r4r2 = source["r4r2"]
    if len(elements) != 86 or len(radii) != 86 or len(r4r2) != 86:
        raise RuntimeError("production D3 table must cover exactly H through Rn")
    if len(pairs) != 86 * 87 // 2:
        raise RuntimeError("unexpected packed element-pair count")
    if any(e["reference_count"] > 7 for e in elements):
        raise RuntimeError(
            "D3 production layout supports at most seven references per element"
        )

    out = [
        "// Generated by tools/vibeqc_d3/generate_native_data.py; do not edit.",
        "// Source/provenance: external/xtbloom-d3/manifest.json.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace vibeqc::dft::dispersion::d3_data {",
        f'inline constexpr char kTableSha256[] = "{expected["gfn1_d3.json"]}";',
        f'inline constexpr char kRadiiSha256[] = "{expected["covalent_radii.json"]}";',
        'inline constexpr char kVersion[] = "xtbloom-d3-2cbdf1d-production-v1";',
        "",
        "struct ElementData {",
        "  std::uint32_t reference_offset;",
        "  std::uint8_t reference_count;",
        "  double covalent_radius;",
        "  double r4r2;",
        "};",
        "struct PairData {",
        "  std::uint32_t c6_offset;",
        "  std::uint8_t first_reference_count;",
        "  std::uint8_t second_reference_count;",
        "};",
        "",
        f"inline constexpr std::array<ElementData, {len(elements)}> kElements{{{{",
    ]
    for i, e in enumerate(elements):
        out.append(
            "    ElementData{"
            f"{int(e['reference_offset'])}u, {int(e['reference_count'])}u, "
            f"{_real(radii[i])}, {_real(r4r2[i])}"
            "},"
        )
    out.extend(
        [
            "}};",
            "",
            f"inline constexpr std::array<double, {len(refs)}> kReferenceCn{{{{",
        ]
    )
    for i in range(0, len(refs), 4):
        out.append("    " + ", ".join(_real(x) for x in refs[i : i + 4]) + ",")
    out.extend(
        ["}};", "", f"inline constexpr std::array<PairData, {len(pairs)}> kPairs{{{{"]
    )
    for p in pairs:
        out.append(
            "    PairData{"
            f"{int(p['c6_offset'])}u, {int(p['first_reference_count'])}u, "
            f"{int(p['second_reference_count'])}u"
            "},"
        )
    out.extend(
        ["}};", "", f"inline constexpr std::array<double, {len(c6)}> kReferenceC6{{{{"]
    )
    for i in range(0, len(c6), 4):
        out.append("    " + ", ".join(_real(x) for x in c6[i : i + 4]) + ",")
    out.extend(
        [
            "}};",
            "",
            "}  // namespace vibeqc::dft::dispersion::d3_data",
            "",
        ]
    )
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            raise SystemExit(f"{args.output} is stale; regenerate it")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)


if __name__ == "__main__":
    main()
