"""Generate the native D3(BJ) table from VibeQC's compact production product."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; PYTHON_ROOT=ROOT/"python"
if str(PYTHON_ROOT) not in sys.path: sys.path.insert(0,str(PYTHON_ROOT))
from vibeqc_compiler.common.d3_data import load_d3_production_data
MANIFEST=ROOT/"manifests/xtbloom-d3.json"; DATA=ROOT/"data/parameters/d3_production.bin"; DEFAULT_OUTPUT=ROOT/"src/dft/dispersion/d3_data.hpp"
def _real(v:float)->str:
    v=float(v);return "0.0" if v==0.0 else v.hex()
def render()->str:
    m=json.loads(MANIFEST.read_text());e=m["data"];d=load_d3_production_data(DATA)
    if d.table_sha256!=e["gfn1_d3.json"] or d.radii_sha256!=e["covalent_radii.json"]: raise RuntimeError("compact D3 provenance mismatch")
    if any(x.reference_count>7 for x in d.elements): raise RuntimeError("D3 supports at most seven references per element")
    o=["// Generated by tools/vibeqc_d3/generate_native_data.py; do not edit.","// Source/provenance: manifests/xtbloom-d3.json.","#pragma once","","#include <array>","#include <cstdint>","","namespace vibeqc::dft::dispersion::d3_data {",f'inline constexpr char kTableSha256[] = "{d.table_sha256}";',f'inline constexpr char kRadiiSha256[] = "{d.radii_sha256}";',f'inline constexpr char kVersion[] = "xtbloom-d3-{d.source_revision[:7]}-production-v1";',"","struct ElementData {","  std::uint32_t reference_offset;","  std::uint8_t reference_count;","  double covalent_radius;","  double r4r2;","};","struct PairData {","  std::uint32_t c6_offset;","  std::uint8_t first_reference_count;","  std::uint8_t second_reference_count;","  double vdw_radius;","};","",f"inline constexpr std::array<ElementData, {len(d.elements)}> kElements{{{{"]
    for i,x in enumerate(d.elements):o.append(f"    ElementData{{{x.reference_offset}u, {x.reference_count}u, {_real(d.covalent_radii[i])}, {_real(d.r4r2[i])}}},")
    o+=["}};","",f"inline constexpr std::array<double, {len(d.coordination_numbers)}> kReferenceCn{{{{"]
    for i in range(0,len(d.coordination_numbers),4):o.append("    "+", ".join(_real(v) for v in d.coordination_numbers[i:i+4])+",")
    o+=["}};","",f"inline constexpr std::array<PairData, {len(d.pairs)}> kPairs{{{{"]
    for i,x in enumerate(d.pairs):o.append(f"    PairData{{{x.c6_offset}u, {x.first_reference_count}u, {x.second_reference_count}u, {_real(d.vdw_radii[i])}}},")
    o+=["}};","",f"inline constexpr std::array<double, {len(d.c6)}> kReferenceC6{{{{"]
    for i in range(0,len(d.c6),4):o.append("    "+", ".join(_real(v) for v in d.c6[i:i+4])+",")
    o+=["}};","","}  // namespace vibeqc::dft::dispersion::d3_data",""];return "\n".join(o)
def main()->None:
    p=argparse.ArgumentParser();p.add_argument("--output",type=Path,default=DEFAULT_OUTPUT);p.add_argument("--check",action="store_true");a=p.parse_args();r=render()
    if a.check:
        if not a.output.exists() or a.output.read_text()!=r: raise SystemExit(f"{a.output} is stale; regenerate it")
        return
    a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(r)
if __name__=="__main__":main()
