#ifndef VIBEQC_SCF_MEAN_FIELD_HPP
#define VIBEQC_SCF_MEAN_FIELD_HPP

#include <memory>
#include <optional>
#include <vector>

#include "core/types.hpp"
#include "scf/cuda_batch.hpp"
#include "scf/density_fitting.hpp"
#include "scf/types.hpp"

namespace vibeqc::scf {

struct CudaDensityFittingMetricDiagnostic;
struct CudaDensityFittingJkPlan;
class PreparedFockPlan;

/** Validate controls and derive the requested value/force capability for this
 * execution without changing the immutable prepared method request. */
ResolvedFockBuild fock_strategy_for_execution(const ScfOptions& options);
ScfResult run_prepared_fock_strategy(const PreparedFockPlan& plan, const ScfOptions& options,
                                     const std::vector<double>* initial_density = nullptr);

/** Reuse independent CUDA sources when immutable inputs match. Build a new
 * candidate completely before replacing cached sources; fused standard HF
 * and the existing CPU storage lifetime retain their established dispatch. */
ScfResult run_fock_strategy_cached(std::unique_ptr<PreparedFockPlan>& cache,
                                   const core::System& system, const core::System* auxiliary,
                                   const ScfOptions& options, int device_id,
                                   const std::vector<double>* initial_density = nullptr);

/** Rebuild only the source overlap on the CPU and apply the shared SCF
 * ensemble-density guard (Hermiticity, metric occupations, electron/spin trace).
 * This does not assert target compatibility or target convergence. */
void validate_hf_warm_density(const core::System& source, vibeqc_method method,
                              const std::vector<double>& density);

/** Execute the existing CPU SCF solver with an explicitly resolved independent
 * J/K model. Iterations, final energy and analytic forces share one provider
 * binding. A null auxiliary pointer uses the orbital basis for requested DF
 * terms. This does not add XC or advertise a complete DFT method.
 */
ScfResult run_cpu_fock_strategy(const core::System& system, const core::System* auxiliary,
                                const ScfOptions& options,
                                const std::vector<double>* initial_density = nullptr);

/** General independent CUDA route. Reuses host DIIS/eigensolve/finalization
 * control with CUDA direct/DF J/K and matched two-electron derivatives. The
 * standard HF entry retains its existing fused device solver separately. */
ScfResult run_cuda_independent_fock_strategy(const core::System& system,
                                             const core::System* auxiliary,
                                             const ScfOptions& options, int device_id,
                                             const std::vector<double>* initial_density = nullptr);

/** Method-neutral single-item dispatch. CPU independent providers and existing
 * CUDA fused HF schedules share this boundary; callers supply semantics through
 * options.resolved_fock_build instead of branching on a combined DF enum.
 */
ScfResult run_fock_strategy(const core::System& system, const core::System* auxiliary,
                            const ScfOptions& options, int device_id,
                            const std::vector<double>* initial_density = nullptr);

/** Run closed-shell RHF and assemble its variational analytic gradient. */
ScfResult run_rhf(const core::System& system, const ScfOptions& options,
                  const std::vector<double>* initial_density = nullptr);

/** Run spin-unrestricted HF and assemble its variational analytic gradient. */
ScfResult run_uhf(const core::System& system, const ScfOptions& options,
                  const std::vector<double>* initial_density = nullptr);

/**
 * Run RHF with a prepared auxiliary topology and the CPU DF reference
 * contractions. The auxiliary atoms are required to have the same geometry
 * as `system`; callers preparing a moving batch should update those positions
 * before invoking the function.
 */
ScfResult run_rhf_density_fitting(const core::System& system, const core::System& auxiliary_system,
                                  const ScfOptions& options,
                                  const std::vector<double>* initial_density = nullptr);

/** UHF counterpart of `run_rhf_density_fitting`. */
ScfResult run_uhf_density_fitting(const core::System& system, const core::System& auxiliary_system,
                                  const ScfOptions& options,
                                  const std::vector<double>* initial_density = nullptr);

/**
 * Execute DF SCF through the CUDA contraction plan. Two-/three-center DF
 * values and their first nuclear derivatives are generated by the CUDA
 * quartet recurrence; one-electron/overlap-Pulay assembly remains host-side
 * in this bridge. Iterative densities, Fock assembly, eigensolves, RI-J/RI-K
 * contractions, and the raw two-electron force response stay on the selected
 * CUDA device when the provider is available.
 */
ScfResult run_rhf_density_fitting_cuda(const core::System& system,
                                       const core::System& auxiliary_system,
                                       const ScfOptions& options, int device_id,
                                       const std::vector<double>* initial_density = nullptr);

/** CUDA DF counterpart for UHF. */
ScfResult run_uhf_density_fitting_cuda(const core::System& system,
                                       const core::System& auxiliary_system,
                                       const ScfOptions& options, int device_id,
                                       const std::vector<double>* initial_density = nullptr);

/**
 * Execute a homogeneous fleet bucket through one batched CUDA DF J/K plan.
 *
 * The returned vector preserves the input order.  A missing auxiliary
 * template means that each orbital basis is also used as its auxiliary basis,
 * matching the single-system DF entry points.  Individual preparation,
 * eigensolver, and convergence failures are isolated to their item whenever
 * the shared batched contractions can still be evaluated.
 */
std::vector<RhfBucketItem> run_rhf_density_fitting_cuda_bucket(
    const std::vector<core::System>& systems, const std::optional<core::System>& auxiliary_template,
    const ScfOptions& options, const std::vector<const std::vector<double>*>& initial_densities,
    int device_id, std::vector<CudaDensityFittingMetricDiagnostic>* diagnostics = nullptr);

/**
 * Cached counterpart used by a persistent FleetPlan. The pointed-to plan is
 * retained by the caller across same-topology replays and may be replaced
 * when the caller invalidates its geometry cache.
 */
std::vector<RhfBucketItem> run_rhf_density_fitting_cuda_bucket_cached(
    CudaDensityFittingJkPlan** plan, const std::vector<core::System>& systems,
    const std::optional<core::System>& auxiliary_template, const ScfOptions& options,
    const std::vector<const std::vector<double>*>& initial_densities, int device_id,
    std::vector<CudaDensityFittingMetricDiagnostic>* diagnostics = nullptr,
    std::vector<std::optional<DensityFittingScfData>>* prepared_cache = nullptr);

/** UHF counterpart of the batched CUDA DF bucket executor. */
std::vector<RhfBucketItem> run_uhf_density_fitting_cuda_bucket(
    const std::vector<core::System>& systems, const std::optional<core::System>& auxiliary_template,
    const ScfOptions& options, const std::vector<const std::vector<double>*>& initial_densities,
    int device_id, std::vector<CudaDensityFittingMetricDiagnostic>* diagnostics = nullptr);

/** Cached UHF counterpart for persistent FleetPlan replay. */
std::vector<RhfBucketItem> run_uhf_density_fitting_cuda_bucket_cached(
    CudaDensityFittingJkPlan** plan, const std::vector<core::System>& systems,
    const std::optional<core::System>& auxiliary_template, const ScfOptions& options,
    const std::vector<const std::vector<double>*>& initial_densities, int device_id,
    std::vector<CudaDensityFittingMetricDiagnostic>* diagnostics = nullptr,
    std::vector<std::optional<DensityFittingScfData>>* prepared_cache = nullptr);

/** Execute RHF through the native CUDA scientific path. */
ScfResult run_rhf_cuda(const core::System& system, const ScfOptions& options, int device_id,
                       const std::vector<double>* initial_density = nullptr);

/** Execute UHF through the native CUDA scientific path. */
ScfResult run_uhf_cuda(const core::System& system, const ScfOptions& options, int device_id,
                       const std::vector<double>* initial_density = nullptr);

}  // namespace vibeqc::scf

#endif
