#ifndef VIBEQC_XTB_RUNTIME_BACKEND_HPP
// xtbloom's CUDA/MKL additional permission is in CUDA_MKL_LINKING_EXCEPTION.

#define VIBEQC_XTB_RUNTIME_BACKEND_HPP

#include <cstdint>
#include <string>

#include "runtime/types.hpp"

namespace vibeqc::xtb::detail {

// Only native CUDA device admission and parameter residency are declared
// here. Context/cache ownership belongs to Gfn2RuntimeBridge; the imported
// external context and GFN1 cache API had no implementation or consumers.
#if defined(VIBEQC_XTB_HAS_CUDA)
bool resolve_cuda_device(std::int32_t requested_device, std::int32_t& resolved_device,
                         std::string& error);

/* Upload immutable GFN2 tables once for each CUDA device used by this process. */
bool ensure_cuda_gfn2_parameters(std::int32_t device_id, std::string& error);

/* Internal observability used to prove that repeated contexts reuse the upload. */
std::uint64_t cuda_gfn2_parameter_upload_count(std::int32_t device_id);

/* Test hook that copies constant memory back and compares every generated byte. */
bool cuda_gfn2_parameters_match_host(std::int32_t device_id, std::string& error);
#endif

}  // namespace vibeqc::xtb::detail

#endif  // VIBEQC_XTB_RUNTIME_BACKEND_HPP
