"""ECP operator IR and generated Gaussian center-derivative quadrature kernels."""

from dataclasses import replace

from .blocks import RawBlock, TensorLayout, WeightDescriptor, WeightedDerivative
from .expr import Graph
from .ir import (
    EcpCenter,
    OperatorSpec,
    TranslationInvariant,
    build_integral_ir,
)
from .scalar_c import ScalarCEmitter
from .shell_signature import BasisShell, CenterBinding, ShellSignature
from .shell_spec import cartesian_components


def build_ecp_ir(angular, terms, *, derivatives=False, weighted=False):
    """Preserve A/B/C and generic weighted semantics before atom mapping."""
    if len(angular) != 2:
        raise ValueError("ECP requires two orbital shell slots")
    signature = ShellSignature(
        tuple(BasisShell(i, i, l) for i, l in enumerate(angular)),
        tuple(CenterBinding(i) for i in range(3)),
    )
    operator = OperatorSpec(
        "scalar_ecp",
        (0, 1, 2),
        (TranslationInvariant(),),
        (EcpCenter(2, tuple(terms)),),
        ((0, 1), (1, 0)),
    )
    matrix = TensorLayout(signature.tensor_indices, signature.component_shape)
    integral = build_integral_ir(
        signature,
        operator=operator,
        contractions=(RawBlock(matrix, matrix.storage_bytes),),
        recurrence="ecp_quadrature",
    )
    if weighted and not derivatives:
        raise ValueError("weighted ECP contractions require derivatives")
    if not derivatives:
        return integral
    layout = TensorLayout(("center", "xyz"), (3, 3))
    if weighted:
        consumer = WeightedDerivative(
            WeightDescriptor("ecp_weight", matrix), layout, layout.storage_bytes
        )
    else:
        layout = TensorLayout(
            layout.indices + matrix.indices, layout.shape + matrix.shape
        )
        consumer = RawBlock(layout, layout.storage_bytes)
    return replace(
        integral, derivative=operator.nuclear_derivative(), contractions=(consumer,)
    )


def gaussian_roots(component):
    """Differentiate AO centers symbolically before emitting device arithmetic."""
    graph = Graph()
    xyz = [graph.variable(a) for a in "xyz"]
    alpha = graph.variable("alpha")
    value = graph.exponential(-alpha * graph.sum(x * x for x in xyz))
    for axis, coordinate in zip("xyz", xyz, strict=True):
        for _ in range(component.count(axis)):
            value = value * coordinate
    return graph, (value, *(-graph.differentiate(value, x) for x in xyz))


def emit_ecp_ao_cuda():
    """Specialize all validated Cartesian components; no runtime AD."""
    lines = [
        "#pragma once",
        "// Generated by tools/generate_ecp_kernels.py.",
        "namespace vibeqc::generated {",
        "__device__ inline void ecp_ao(unsigned lx,unsigned ly,unsigned lz,",
        "    double x,double y,double z,double alpha,double* out) {",
        "  switch (16*lx+4*ly+lz) {",
    ]
    for l in range(3):
        for component in cartesian_components(l):
            graph, roots = gaussian_roots(component)
            emitter = ScalarCEmitter(graph, {})
            emitter.emit(roots)
            key = (
                16 * component.count("x")
                + 4 * component.count("y")
                + component.count("z")
            )
            lines += [
                f"case {key}: {{",
                *emitter.lines,
                *(
                    f"out[{i}]={emitter.reference(root)};"
                    for i, root in enumerate(roots)
                ),
                "return; }",
            ]
    return "\n".join(lines + ["}", "for(int i=0;i<4;++i) out[i]=0;", "}", "}", ""])
