"""Lower the S/T/V execution policy onto the reusable native AO-pair schedule.

Scalar operator helpers remain in ``one_electron_cuda``. This separate artifact
keeps their source identity stable while moving operator composition and output
semantics into the compiler. Native traversal knows no S/T/V formulas, nuclear
charge convention or number of scientific channels.
"""

from .cuda import CudaEmitter
from .expr import Graph
from .one_electron_values import build_one_electron_value_ir


def one_electron_policy_inventory():
    """Version the normalized contraction/output ABI independently of scalars."""
    return {
        "schema": "vibeqc.one_electron_pair_policy",
        "version": 1,
        "runtime": "cuda_ao_pairs",
        "primitive_families": ["overlap", "kinetic", "nuclear_attraction"],
        "accumulators": ["overlap", "kinetic", "attraction"],
        "outputs": ["overlap", "hcore", "kinetic", "attraction"],
        "normalization": "public_ao_expansion_and_primitive_coefficients",
        "nuclear_attraction": "signed_unit_charge_times_current_nuclear_charge",
        "schedules": ["thread", "shell_warp"],
    }


def emit_one_electron_policy_cuda():
    """Emit operator composition for all supported Cartesian/spherical shells.

    No shell-specific glue is emitted: component dispatch is shared with the
    scalar family, and the typed runtime supplies normalized AO/primitive loops.
    Attraction is reduced over every nucleus before the primitive is weighted.
    Output combinations use the existing expression emitter, including H=T+V.
    """
    for family in one_electron_policy_inventory()["primitive_families"]:
        # Fail closed if the scalar IR no longer supports this value contract.
        build_one_electron_value_ir(family, (0, 0))
    graph = Graph()
    s, t, v = (
        graph.variable("result." + n) for n in ("overlap", "kinetic", "attraction")
    )
    emitter = CudaEmitter(graph, {})
    for index, expression in enumerate((s, t + v, t, v)):
        emitter.emit_assignment(expression, f"values[{index}]")
    prefix = r"""// Generated by tools/generate_one_electron_kernels.py; do not edit.
#ifndef VIBEQC_GENERATED_ONE_ELECTRON_POLICY_CUH
#define VIBEQC_GENERATED_ONE_ELECTRON_POLICY_CUH
#include "generated_one_electron_values.cuh"
namespace vibeqc::scf::generated_one_electron {
/** Scientific policy for the normalized AO-pair runtime contract. */
struct ValuePolicy {
  static constexpr unsigned channels = 4;
  struct Accumulator { double overlap{}, kinetic{}, attraction{}; };
  __device__ static PairGeometry prepare(double a, double b, const double* A, const double* B) {
    return make_pair(a, b, A[0], A[1], A[2], B[0], B[1], B[2]);
  }
  __device__ static unsigned component(const unsigned char* powers) {
    return component_index(powers[0], powers[1], powers[2]);
  }
  template<class View>
  __device__ static void accumulate(Accumulator& result, const PairGeometry& pair,
      unsigned first, unsigned second, double weight, const View& batch, long long system) {
    const auto st = overlap_kinetic(pair, first, second);
    double v = 0.0;
    for (auto atom = batch.atom_offsets[system]; atom < batch.atom_offsets[system + 1]; ++atom) {
      const double* C = batch.positions + 3 * atom;
      v += batch.atomic_numbers[atom] * attraction(pair, first, second, C[0], C[1], C[2]);
    }
    result.overlap += weight * st.overlap;
    result.kinetic += weight * st.kinetic;
    result.attraction += weight * v;
  }
  __device__ static void project(const Accumulator& result, double (&values)[channels]) {
"""
    return "\n".join([prefix, *emitter.lines, "  }", "};", "}", "#endif", ""])
