"""Compiler-owned CUDA schedule policy for generated one-electron derivatives."""

from __future__ import annotations

from dataclasses import asdict
from typing import TYPE_CHECKING

from vibeqc_compiler.common.backend import TargetInfo
from vibeqc_compiler.common.cuda_target import CUDA_TARGETS
from vibeqc_compiler.common.provenance import canonical_hash
from vibeqc_compiler.common.specialization import WorkloadSignature
from vibeqc_compiler.integral.cooperative_schedule import (
    CooperativeLaneSchedule,
    cooperative_schedule_contract,
)

if TYPE_CHECKING:
    from vibeqc_compiler.common.schedule import ScheduleContract

NUCLEUS_COOPERATIVE_SCHEDULE_CODE = 3
_PREFERRED_GROUPS_PER_WORKGROUP = 4


def nucleus_cooperative_schedule(target: TargetInfo) -> CooperativeLaneSchedule:
    """Resolve one AO-pair cooperative group from explicit target resources."""
    if target.backend != "cuda" or target.subgroup_size is None:
        raise ValueError("nucleus-cooperative lowering requires a CUDA subgroup target")
    groups = min(
        _PREFERRED_GROUPS_PER_WORKGROUP,
        target.maximum_workgroup_threads // target.subgroup_size,
    )
    if groups < 1:
        raise ValueError("target cannot host one nucleus-cooperative group")
    schedule = CooperativeLaneSchedule(
        subgroup_size=target.subgroup_size,
        lanes_per_group=target.subgroup_size,
        groups_per_workgroup=groups,
        shared_state=True,
        group_reduction=True,
    )
    schedule.validate_for(target)
    return schedule


def production_nucleus_cooperative_schedule() -> CooperativeLaneSchedule:
    """Return one schedule legal across every supported CUDA architecture."""
    targets = tuple(item.target_info for item in CUDA_TARGETS.values())
    subgroup_sizes = {target.subgroup_size for target in targets}
    if len(subgroup_sizes) != 1:
        raise ValueError("supported CUDA targets disagree on subgroup size")
    target = TargetInfo(
        backend="cuda",
        architecture="supported-cuda-catalog",
        subgroup_size=targets[0].subgroup_size,
        maximum_workgroup_threads=min(t.maximum_workgroup_threads for t in targets),
        maximum_resident_workgroups=min(
            t.maximum_resident_workgroups
            for t in targets
            if t.maximum_resident_workgroups
        ),
    )
    schedule = nucleus_cooperative_schedule(target)
    for candidate in targets:
        schedule.validate_for(candidate)
    return schedule


def one_electron_derivative_workload() -> WorkloadSignature:
    """Return the shared profile-key input for the production schedule.

    #693 deliberately promoted one schedule across measured 29-768 AO holdouts,
    so no AO-count, molecule, or product-name threshold belongs here. #597 can
    add general workload features later without creating a local profile stack.
    """

    return WorkloadSignature(
        "one-electron-derivative",
        (
            ("cooperative_axis", "nuclear_center"),
            ("precision", "fp64"),
            ("task_axis", "ao_pair"),
        ),
    )


def one_electron_derivative_schedule_contract(target: TargetInfo) -> ScheduleContract:
    """Bind cooperative ownership to shared workload/target/profile identity."""

    workload = one_electron_derivative_workload()
    workload_hash = canonical_hash(asdict(workload))
    return cooperative_schedule_contract(
        nucleus_cooperative_schedule(target),
        consumer="integral.one_electron_derivative",
        target=target,
        workload_hash=workload_hash,
        profile_key=workload_hash,
        provenance=(
            ("policy", "generated-nucleus-cooperative"),
            ("profile_owner", "compiler-specialization-target-profile"),
        ),
    )


def one_electron_derivative_policy_inventory() -> dict[str, object]:
    """Serialize execution ownership separately from the scientific DAG."""
    schedule = production_nucleus_cooperative_schedule()
    workload = one_electron_derivative_workload()
    contracts = {
        architecture: one_electron_derivative_schedule_contract(
            target.target_info
        ).to_payload()
        for architecture, target in sorted(CUDA_TARGETS.items())
    }
    return {
        "schema": "vibeqc.one_electron_derivative_schedule",
        "version": 2,
        "schedule": "nucleus_cooperative",
        "schedule_code": NUCLEUS_COOPERATIVE_SCHEDULE_CODE,
        "task_axis": "ao_pair",
        "cooperative_axis": "nuclear_center",
        "cooperative_schedule": schedule.to_payload(),
        "cooperative_schedule_identity": schedule.identity,
        "workload": asdict(workload),
        "workload_profile_key": canonical_hash(asdict(workload)),
        "schedule_contracts": contracts,
    }


def emit_one_electron_derivative_policy_cuda() -> str:
    """Emit only schedule constants; derivative mathematics stays elsewhere."""
    schedule = production_nucleus_cooperative_schedule()
    return f"""// Generated by tools/generate_one_electron_kernels.py; do not edit.
#ifndef VIBEQC_GENERATED_ONE_ELECTRON_DERIVATIVE_POLICY_CUH
#define VIBEQC_GENERATED_ONE_ELECTRON_DERIVATIVE_POLICY_CUH
namespace vibeqc::scf::generated_one_electron_derivative_policy {{
struct NucleusCooperativeSchedule {{
  static constexpr unsigned schedule_code={NUCLEUS_COOPERATIVE_SCHEDULE_CODE}U;
  static constexpr unsigned subgroup_lanes={schedule.subgroup_size}U;
  static constexpr unsigned group_lanes={schedule.lanes_per_group}U;
  static constexpr unsigned groups_per_block={schedule.groups_per_workgroup}U;
  static constexpr unsigned block_threads={schedule.workgroup_threads}U;
  static constexpr const char* identity="{schedule.identity}";
}};
}} // namespace vibeqc::scf::generated_one_electron_derivative_policy
#endif
"""
