"""Host lowering for the promoted S/T production profile.

The scientific DAG and shell/component lowering are the same helpers used by
the CUDA production generator.  This module changes only C-family qualifiers
and omits the still-unpromoted nuclear-attraction family.
"""

from itertools import product

from .ir_serialization import integral_to_payload
from .one_electron_cuda import (
    _emit_component_index,
    _emit_operator_helpers,
    _emit_pair_geometry,
)
from .one_electron_derivatives import build_one_electron_derivative_ir
from .one_electron_derivatives_cuda import (
    _emit_axis_permutations,
    _emit_gradient_helpers,
)
from .one_electron_values import build_one_electron_value_ir


def _hostify(source: str) -> str:
    source = (
        source.replace("__device__ __forceinline__", "inline")
        .replace("__device__ __noinline__", "inline")
        .replace("__device__", "inline")
    )
    if (
        "__device__" in source
        or "__forceinline__" in source
        or "__noinline__" in source
    ):
        raise ValueError("CUDA qualifier escaped host one-electron lowering")
    return source


def one_electron_st_cpu_inventory() -> dict[str, object]:
    """Describe the exact shared scientific surface promoted on CPU."""
    return {
        "schema": "vibeqc.one_electron_st_cpu",
        "version": 1,
        "precision": "fp64",
        "maximum_angular": 3,
        "families": ["overlap", "kinetic"],
        "values": [
            integral_to_payload(build_one_electron_value_ir(family, angular))
            for family in ("overlap", "kinetic")
            for angular in product(range(4), repeat=2)
        ],
        "derivatives": [
            integral_to_payload(build_one_electron_derivative_ir(family, angular))
            for family in ("overlap", "kinetic")
            for angular in product(range(4), repeat=2)
        ],
    }


def emit_one_electron_st_cpu() -> str:
    """Emit the s/p/d/f S/T value + first-derivative production helper."""
    body = "\n".join(
        (
            _emit_pair_geometry(),
            _emit_component_index(),
            _emit_operator_helpers(False),
            _emit_axis_permutations(),
            _emit_gradient_helpers(False),
        )
    )
    return "\n".join(
        (
            "// Generated by tools/generate_one_electron_kernels.py; do not edit.",
            "#ifndef VIBEQC_GENERATED_ONE_ELECTRON_ST_CPU_HPP",
            "#define VIBEQC_GENERATED_ONE_ELECTRON_ST_CPU_HPP",
            "#include <cmath>",
            "namespace vibeqc::integrals::generated_one_electron_cpu {",
            "struct ST { double overlap, kinetic; };",
            "struct GradientPair { double first[3], second[3]; };",
            "struct GradientAxis { double first, second; };",
            _hostify(body),
            "}  // namespace vibeqc::integrals::generated_one_electron_cpu",
            "#endif",
            "",
        )
    )
