"""Host lowering for the promoted S/T/V production profile.

The scientific DAG and shell/component lowering are shared with CUDA.  CPU
specialization changes only C-family qualifiers; the dynamic-Jet path remains
an independent oracle and the explicit g-shell fallback.
"""

from itertools import product

from .ir_serialization import integral_to_payload
from .one_electron_cuda import (
    _emit_boys_support,
    _emit_component_index,
    _emit_operator_helpers,
    _emit_pair_geometry,
)
from .one_electron_derivatives import build_one_electron_derivative_ir
from .one_electron_derivatives_cuda import (
    _emit_axis_permutations,
    _emit_gradient_helpers,
)
from .one_electron_values import build_one_electron_value_ir


def _hostify(source: str) -> str:
    source = (
        source.replace("__device__ __forceinline__", "inline")
        .replace("__device__ __noinline__", "inline")
        .replace("__device__", "inline")
    )
    if (
        "__device__" in source
        or "__forceinline__" in source
        or "__noinline__" in source
    ):
        raise ValueError("CUDA qualifier escaped host one-electron lowering")
    return source


def one_electron_cpu_inventory() -> dict[str, object]:
    """Describe the exact shared scientific surface promoted on CPU."""
    families = ("overlap", "kinetic", "nuclear_attraction")
    return {
        "schema": "vibeqc.one_electron_cpu",
        "version": 2,
        "precision": "fp64",
        "maximum_angular": 3,
        "families": list(families),
        "values": [
            integral_to_payload(build_one_electron_value_ir(family, angular))
            for family in families
            for angular in product(range(4), repeat=2)
        ],
        "derivatives": [
            integral_to_payload(build_one_electron_derivative_ir(family, angular))
            for family in families
            for angular in product(range(4), repeat=2)
        ],
    }


def one_electron_st_cpu_inventory() -> dict[str, object]:
    """Compatibility alias for the pre-V host inventory entry point."""
    return one_electron_cpu_inventory()


def emit_one_electron_cpu() -> str:
    """Emit the s/p/d/f S/T/V value + first-derivative production helper."""
    body = "\n".join(
        (
            _emit_boys_support(7),
            _emit_pair_geometry(),
            _emit_component_index(),
            _emit_operator_helpers(False),
            _emit_operator_helpers(True),
            _emit_axis_permutations(),
            _emit_gradient_helpers(False),
            _emit_gradient_helpers(True),
        )
    )
    return "\n".join(
        (
            "// Generated by tools/generate_one_electron_kernels.py; do not edit.",
            "#ifndef VIBEQC_GENERATED_ONE_ELECTRON_CPU_HPP",
            "#define VIBEQC_GENERATED_ONE_ELECTRON_CPU_HPP",
            "#include <cmath>",
            "namespace vibeqc::integrals::generated_one_electron_cpu {",
            "struct ST { double overlap, kinetic; };",
            "struct GradientPair { double first[3], second[3]; };",
            "struct GradientAxis { double first, second; };",
            _hostify(body),
            "}  // namespace vibeqc::integrals::generated_one_electron_cpu",
            "#endif",
            "",
        )
    )


def emit_one_electron_st_cpu() -> str:
    """Compatibility alias for the pre-V host emitter entry point."""
    return emit_one_electron_cpu()
