"""Compatibility facade for integral production compiler ownership.

Issue #487 split production responsibilities into stable leaf modules.  Keep this
module as a narrow import-compatible facade while in-tree callers migrate.
"""

from __future__ import annotations

from typing import TYPE_CHECKING as TYPE_CHECKING  # noqa: PLC0414

from . import production_bundle as _production_bundle
from . import production_cost as _production_cost
from . import production_emission as _production_emission
from . import production_profile as _production_profile
from . import production_registry as _production_registry
from . import production_selection as _production_selection

# Compatibility re-exports preserve canonical object identity for downstream
# callers that still import these names from ``integral.production``.
CAPABILITY_LOCAL_PACKED_STREAMING_FOCK = (
    _production_emission.CAPABILITY_LOCAL_PACKED_STREAMING_FOCK
)
CAPABILITY_MIXED_FOCK = _production_emission.CAPABILITY_MIXED_FOCK
CAPABILITY_STREAMING_FOCK = _production_emission.CAPABILITY_STREAMING_FOCK
FUSED_SHELL_SPEC_BY_NAME = _production_bundle.FUSED_SHELL_SPEC_BY_NAME
GeneratedKernelArgument = _production_emission.GeneratedKernelArgument
GeneratedKernelSignature = _production_emission.GeneratedKernelSignature
KernelConsumer = _production_emission.KernelConsumer
ScheduleIR = _production_emission.ScheduleIR
ScheduleKind = _production_emission.ScheduleKind
ShellClassSpec = _production_emission.ShellClassSpec
build_fused_shell_plan = _production_emission.build_fused_shell_plan
cuda_target_info = _production_emission.cuda_target_info
emit_ppps_resident_bra_rys3_cuda = _production_emission.emit_ppps_resident_bra_rys3_cuda
emit_shell_class_fused_cuda = _production_emission.emit_shell_class_fused_cuda
normalize_cuda_architecture = _production_bundle.normalize_cuda_architecture
re = _production_emission.re
shell_pair_class = _production_emission.shell_pair_class

_STABLE_AOT_SHARD_MAP_VERSION = _production_cost._STABLE_AOT_SHARD_MAP_VERSION
_partition_production_selections = _production_cost._partition_production_selections
production_compile_cost = _production_cost.production_compile_cost
shell_class_index = _production_cost.shell_class_index
stable_aot_shard_slot = _production_cost.stable_aot_shard_slot
_SUPPORTED_RECURRENCES = _production_selection._SUPPORTED_RECURRENCES
_schedule_from_payload = _production_profile._schedule_from_payload

ProfileMatch = _production_profile.ProfileMatch
ResolvedProductionProfile = _production_profile.ResolvedProductionProfile
load_production_fock_manifest = _production_profile.load_production_fock_manifest
load_production_kernel_selections = (
    _production_profile.load_production_kernel_selections
)
load_production_manifest = _production_profile.load_production_manifest
resolve_production_profile = _production_profile.resolve_production_profile
_profile_identifier = _production_profile._profile_identifier
_as_selection = _production_selection._as_selection
_selection_integral = _production_selection._selection_integral
_stable_selection_order = _production_registry._stable_selection_order
emit_registry_header = _production_registry.emit_registry_header
emit_registry_source = _production_registry.emit_registry_source
emit_multi_registry_header = _production_registry.emit_multi_registry_header
emit_multi_registry_source = _production_registry.emit_multi_registry_source

_launch_parameter_declaration = _production_registry._launch_parameter_declaration
_resident_launch_parameter_declaration = (
    _production_registry._resident_launch_parameter_declaration
)
_streaming_fock_launch_parameter_declaration = (
    _production_registry._streaming_fock_launch_parameter_declaration
)
_launch_argument_list = _production_registry._launch_argument_list
_resident_launch_argument_list = _production_registry._resident_launch_argument_list
_streaming_fock_launch_argument_list = (
    _production_registry._streaming_fock_launch_argument_list
)

KernelSelection = _production_selection.KernelSelection

_write_if_changed = _production_bundle._write_if_changed
write_production_bundle = _production_bundle.write_production_bundle
write_production_bundles = _production_bundle.write_production_bundles

_PRODUCTION_PRELUDE = _production_emission._PRODUCTION_PRELUDE
_emit_ppps_resident_source = _production_emission._emit_ppps_resident_source
_fock_launch_wrapper = _production_emission._fock_launch_wrapper
_launch_wrapper = _production_emission._launch_wrapper
_mixed_fock_launch_wrapper = _production_emission._mixed_fock_launch_wrapper
_ppps_resident_launch_wrapper = _production_emission._ppps_resident_launch_wrapper
_scope_profile_identifiers = _production_emission._scope_profile_identifiers
_streaming_fock_internal_signature = (
    _production_emission._streaming_fock_internal_signature
)
_streaming_fock_launch_wrapper = _production_emission._streaming_fock_launch_wrapper
_streaming_fock_schedule = _production_emission._streaming_fock_schedule
_streaming_fock_source = _production_emission._streaming_fock_source
_strip_emitter_includes = _production_emission._strip_emitter_includes
emit_production_shard = _production_emission.emit_production_shard
emit_profile_shard = _production_emission.emit_profile_shard
