"""Compiler-owned AO jets and density-invariant arithmetic for grid schedules.

The normalized native basis remains the only source of primitive and public AO
coefficients. The shared scalar DAG differentiates Gaussian polynomial factors
at build time; CUDA traversal, maps, buffers and matrix calls remain runtime.
"""

import typing

from vibeqc_compiler.common.paths import asset_path
from vibeqc_compiler.common.provenance import canonical_hash
from vibeqc_compiler.integral.cuda import CudaEmitter
from vibeqc_compiler.integral.expr import AlgebraForm, Graph

from .ao import jet_indices
from .feature_policy import emit_feature_policy


def axis_expression(power: typing.Any, derivative: typing.Any) -> typing.Any:
    """Return exp(+a*x*x) d^d[x^l exp(-a*x*x)] as a scalar polynomial.

    Keeping the exponential outside avoids division by an underflowed radial
    factor. Derivatives are ordinary spatial derivatives, without factorials.
    """
    if (
        type(power) is not int
        or type(derivative) is not int
        or not (0 <= power <= 3 and 0 <= derivative <= 3)
    ):
        raise ValueError("AO axis domain is l,d in [0,3]")
    graph = Graph()
    x, a = graph.variable("x"), graph.variable("a")
    root = graph.constant(1)
    for _ in range(power):
        root = root * x
    for _ in range(derivative):
        root = graph.differentiate(root, x) - 2 * a * x * root
    return graph, root


def emit_grid_policy() -> typing.Any:
    """Emit through-f/order-three AO factors and spin feature contractions.

    The same policy serves dense and selected-column execution. Adding an AO
    domain needs a compiler change rather than another native scientific body.
    """
    lines = [
        "// Generated by vibeqc_compiler.dft.ao_cuda; do not edit.",
        "#include <cmath>",
        "namespace vibeqc_grid_policy {",
        # This common order-three evaluator otherwise inlines three copies of
        # its branch temporaries into AO traversal. A measured call boundary
        # lowers the sm_120 AO kernel from 122 to 50 registers without spills.
        "__device__ __noinline__ double axis_jet(int l, int d, double a, double x) {",
        "  switch (4*l+d) {",
    ]
    for power in range(4):
        for derivative in range(4):
            graph, root = axis_expression(power, derivative)
            graph, (root,) = graph.apply_algebra_form(
                (root,), AlgebraForm.FACTORED_NARY
            )
            emitter = CudaEmitter(graph, {})
            emitter.emit((root,))
            lines.append(f"  case {4 * power + derivative}: {{")
            lines.extend(emitter.lines)
            lines.extend((f"    return {emitter.reference(root)};", "  }"))
    lines.extend(("  }", "  return NAN;", "}"))
    domain = ",".join("{" + ",".join(map(str, d)) + "}" for d in jet_indices(3))
    lines.append(f"__constant__ int derivatives[20][3] = {{{domain}}};")
    lines.extend((emit_feature_policy(device=True).rstrip("\n"), "}", ""))
    return "\n".join(lines)


def emit_grid_source(*, native_ks: typing.Any = False) -> typing.Any:
    """Compose one AO policy with the grid runtime and optional resident KS glue.

    The native library additionally instantiates its borrowed-buffer XC kernels.
    JIT grid owners retain their own ABI and arena without that native extension.
    """
    policy = emit_grid_policy()
    source = policy + '#include "cuda_grid.cu"\n'
    if native_ks:
        source += '#include "cuda_xc_kernels.cuh"\n'
    return (
        source,
        canonical_hash({"schema": "vibeqc.grid-policy.v1", "source": source}),
        (
            asset_path("src/dft/cuda_grid.cu"),
            asset_path("src/tensor/cuda_runtime.cuh"),
            asset_path("src/runtime/bounded_workspace.hpp"),
            asset_path("src/runtime/cuda_resources.cuh"),
            asset_path("src/runtime/resource_cuda.cuh"),
            asset_path("src/runtime/resource_ledger.hpp"),
            asset_path("src/dft/grid_task_view.cuh"),
            asset_path("src/dft/xc_point.hpp"),
            asset_path("src/tensor/cuda_error.hpp"),
            asset_path("include/vibeqc/vibeqc.h"),
        ),
    )
