"""Generate shared CPU/CUDA GFN2 ES2 scalar kernels from TensorIR + AD."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

# Build-time code generation must stay independent of NumPy/site packages.
import vibeqc_compiler

for package_name in ("tensor", "method"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python" / "vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)

from vibeqc_compiler.method.gfn2_es2_runtime import (
    GFN2_ES2_RUNTIME_VERSION,
    build_gfn2_es2_arithmetic_hardness_program,
    build_gfn2_es2_cached_gradient_weight_program,
    build_gfn2_es2_energy_update_program,
    build_gfn2_es2_gradient_projection_program,
    build_gfn2_es2_pair_primal,
    build_gfn2_es2_pair_vjp,
    build_gfn2_es2_potential_update_program,
)
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp


def _host_device(source: str) -> str:
    return source.replace("inline bool ", "VIBEQC_GFN2_ES2_HD inline bool ").replace(
        "std::isfinite", "gfn2_es2_isfinite"
    )


def native_header() -> str:
    hardness = build_gfn2_es2_arithmetic_hardness_program()
    primal = build_gfn2_es2_pair_primal()
    vjp = build_gfn2_es2_pair_vjp()
    potential = build_gfn2_es2_potential_update_program()
    energy = build_gfn2_es2_energy_update_program()
    weight = build_gfn2_es2_cached_gradient_weight_program()
    projection = build_gfn2_es2_gradient_projection_program()

    potential_body = _host_device(
        emit_scalar_cpp(
            potential,
            function_name="gfn2_es2_potential_update_tensor",
            input_order=("kernel", "charge", "accumulator"),
            output_order=("updated",),
        )
    )
    energy_body = _host_device(
        emit_scalar_cpp(
            energy,
            function_name="gfn2_es2_energy_update_tensor",
            input_order=("row_charge", "potential", "accumulator"),
            output_order=("updated",),
        )
    )
    weight_body = _host_device(
        emit_scalar_cpp(
            weight,
            function_name="gfn2_es2_cached_gradient_weight_tensor",
            input_order=("kernel", "first_charge", "second_charge"),
            output_order=("weight",),
        )
    )
    projection_body = _host_device(
        emit_scalar_cpp(
            projection,
            function_name="gfn2_es2_gradient_projection_tensor",
            input_order=("weight", "dx", "dy", "dz"),
            output_order=("gx", "gy", "gz"),
        )
    )

    return f"""// Generated by tools/generate_gfn2_es2_native.py from TensorIR + AD; do not edit.
#pragma once

#include <cmath>

#if defined(__CUDACC__)
#define VIBEQC_GFN2_ES2_HD __host__ __device__
#else
#define VIBEQC_GFN2_ES2_HD
#endif

namespace vibeqc::xtb::generated {{

inline constexpr const char* gfn2_es2_runtime_version = "{GFN2_ES2_RUNTIME_VERSION}";
inline constexpr const char* gfn2_es2_arithmetic_hardness_logical_hash = "{hardness.logical_hash}";
inline constexpr const char* gfn2_es2_pair_primal_logical_hash = "{primal.logical_hash}";
inline constexpr const char* gfn2_es2_pair_vjp_hash = "{vjp.derivative_hash}";
inline constexpr const char* gfn2_es2_potential_update_logical_hash = "{potential.logical_hash}";
inline constexpr const char* gfn2_es2_energy_update_logical_hash = "{energy.logical_hash}";
inline constexpr const char* gfn2_es2_cached_gradient_weight_logical_hash = "{weight.logical_hash}";
inline constexpr const char* gfn2_es2_gradient_projection_logical_hash = "{projection.logical_hash}";

VIBEQC_GFN2_ES2_HD inline bool gfn2_es2_isfinite(double value) noexcept {{
#if defined(__CUDA_ARCH__)
  return isfinite(value);
#else
  return std::isfinite(value);
#endif
}}

VIBEQC_GFN2_ES2_HD inline double gfn2_es2_hypot(double first, double second) noexcept {{
#if defined(__CUDA_ARCH__)
  return hypot(first, second);
#else
  return std::hypot(first, second);
#endif
}}

/* Numerically stable lowering of the compiler-owned arithmetic hardness mean.
 * Add-before-half preserves positive subnormals; half-before-add is used only
 * when the finite positive sum itself overflows. */
VIBEQC_GFN2_ES2_HD inline bool evaluate_gfn2_es2_arithmetic_hardness(
    double first, double second, double& average) noexcept {{
  if (!gfn2_es2_isfinite(first) || !gfn2_es2_isfinite(second)) return false;
  const double sum = first + second;
  average = gfn2_es2_isfinite(sum) ? 0.5 * sum : 0.5 * first + 0.5 * second;
  const double inverse = 1.0 / average;
  return average > 0.0 && gfn2_es2_isfinite(average) && gfn2_es2_isfinite(inverse);
}}

/* Stable native lowering of 1/sqrt(dx^2+dy^2+dz^2+hardness^-2).
 * The TensorIR primal owns the equation/hash; nested hypot preserves the
 * production overflow/underflow envelope. */
VIBEQC_GFN2_ES2_HD inline bool evaluate_gfn2_es2_kernel_from_hardness(
    double dx, double dy, double dz, double pair_hardness, double& kernel) noexcept {{
  if (!gfn2_es2_isfinite(dx) || !gfn2_es2_isfinite(dy) || !gfn2_es2_isfinite(dz) ||
      !(pair_hardness > 0.0) || !gfn2_es2_isfinite(pair_hardness)) return false;
  const double inverse = 1.0 / pair_hardness;
  if (!gfn2_es2_isfinite(inverse)) return false;
  const double softened =
      gfn2_es2_hypot(gfn2_es2_hypot(dx, dy), gfn2_es2_hypot(dz, inverse));
  kernel = 1.0 / softened;
  return softened > 0.0 && gfn2_es2_isfinite(softened) && kernel > 0.0 &&
         gfn2_es2_isfinite(kernel);
}}

{potential_body}
{energy_body}
{weight_body}
{projection_body}

VIBEQC_GFN2_ES2_HD inline bool accumulate_gfn2_es2_potential(
    double kernel, double charge, double& accumulator) noexcept {{
  double updated = 0.0;
  if (!gfn2_es2_potential_update_tensor(kernel, charge, accumulator, updated)) return false;
  accumulator = updated;
  return true;
}}

VIBEQC_GFN2_ES2_HD inline bool accumulate_gfn2_es2_energy(
    double row_charge, double potential_value, double& accumulator) noexcept {{
  double updated = 0.0;
  if (!gfn2_es2_energy_update_tensor(row_charge, potential_value, accumulator, updated)) return false;
  accumulator = updated;
  return true;
}}

VIBEQC_GFN2_ES2_HD inline bool evaluate_gfn2_es2_cached_gradient_weight(
    double kernel, double first_charge, double second_charge, double& result) noexcept {{
  return gfn2_es2_cached_gradient_weight_tensor(kernel, first_charge, second_charge, result);
}}

VIBEQC_GFN2_ES2_HD inline bool project_gfn2_es2_gradient(
    double weight_value, double dx, double dy, double dz,
    double& gx, double& gy, double& gz) noexcept {{
  return gfn2_es2_gradient_projection_tensor(weight_value, dx, dy, dz, gx, gy, gz);
}}

}}  // namespace vibeqc::xtb::generated

#undef VIBEQC_GFN2_ES2_HD
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
