"""Emit shared host/device spin arithmetic from compiler-owned TensorIR."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

import vibeqc_compiler

# Generation from an uninstalled checkout needs only the standard library.
for package_name in ("tensor", "method"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python/vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)

from vibeqc_compiler.method.gfn2_spin_runtime import (
    GFN2_SPIN_RUNTIME_VERSION,
    build_gfn2_spin_atom_vjp,
    build_gfn2_spin_energy_update,
    build_gfn2_spin_potential_update,
)
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp


def native_header() -> str:
    """Preserve the original ordered FMA sequence on both native backends."""
    definitions = []
    identities = []
    for name, program, inputs in (
        (
            "potential",
            build_gfn2_spin_potential_update(),
            ("coupling", "magnetization", "accumulated"),
        ),
        (
            "energy",
            build_gfn2_spin_energy_update(),
            ("magnetization", "potential", "accumulated"),
        ),
    ):
        function = f"accumulate_gfn2_spin_{name}"
        body = emit_scalar_cpp(
            program,
            function_name=function,
            input_order=inputs,
            output_order=("updated",),
            fused_accumulation=True,
        )
        definitions.append(
            body.replace(
                f"inline bool {function}", f"VIBEQC_GFN2_SPIN_HD inline bool {function}"
            )
        )
        identities.append(
            f'inline constexpr const char* gfn2_spin_{name}_hash = "{program.logical_hash}";'
        )
    for shells in (1, 2, 3):
        identities.append(
            f'inline constexpr const char* gfn2_spin_atom_{shells}_vjp_hash = "{build_gfn2_spin_atom_vjp(shells).logical_hash}";'
        )
    return "\n".join(
        [
            "// Generated by tools/generate_gfn2_spin_native.py from TensorIR; do not edit.",
            "#pragma once",
            "#include <cmath>",
            "#if defined(__CUDACC__)",
            "#define VIBEQC_GFN2_SPIN_HD __host__ __device__",
            "#else",
            "#define VIBEQC_GFN2_SPIN_HD",
            "#endif",
            "namespace vibeqc::xtb::generated {",
            f'inline constexpr const char* gfn2_spin_runtime_version = "{GFN2_SPIN_RUNTIME_VERSION}";',
            *identities,
            *definitions,
            "}  // namespace vibeqc::xtb::generated",
            "#undef VIBEQC_GFN2_SPIN_HD",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
