"""Generate the native CPU standard RCCSD(T) triples evaluator from the audited inventory."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDITED_SOURCE = ROOT / "tools/vibeqc_cc/triples.py"


def _literal_inventory() -> dict[str, object]:
    tree = ast.parse(AUDITED_SOURCE.read_text(encoding="utf-8"))
    wanted = {
        "W_TERMS",
        "V_TERMS",
        "R3",
        "DEGENERACY_DESCRIPTION",
        "VP",
        "OP",
        "SLOW_TABLE",
        "_LABELS",
        "VERSION",
    }
    values: dict[str, object] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and target.id in wanted:
            values[target.id] = ast.literal_eval(node.value)
    missing = wanted - values.keys()
    if missing:
        raise RuntimeError(
            "audited triples source is missing literal inventory: "
            + ", ".join(sorted(missing))
        )
    return values


_VALUES = _literal_inventory()
W_TERMS = _VALUES["W_TERMS"]
V_TERMS = _VALUES["V_TERMS"]
R3 = _VALUES["R3"]
VP = _VALUES["VP"]
OP = _VALUES["OP"]
SLOW_TABLE = _VALUES["SLOW_TABLE"]
_LABELS = _VALUES["_LABELS"]
_inventory_payload = {
    "method": "RCCSD(T)",
    "slice": "A",
    "inventory_version": _VALUES["VERSION"],
    "upstream": "PySCF 2.14.0 ccsd_t_slow.py kernel + r3",
    "w_terms": sorted(W_TERMS),
    "v_terms": sorted(V_TERMS),
    "r3": sorted(R3),
    "degeneracy": _VALUES["DEGENERACY_DESCRIPTION"],
    "virtual_domain": "triangular a>=b>=c",
    "overall_factor": 2,
    "contraction_table": {key: SLOW_TABLE[key] for key in _LABELS},
}
INVENTORY_HASH = hashlib.sha256(
    json.dumps(
        _inventory_payload, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode()
).hexdigest()

EXPECTED_W = (
    (1, "if,fkj->ijk", ("vvov", "t2T")),
    (-1, "ijm,mk->ijk", ("vooo", "t2T")),
)
EXPECTED_V = (
    (1, "ij,k->ijk", ("vvoo", "t1T")),
    (1, "ij,k->ijk", ("t2T", "fvo")),
)
if W_TERMS != EXPECTED_W or V_TERMS != EXPECTED_V:
    raise RuntimeError(
        "native triples generator does not recognize the audited seed inventory"
    )


def _arrays() -> str:
    label_index = {label: i for i, label in enumerate(_LABELS)}
    virtual = ",\n".join(
        "    {" + ",".join(str(x) for x in VP[label]) + "}" for label in _LABELS
    )
    r3_coeff = ",".join(str(c) for c, _ in R3)
    r3_perm = ",\n".join(
        "    {" + ",".join(str(x) for x in perm) + "}" for _, perm in R3
    )
    rows = []
    for zlabel in _LABELS:
        entries = []
        for wlabel, occupied in SLOW_TABLE[zlabel]:
            perm = OP[occupied]
            entries.append(
                "{"
                + str(label_index[wlabel])
                + ",{"
                + ",".join(str(x) for x in perm)
                + "}}"
            )
        rows.append("    {" + ",".join(entries) + "}")
    contraction = ",\n".join(rows)
    return f"""
inline constexpr int kVirtualPermutations[6][3] = {{
{virtual}
}};
inline constexpr int kR3Coefficients[6] = {{{r3_coeff}}};
inline constexpr int kR3Permutations[6][3] = {{
{r3_perm}
}};
struct ContractionTerm {{ int w; int p[3]; }};
inline constexpr ContractionTerm kContraction[6][6] = {{
{contraction}
}};
"""


def header() -> str:
    return f"""// Generated by tools/generate_rccsdt_native.py from tools/vibeqc_cc/triples.py.
// Standard canonical closed-shell (T); do not edit by hand.
#pragma once
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <limits>
#include <stdexcept>
#include <vector>

namespace vibeqc::cc::triples::generated {{
inline constexpr const char* inventory_hash = "{INVENTORY_HASH}";
{_arrays()}
inline std::size_t checked_mul(std::size_t a, std::size_t b) {{
  if (a && b > std::numeric_limits<std::size_t>::max() / a)
    throw std::length_error("RCCSD(T) triples size overflow");
  return a * b;
}}
inline std::size_t index3(std::size_t i, std::size_t j, std::size_t k, std::size_t o) {{
  return (i * o + j) * o + k;
}}
inline std::size_t permuted_index(const int p[3], std::size_t i, std::size_t j,
                                  std::size_t k, std::size_t o) {{
  const std::size_t out[3] = {{i, j, k}};
  std::size_t src[3] = {{0, 0, 0}};
  for (int axis = 0; axis < 3; ++axis) src[p[axis]] = out[axis];
  return index3(src[0], src[1], src[2], o);
}}
inline double w_seed(std::size_t o, std::size_t v, const double* ovvv,
                     const double* ovoo, const double* t2, std::size_t a,
                     std::size_t b, std::size_t c, std::size_t i,
                     std::size_t j, std::size_t k) {{
  double value = 0.0;
  for (std::size_t f = 0; f < v; ++f)
    value += ovvv[((i * v + a) * v + f) * v + b] *
             t2[((k * o + j) * v + c) * v + f];
  for (std::size_t m = 0; m < o; ++m)
    value -= ovoo[((i * v + a) * o + j) * o + m] *
             t2[((m * o + k) * v + b) * v + c];
  return value;
}}
inline double v_seed(std::size_t o, std::size_t v, const double* ovov,
                     const double* fov, const double* t1, const double* t2,
                     std::size_t a, std::size_t b, std::size_t c,
                     std::size_t i, std::size_t j, std::size_t k) {{
  return ovov[((i * v + a) * o + j) * v + b] * t1[k * v + c] +
         t2[((i * o + j) * v + a) * v + b] * fov[k * v + c];
}}
struct Result {{
  double energy{{}};
  double minimum_absolute_denominator{{std::numeric_limits<double>::infinity()}};
  std::size_t virtual_triples{{}};
  std::size_t workspace_bytes{{}};
}};
inline Result evaluate(std::size_t o, std::size_t v, const double* ovvv,
                       const double* ovoo, const double* ovov, const double* fov,
                       const double* t1, const double* t2, const double* eps_o,
                       const double* eps_v, double denominator_threshold,
                       std::size_t max_bytes) {{
  if (!o || !v || !(denominator_threshold > 0.0) ||
      !std::isfinite(denominator_threshold))
    throw std::invalid_argument("invalid RCCSD(T) triples dimensions or denominator threshold");
  const auto o3 = checked_mul(checked_mul(o, o), o);
  const auto workspace_elements = checked_mul(13, o3);
  const auto workspace_bytes = checked_mul(workspace_elements, sizeof(double));
  if (workspace_bytes > max_bytes)
    throw std::length_error("RCCSD(T) triples workspace exceeds correlation memory budget");
  std::vector<double> storage(workspace_elements);
  double* w[6]{{}};
  double* z[6]{{}};
  for (int p = 0; p < 6; ++p) w[p] = storage.data() + p * o3;
  for (int p = 0; p < 6; ++p) z[p] = storage.data() + (6 + p) * o3;
  double* q = storage.data() + 12 * o3;
  Result result;
  result.workspace_bytes = workspace_bytes;
  for (std::size_t a = 0; a < v; ++a)
    for (std::size_t b = 0; b <= a; ++b)
      for (std::size_t c = 0; c <= b; ++c) {{
        const std::size_t triple[3] = {{a, b, c}};
        const double degeneracy = (a == c) ? 6.0 : ((a == b || b == c) ? 2.0 : 1.0);
        ++result.virtual_triples;
        for (int p = 0; p < 6; ++p) {{
          const auto pa = triple[kVirtualPermutations[p][0]];
          const auto pb = triple[kVirtualPermutations[p][1]];
          const auto pc = triple[kVirtualPermutations[p][2]];
          for (std::size_t i = 0; i < o; ++i)
            for (std::size_t j = 0; j < o; ++j)
              for (std::size_t k = 0; k < o; ++k) {{
                const auto x = index3(i, j, k, o);
                const double ws = w_seed(o, v, ovvv, ovoo, t2, pa, pb, pc, i, j, k);
                const double vs = v_seed(o, v, ovov, fov, t1, t2, pa, pb, pc, i, j, k);
                if (!std::isfinite(ws) || !std::isfinite(vs))
                  throw std::runtime_error("nonfinite RCCSD(T) triples seed");
                w[p][x] = ws;
                q[x] = ws + 0.5 * vs;
              }}
          for (std::size_t i = 0; i < o; ++i)
            for (std::size_t j = 0; j < o; ++j)
              for (std::size_t k = 0; k < o; ++k) {{
                double projected = 0.0;
                for (int r = 0; r < 6; ++r)
                  projected += kR3Coefficients[r] *
                               q[permuted_index(kR3Permutations[r], i, j, k, o)];
                const double denominator =
                    (eps_o[i] + eps_o[j] + eps_o[k] - eps_v[a] - eps_v[b] - eps_v[c]) *
                    degeneracy;
                result.minimum_absolute_denominator =
                    std::min(result.minimum_absolute_denominator, std::abs(denominator / degeneracy));
                if (!std::isfinite(denominator) || denominator >= 0.0 ||
                    std::abs(denominator / degeneracy) <= denominator_threshold)
                  throw std::invalid_argument("noncanonical or near-zero RCCSD(T) triples denominator");
                const double value = projected / denominator;
                if (!std::isfinite(value))
                  throw std::runtime_error("nonfinite RCCSD(T) triples amplitude");
                z[p][index3(i, j, k, o)] = value;
              }}
        }}
        for (int zp = 0; zp < 6; ++zp)
          for (int term = 0; term < 6; ++term) {{
            const auto& entry = kContraction[zp][term];
            for (std::size_t i = 0; i < o; ++i)
              for (std::size_t j = 0; j < o; ++j)
                for (std::size_t k = 0; k < o; ++k)
                  result.energy += w[entry.w][permuted_index(entry.p, i, j, k, o)] *
                                   z[zp][index3(i, j, k, o)];
          }}
      }}
  result.energy *= 2.0;
  if (!std::isfinite(result.energy))
    throw std::runtime_error("nonfinite RCCSD(T) triples energy");
  return result;
}}
}}  // namespace vibeqc::cc::triples::generated
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header(), encoding="utf-8")


if __name__ == "__main__":
    main()
