"""Generate independent high-precision RKS point-response fixtures.

This differentiates the original unscaled PW92/PBE energy oracle, not the
native scaled-coordinate implementation or its directional-jet operations.
Runtime tests read the committed table and do not depend on mpmath or PySCF.
Run from the repository root with ``PYTHONPATH=. python tools/generate_xc_rks_response_references.py``.
"""

from pathlib import Path

import mpmath as mp
import numpy as np

from tools.generate_xc_scf_references import energy


def exchange_energy(pbe: bool, rho: mp.mpf, gradient: list[mp.mpf]) -> mp.mpf:
    """Original equal-spin exchange, used only to measure XC cancellation."""
    spin_rho = rho / 2
    cx = mp.mpf(3) / 8 * (3 / mp.pi) ** (mp.mpf(1) / 3) * 4 ** (mp.mpf(2) / 3)
    enhancement = mp.mpf(1)
    if pbe:
        beta, kappa = mp.mpf("0.06672455060314922"), mp.mpf("0.804")
        s2 = sum((g / 2) ** 2 for g in gradient) / (
            4 * (6 * mp.pi**2) ** (mp.mpf(2) / 3) * spin_rho ** (mp.mpf(8) / 3)
        )
        enhancement += kappa * (1 - kappa / (kappa + beta * mp.pi**2 / 3 * s2))
    return -2 * cx * spin_rho ** (mp.mpf(4) / 3) * enhancement


def reference(pbe: bool, point: np.ndarray, direction: np.ndarray) -> np.ndarray:
    """Return mixed XC derivatives and independent |delta X|+|delta C| scales.

    PBE cancels the leading exchange/correlation gradient response. The scale
    permits an FP64 roundoff bound without a global absolute error floor that
    would conceal an inaccurate but tiny nonzero density-tail response.
    """
    x, d = [[mp.mpf(float(value)) for value in row] for row in (point, direction)]
    scale = x[0]
    result, magnitudes = [], []
    for index in range(4):

        def displaced(
            s: mp.mpf, t: mp.mpf, exchange_only: bool = False, index: int = index
        ) -> mp.mpf:
            values = [value + t * delta for value, delta in zip(x, d, strict=True)]
            values[index] += s * scale
            rho, *gradient = values
            if exchange_only:
                return exchange_energy(pbe, rho, gradient) / scale
            return (
                energy(
                    pbe,
                    [
                        rho / 2,
                        rho / 2,
                        *(v / 2 for v in gradient),
                        *(v / 2 for v in gradient),
                    ],
                )
                / scale
            )

        total = mp.diff(displaced, (0, 0), (1, 1), addprec=200)
        exchange = mp.diff(
            lambda s, t: displaced(s, t, exchange_only=True),
            (0, 0),
            (1, 1),
            addprec=200,
        )
        result.append(float(total))
        magnitudes.append(float(abs(exchange) + abs(total - exchange)))
    return np.array(result + magnitudes)


def main() -> None:
    """Keep branch, tail and zero-gradient cases deterministic and auditable."""
    mp.mp.dps = 450
    cases = []
    for density in (0.9, 1e-20, 1e-80, 1e-180, 1e-280, 1e10):
        for reduced in ((0.03, -0.02, 0.01), (7.0, -2.0, 1.0)):
            cases.append(np.r_[density, density * np.array(reduced)])
    cases.append(np.array([0.9, 0.0, 0.0, 0.0]))
    # The exchange implementation joins direct and reciprocal reduced gradients
    # at |g_s|=rho_s^(4/3). Both sides must differentiate the same expression.
    for factor in (1 - 1e-5, 1 + 1e-5):
        density = 0.9
        gradient = factor * 2 * (density / 2) ** (4 / 3) * np.array([0.6, 0.8, 0])
        cases.append(np.r_[density, gradient])
    rows = []
    for pbe in (False, True):
        for point in cases:
            direction = point[0] * np.array([0.17, 0.07, 0.02, -0.03])
            rows.append(
                np.r_[int(pbe), point, direction, reference(pbe, point, direction)]
            )
    output = Path(__file__).resolve().parents[1] / "tests/data/xc/rks_response.tsv"
    np.savetxt(
        output,
        rows,
        fmt="%.17e",
        header=(
            "pbe rho grad[3] delta_rho delta_grad[3] delta_vrho delta_vgrad[3] "
            "abs_delta_exchange_plus_abs_delta_correlation[4]\n"
            "Original unscaled PW92/PBE, mpmath 450 dps mixed derivatives; "
            "generated by tools/generate_xc_rks_response_references.py"
        ),
    )
    print(f"Wrote {len(rows)} independent point directions to {output}")


if __name__ == "__main__":
    main()
