"""Generate backend-neutral DFT MethodSpec metadata from pinned Libxc owners."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "python"))

from tools import source_registry
from tools.libxc_method_metadata import (
    METHOD_METADATA_SEMANTICS,
    extract_method_registrations,
)

REVISION = "7.0.0"
SOURCE_ROOT = ROOT / "upstream" / "libxc" / REVISION
REGISTRY = ROOT / "upstream" / "manifest.json"
SOURCE_ID = "libxc-7.0.0"
COLLECTIONS = ("rsh", "wb97mv")
OUTPUT = ROOT / "python" / "vibeqc_compiler" / "method" / "_generated_libxc_methods.py"


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _sources() -> list[tuple[Path, str]]:
    """Return unique pinned hybrid C owners from the canonical source registry."""
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    source = registry["sources"][SOURCE_ID]
    if source.get("revision") != REVISION:
        raise ValueError("unexpected Libxc source-registry revision")
    names = {
        name
        for collection in COLLECTIONS
        for name in source["collections"][collection]
        if name.startswith("hyb_") and name.endswith(".c")
    }
    result: list[tuple[Path, str]] = []
    for name in sorted(names):
        expected = source["files"][name]["sha256"]
        path = SOURCE_ROOT / name
        if not path.is_file():
            raise ValueError(f"missing pinned Libxc hybrid owner: {name}")
        actual = _digest(path)
        if actual != expected:
            raise ValueError(f"pinned Libxc hybrid owner SHA-256 mismatch: {name}")
        result.append((path, actual))
    if not result:
        raise ValueError("no pinned Libxc hybrid owners")
    return result


def build_catalog() -> tuple[dict[str, dict[str, Any]], dict[str, str]]:
    generated: dict[str, dict[str, Any]] = {}
    blocked: dict[str, str] = {}
    registrations: set[str] = set()
    for path, sha in _sources():
        for record in extract_method_registrations(
            path.read_text(encoding="utf-8"), path.name
        ):
            registration = record["registration"]
            if registration in registrations:
                raise ValueError(f"duplicate Libxc hybrid registration: {registration}")
            registrations.add(registration)
            if record["status"] != "generated":
                blocked[registration] = record["reason"]
                continue
            identifier = record["identifier"]
            if identifier in generated:
                raise ValueError(f"duplicate generated method identifier: {identifier}")
            payload = {
                key: value
                for key, value in record.items()
                if key not in ("status", "reason", "identifier")
            }
            payload["source_sha256"] = sha
            payload["components"] = tuple(
                (name, coefficient) for name, coefficient in payload["components"]
            )
            generated[identifier] = payload
    if not generated:
        raise ValueError("no generated Libxc hybrid method metadata")
    return generated, blocked


def render(generated: dict[str, dict[str, Any]], blocked: dict[str, str]) -> str:
    raw_generated = json.dumps(generated, indent=2, sort_keys=True)
    raw_blocked = json.dumps(blocked, indent=2, sort_keys=True)
    return f'''# Generated by tools/generate_libxc_methods.py; do not edit.\nimport json\nfrom types import MappingProxyType\nfrom typing import cast\n\nMETHOD_METADATA_SEMANTICS = {json.dumps(METHOD_METADATA_SEMANTICS)}\n\n_RAW_LIBXC_METHODS: dict[str, dict[str, object]] = json.loads(\n    r"""{raw_generated}"""\n)\nLIBXC_METHODS = MappingProxyType(\n    {{\n        name: MappingProxyType(\n            {{\n                **record,\n                "components": tuple(\n                    tuple(item)\n                    for item in cast("list[list[str]]", record["components"])\n                ),\n            }}\n        )\n        for name, record in _RAW_LIBXC_METHODS.items()\n    }}\n)\n\n_RAW_BLOCKED_LIBXC_METHODS: dict[str, str] = json.loads(\n    r"""{raw_blocked}"""\n)\nBLOCKED_LIBXC_METHODS = MappingProxyType(_RAW_BLOCKED_LIBXC_METHODS)\n'''


def register_product() -> None:
    """Register the deterministic method-metadata product with source provenance."""
    registry = source_registry._load()
    registry["products"]["libxc-method-metadata"] = {
        "inputs": [SOURCE_ID],
        "input_identity_sha256": source_registry._product_input_identity(
            registry["sources"], [SOURCE_ID]
        ),
        "generator": Path(__file__).relative_to(ROOT).as_posix(),
        "generator_sha256": _digest(Path(__file__)),
        "canonical_inputs": {
            name: _digest(ROOT / name)
            for name in (
                "tools/libxc_bulk_metadata.py",
                "tools/libxc_method_metadata.py",
            )
        },
        "outputs": {
            OUTPUT.relative_to(ROOT).as_posix(): _digest(OUTPUT),
        },
    }
    REGISTRY.write_text(
        json.dumps(registry, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated, blocked = build_catalog()
    content = render(generated, blocked)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit(
                f"stale generated Libxc method metadata: {OUTPUT.relative_to(ROOT)}"
            )
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        register_product()
    print(
        json.dumps(
            {
                "generated": len(generated),
                "blocked": len(blocked),
                "pinned_sources": len(_sources()),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
