"""Generate native CPU GFN2 electronic scalar kernels from #505 TensorIR."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

# Build-time generation must not acquire the NumPy interpreter dependency.
import vibeqc_compiler

for package_name in ("tensor", "method"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python" / "vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)
from vibeqc_compiler.method.gfn2_electronic_runtime import (
    GFN2_ELECTRONIC_RUNTIME_VERSION,
    build_gfn2_core_energy_update_program,
    build_gfn2_multipole_hamiltonian_update_program,
    build_gfn2_multipole_integral_vjp_program,
    build_gfn2_population_update_program,
    build_gfn2_scalar_hamiltonian_update_program,
    build_gfn2_scalar_integral_vjp_program,
)
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp

POPULATION_INPUTS = ("density", "integral", "accumulator")
CORE_ENERGY_INPUTS = ("density", "h0", "accumulator")
SCALAR_HAMILTONIAN_INPUTS = (
    "overlap",
    "row_vat",
    "row_vsh",
    "column_vat",
    "column_vsh",
    "accumulator",
)
MULTIPOLE_HAMILTONIAN_INPUTS = (
    "forward_integral",
    "reverse_integral",
    "row_potential",
    "column_potential",
    "accumulator",
)
SCALAR_VJP_INPUTS = ("row_vat", "row_vsh", "column_vat", "column_vsh", "bar_updated")
MULTIPOLE_VJP_INPUTS = ("row_potential", "column_potential", "bar_updated")


def native_header() -> str:
    population = build_gfn2_population_update_program()
    core_energy = build_gfn2_core_energy_update_program()
    scalar_h = build_gfn2_scalar_hamiltonian_update_program()
    multipole_h = build_gfn2_multipole_hamiltonian_update_program()
    scalar_vjp = build_gfn2_scalar_integral_vjp_program()
    multipole_vjp = build_gfn2_multipole_integral_vjp_program()

    bodies = (
        emit_scalar_cpp(
            population,
            fused_accumulation=True,
            function_name="gfn2_population_update_tensor",
            input_order=POPULATION_INPUTS,
            output_order=("updated",),
        ),
        emit_scalar_cpp(
            core_energy,
            fused_accumulation=True,
            function_name="gfn2_core_energy_update_tensor",
            input_order=CORE_ENERGY_INPUTS,
            output_order=("updated",),
        ),
        emit_scalar_cpp(
            scalar_h,
            fused_accumulation=True,
            function_name="gfn2_scalar_hamiltonian_update_tensor",
            input_order=SCALAR_HAMILTONIAN_INPUTS,
            output_order=("updated",),
        ),
        emit_scalar_cpp(
            multipole_h,
            fused_accumulation=True,
            function_name="gfn2_multipole_hamiltonian_update_tensor",
            input_order=MULTIPOLE_HAMILTONIAN_INPUTS,
            output_order=("updated",),
        ),
        emit_scalar_cpp(
            scalar_vjp.program,
            fused_accumulation=True,
            function_name="gfn2_scalar_integral_vjp_tensor",
            input_order=SCALAR_VJP_INPUTS,
            output_order=("bar_overlap",),
        ),
        emit_scalar_cpp(
            multipole_vjp.program,
            fused_accumulation=True,
            function_name="gfn2_multipole_integral_vjp_tensor",
            input_order=MULTIPOLE_VJP_INPUTS,
            output_order=("bar_forward_integral", "bar_reverse_integral"),
        ),
    )
    return f"""// Generated by tools/generate_gfn2_electronic_native.py from #505 TensorIR; do not edit.
#pragma once

#include <cmath>

namespace vibeqc::xtb::generated {{

inline constexpr const char* gfn2_electronic_runtime_version =
    "{GFN2_ELECTRONIC_RUNTIME_VERSION}";
inline constexpr const char* gfn2_population_update_logical_hash =
    "{population.logical_hash}";
inline constexpr const char* gfn2_core_energy_update_logical_hash =
    "{core_energy.logical_hash}";
inline constexpr const char* gfn2_scalar_hamiltonian_update_logical_hash =
    "{scalar_h.logical_hash}";
inline constexpr const char* gfn2_multipole_hamiltonian_update_logical_hash =
    "{multipole_h.logical_hash}";
inline constexpr const char* gfn2_scalar_integral_vjp_hash =
    "{scalar_vjp.derivative_hash}";
inline constexpr const char* gfn2_multipole_integral_vjp_hash =
    "{multipole_vjp.derivative_hash}";

{"".join(bodies)}
}}  // namespace vibeqc::xtb::generated
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
