"""Generate native CUDA standard RCCSD(T) triples execution from the audited inventory.

The scientific permutation/contraction tables are imported from
generate_rccsdt_native.py so CPU and CUDA owners share one audited source.
This first native CUDA lowering is correctness- and memory-bounded. It
recomputes small W/Q intermediates instead of materializing full T3; #783 owns
the later persistent/cooperative performance lowering.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from generate_rccsdt_native import _LABELS, INVENTORY_HASH, OP, R3, SLOW_TABLE, VP


def _device_arrays() -> str:
    label_index = {label: i for i, label in enumerate(_LABELS)}
    virtual = ",\n".join(
        "    {" + ",".join(str(x) for x in VP[label]) + "}" for label in _LABELS
    )
    r3_coeff = ",".join(str(c) for c, _ in R3)
    r3_perm = ",\n".join(
        "    {" + ",".join(str(x) for x in perm) + "}" for _, perm in R3
    )
    rows = []
    for zlabel in _LABELS:
        entries = []
        for wlabel, occupied in SLOW_TABLE[zlabel]:
            perm = OP[occupied]
            entries.append(
                "{"
                + str(label_index[wlabel])
                + ",{"
                + ",".join(str(x) for x in perm)
                + "}}"
            )
        rows.append("    {" + ",".join(entries) + "}")
    contraction = ",\n".join(rows)
    return f"""
__device__ __constant__ int kVirtualPermutations[6][3] = {{
{virtual}
}};
__device__ __constant__ int kR3Coefficients[6] = {{{r3_coeff}}};
__device__ __constant__ int kR3Permutations[6][3] = {{
{r3_perm}
}};
struct ContractionTerm {{ int w; int p[3]; }};
__device__ __constant__ ContractionTerm kContraction[6][6] = {{
{contraction}
}};
"""


def source() -> str:
    return f"""// Generated by tools/generate_rccsdt_cuda.py from the audited RCCSD(T) inventory.
// Inventory SHA-256: {INVENTORY_HASH}
// Do not edit by hand.
#include "cc/triples_cuda.hpp"

#include <cuda_runtime.h>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>

namespace vibeqc::cc::triples {{
namespace {{
{_device_arrays()}
void cuda_check(cudaError_t error, const char* what) {{
  if (error != cudaSuccess)
    throw std::runtime_error(std::string(what) + ": " + cudaGetErrorString(error));
}}

std::size_t checked_add(std::size_t a, std::size_t b) {{
  if (b > std::numeric_limits<std::size_t>::max() - a)
    throw std::length_error("RCCSD(T) CUDA size overflow");
  return a + b;
}}

std::size_t checked_mul(std::size_t a, std::size_t b) {{
  if (a && b > std::numeric_limits<std::size_t>::max() / a)
    throw std::length_error("RCCSD(T) CUDA size overflow");
  return a * b;
}}

std::size_t align256(std::size_t value) {{
  const auto rem = value % 256;
  return rem ? checked_add(value, 256 - rem) : value;
}}

std::size_t reserve(std::size_t& cursor, std::size_t bytes) {{
  cursor = align256(cursor);
  const auto offset = cursor;
  cursor = checked_add(cursor, bytes);
  return offset;
}}

struct DeviceScope {{
  int previous{{-1}};
  explicit DeviceScope(int device) {{
    cuda_check(cudaGetDevice(&previous), "cudaGetDevice");
    cuda_check(cudaSetDevice(device), "cudaSetDevice");
  }}
  ~DeviceScope() {{
    if (previous >= 0) (void)cudaSetDevice(previous);
  }}
}};

__device__ inline void fail_once(int* error, int code) {{
  atomicCAS(error, 0, code);
}}

__device__ inline void permuted_occupied(const int p[3], std::size_t i,
                                         std::size_t j, std::size_t k,
                                         std::size_t& a, std::size_t& b,
                                         std::size_t& c) {{
  const std::size_t out[3] = {{i, j, k}};
  std::size_t src[3] = {{0, 0, 0}};
  for (int axis = 0; axis < 3; ++axis) src[p[axis]] = out[axis];
  a = src[0];
  b = src[1];
  c = src[2];
}}

__device__ inline bool decode_virtual_triple(std::size_t ordinal, std::size_t v,
                                             std::size_t& a, std::size_t& b,
                                             std::size_t& c) {{
  for (a = 0; a < v; ++a) {{
    const std::size_t width = (a + 1) * (a + 2) / 2;
    if (ordinal >= width) {{
      ordinal -= width;
      continue;
    }}
    for (b = 0; b <= a; ++b) {{
      if (ordinal <= b) {{
        c = ordinal;
        return true;
      }}
      ordinal -= b + 1;
    }}
    return false;
  }}
  return false;
}}

__device__ inline double w_seed(std::size_t o, std::size_t v, const double* ovvv,
                                const double* ovoo, const double* t2,
                                std::size_t a, std::size_t b, std::size_t c,
                                std::size_t i, std::size_t j, std::size_t k) {{
  double value = 0.0;
  for (std::size_t f = 0; f < v; ++f)
    value += ovvv[((i * v + a) * v + f) * v + b] *
             t2[((k * o + j) * v + c) * v + f];
  for (std::size_t m = 0; m < o; ++m)
    value -= ovoo[((i * v + a) * o + j) * o + m] *
             t2[((m * o + k) * v + b) * v + c];
  return value;
}}

__device__ inline double v_seed(std::size_t o, std::size_t v, const double* ovov,
                                const double* fov, const double* t1,
                                const double* t2, std::size_t a, std::size_t b,
                                std::size_t c, std::size_t i, std::size_t j,
                                std::size_t k) {{
  return ovov[((i * v + a) * o + j) * v + b] * t1[k * v + c] +
         t2[((i * o + j) * v + a) * v + b] * fov[k * v + c];
}}

__device__ inline void atomic_min_positive(double* address, double value) {{
  auto* bits = reinterpret_cast<unsigned long long*>(address);
  unsigned long long old = *bits;
  while (value < __longlong_as_double(static_cast<long long>(old))) {{
    const auto assumed = old;
    old = atomicCAS(bits, assumed,
                    static_cast<unsigned long long>(__double_as_longlong(value)));
    if (old == assumed) break;
  }}
}}

__global__ void triples_kernel(
    std::size_t o, std::size_t v, std::size_t o3, std::size_t work_items,
    const double* ovvv, const double* ovoo, const double* ovov, const double* fov,
    const double* t1, const double* t2, const double* eps_o, const double* eps_v,
    double denominator_threshold, double* energy, double* minimum, int* error) {{
  for (std::size_t work = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
       work < work_items; work += std::size_t(blockDim.x) * gridDim.x) {{
    const std::size_t virtual_ordinal = work / o3;
    std::size_t occupied = work - virtual_ordinal * o3;
    const std::size_t k = occupied % o;
    occupied /= o;
    const std::size_t j = occupied % o;
    const std::size_t i = occupied / o;

    std::size_t a = 0, b = 0, c = 0;
    if (!decode_virtual_triple(virtual_ordinal, v, a, b, c)) {{
      fail_once(error, 4);
      continue;
    }}

    const double physical_denominator =
        eps_o[i] + eps_o[j] + eps_o[k] - eps_v[a] - eps_v[b] - eps_v[c];
    const double absolute_denominator = fabs(physical_denominator);
    if (!isfinite(physical_denominator) || physical_denominator >= 0.0 ||
        absolute_denominator <= denominator_threshold) {{
      fail_once(error, 1);
      continue;
    }}
    atomic_min_positive(minimum, absolute_denominator);

    const std::size_t triple[3] = {{a, b, c}};
    const double degeneracy = (a == c) ? 6.0 : ((a == b || b == c) ? 2.0 : 1.0);
    const double denominator = physical_denominator * degeneracy;
    // A finite physical gap can overflow after its multiplicity is applied.
    // Fail closed instead of dividing by infinity and publishing zero energy.
    if (!isfinite(denominator)) {{
      fail_once(error, 3);
      continue;
    }}
    double contribution = 0.0;

    for (int zp = 0; zp < 6; ++zp) {{
      const auto pa = triple[kVirtualPermutations[zp][0]];
      const auto pb = triple[kVirtualPermutations[zp][1]];
      const auto pc = triple[kVirtualPermutations[zp][2]];
      double projected = 0.0;
      bool projected_valid = true;
      for (int r = 0; r < 6; ++r) {{
        std::size_t ri = 0, rj = 0, rk = 0;
        permuted_occupied(kR3Permutations[r], i, j, k, ri, rj, rk);
        const double ws = w_seed(o, v, ovvv, ovoo, t2, pa, pb, pc, ri, rj, rk);
        const double vs = v_seed(o, v, ovov, fov, t1, t2, pa, pb, pc, ri, rj, rk);
        if (!isfinite(ws) || !isfinite(vs)) {{
          fail_once(error, 2);
          projected_valid = false;
          break;
        }}
        projected += double(kR3Coefficients[r]) * (ws + 0.5 * vs);
      }}
      if (!projected_valid || !isfinite(projected)) {{
        fail_once(error, 2);
        continue;
      }}
      const double z = projected / denominator;
      if (!isfinite(z)) {{
        fail_once(error, 3);
        continue;
      }}

      for (int term = 0; term < 6; ++term) {{
        const auto entry = kContraction[zp][term];
        const auto wa = triple[kVirtualPermutations[entry.w][0]];
        const auto wb = triple[kVirtualPermutations[entry.w][1]];
        const auto wc = triple[kVirtualPermutations[entry.w][2]];
        std::size_t wi = 0, wj = 0, wk = 0;
        permuted_occupied(entry.p, i, j, k, wi, wj, wk);
        const double w = w_seed(o, v, ovvv, ovoo, t2, wa, wb, wc, wi, wj, wk);
        if (!isfinite(w)) {{
          fail_once(error, 2);
          continue;
        }}
        contribution += w * z;
      }}
    }}
    if (!isfinite(contribution)) {{
      fail_once(error, 3);
      continue;
    }}
    atomicAdd(energy, 2.0 * contribution);
  }}
}}

}}  // namespace

CudaResult evaluate_cuda(std::size_t o, std::size_t v, const double* ovvv,
                         const double* ovoo, const double* ovov, const double* fov,
                         const double* t1, const double* t2, const double* eps_o,
                         const double* eps_v, double denominator_threshold,
                         std::size_t max_bytes, int device) {{
  if (!o || !v || !(denominator_threshold > 0.0) ||
      !std::isfinite(denominator_threshold))
    throw std::invalid_argument(
        "invalid RCCSD(T) CUDA triples dimensions or denominator threshold");

  const auto ov = checked_mul(o, v);
  const auto oo = checked_mul(o, o);
  const auto vv = checked_mul(v, v);
  const auto o3 = checked_mul(oo, o);
  const auto virtual_triples =
      checked_mul(checked_mul(v, checked_add(v, 1)), checked_add(v, 2)) / 6;
  const auto work_items = checked_mul(virtual_triples, o3);

  const std::size_t sizes[8] = {{
      checked_mul(ov, vv), checked_mul(ov, oo), checked_mul(ov, ov), ov,
      ov, checked_mul(oo, vv), o, v,
  }};
  const double* host[8] = {{ovvv, ovoo, ovov, fov, t1, t2, eps_o, eps_v}};

  std::size_t cursor = 0;
  std::size_t offsets[8]{{}};
  for (int x = 0; x < 8; ++x)
    offsets[x] = reserve(cursor, checked_mul(sizes[x], sizeof(double)));
  const auto energy_offset = reserve(cursor, sizeof(double));
  const auto minimum_offset = reserve(cursor, sizeof(double));
  const auto error_offset = reserve(cursor, sizeof(int));
  const auto workspace_bytes = align256(cursor);
  if (workspace_bytes > max_bytes)
    throw std::length_error(
        "RCCSD(T) CUDA triples workspace exceeds correlation memory budget");

  DeviceScope scope(device);
  cudaStream_t stream = nullptr;
  unsigned char* base = nullptr;
  try {{
    cuda_check(cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking),
               "cudaStreamCreateWithFlags");
    cuda_check(cudaMalloc(reinterpret_cast<void**>(&base), workspace_bytes),
               "cudaMalloc RCCSD(T) triples");
    double* device_inputs[8]{{}};
    for (int x = 0; x < 8; ++x) {{
      device_inputs[x] = reinterpret_cast<double*>(base + offsets[x]);
      const auto bytes = checked_mul(sizes[x], sizeof(double));
      cuda_check(cudaMemcpyAsync(device_inputs[x], host[x], bytes,
                                 cudaMemcpyHostToDevice, stream),
                 "cudaMemcpyAsync RCCSD(T) input");
    }}

    auto* energy = reinterpret_cast<double*>(base + energy_offset);
    auto* minimum = reinterpret_cast<double*>(base + minimum_offset);
    auto* error = reinterpret_cast<int*>(base + error_offset);
    const double zero = 0.0;
    const double infinity = std::numeric_limits<double>::infinity();
    const int no_error = 0;
    cuda_check(cudaMemcpyAsync(energy, &zero, sizeof(double), cudaMemcpyHostToDevice, stream),
               "cudaMemcpyAsync RCCSD(T) energy init");
    cuda_check(cudaMemcpyAsync(minimum, &infinity, sizeof(double),
                               cudaMemcpyHostToDevice, stream),
               "cudaMemcpyAsync RCCSD(T) denominator init");
    cuda_check(cudaMemcpyAsync(error, &no_error, sizeof(int),
                               cudaMemcpyHostToDevice, stream),
               "cudaMemcpyAsync RCCSD(T) status init");

    const int threads = 128;
    const auto needed_blocks = (work_items + threads - 1) / threads;
    const int blocks = static_cast<int>(
        std::max<std::size_t>(1, std::min<std::size_t>(needed_blocks, 65535)));
    triples_kernel<<<blocks, threads, 0, stream>>>(
        o, v, o3, work_items, device_inputs[0], device_inputs[1], device_inputs[2],
        device_inputs[3], device_inputs[4], device_inputs[5], device_inputs[6],
        device_inputs[7], denominator_threshold, energy, minimum, error);
    cuda_check(cudaGetLastError(), "RCCSD(T) triples kernel launch");

    CudaResult result;
    int host_error = 0;
    cuda_check(cudaMemcpyAsync(&result.energy, energy, sizeof(double),
                               cudaMemcpyDeviceToHost, stream),
               "cudaMemcpyAsync RCCSD(T) energy result");
    cuda_check(cudaMemcpyAsync(&result.minimum_absolute_denominator, minimum,
                               sizeof(double), cudaMemcpyDeviceToHost, stream),
               "cudaMemcpyAsync RCCSD(T) denominator result");
    cuda_check(cudaMemcpyAsync(&host_error, error, sizeof(int),
                               cudaMemcpyDeviceToHost, stream),
               "cudaMemcpyAsync RCCSD(T) status result");
    cuda_check(cudaStreamSynchronize(stream), "cudaStreamSynchronize RCCSD(T)");

    result.virtual_triples = virtual_triples;
    result.workspace_bytes = workspace_bytes;
    if (host_error == 1)
      throw std::invalid_argument(
          "noncanonical or near-zero RCCSD(T) triples denominator");
    if (host_error)
      throw std::runtime_error(
          "nonfinite RCCSD(T) generated CUDA triples arithmetic");
    if (!std::isfinite(result.energy))
      throw std::runtime_error("nonfinite RCCSD(T) CUDA triples energy");

    const auto free_error = cudaFree(base);
    base = nullptr;
    const auto destroy_error = cudaStreamDestroy(stream);
    stream = nullptr;
    cuda_check(free_error, "cudaFree RCCSD(T) triples");
    cuda_check(destroy_error, "cudaStreamDestroy RCCSD(T) triples");
    return result;
  }} catch (...) {{
    if (stream) (void)cudaStreamSynchronize(stream);
    if (base) (void)cudaFree(base);
    if (stream) (void)cudaStreamDestroy(stream);
    throw;
  }}
}}

}}  // namespace vibeqc::cc::triples
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source(), encoding="utf-8")


if __name__ == "__main__":
    main()
