"""Generate native CPU GFN2 pair kernels from TensorIR + generated AD."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

# Keep build-time codegen independent of NumPy-backed interpreter packages.
import vibeqc_compiler

for package_name in ("tensor", "geometry"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python" / "vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)

from vibeqc_compiler.geometry.gfn2_pair import (
    GFN2_PAIR_RUNTIME_VERSION,
    build_gfn2_runtime_pair_kernel,
    build_gfn2_runtime_pair_primal,
)
from vibeqc_compiler.tensor.ad_program import linearize
from vibeqc_compiler.tensor.program import Program
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp

COORDINATION_INPUT_ORDER = ("distance", "radius", "d_distance")
COORDINATION_OUTPUT_ORDER = (
    "coordination",
    "coordination_distance_derivative",
)
REPULSION_INPUT_ORDER = (
    "distance",
    "pair_alpha",
    "pair_charge",
    "light_pair",
    "d_distance",
)
REPULSION_OUTPUT_ORDER = (
    "repulsion_energy",
    "repulsion_distance_derivative",
)


def _subprogram(kernel: Program, names: tuple[str, ...], kind: str) -> Program:
    return Program(
        {name: kernel.outputs[name] for name in names},
        kernel.nodes,
        provenance={"kind": kind, "parent_logical_hash": kernel.logical_hash},
    )


def native_header() -> str:
    primal = build_gfn2_runtime_pair_primal()
    jvp = linearize(
        primal,
        ("distance",),
        outputs=("coordination", "repulsion_energy"),
    )
    kernel = build_gfn2_runtime_pair_kernel()
    coordination = _subprogram(
        kernel, COORDINATION_OUTPUT_ORDER, "gfn2-runtime-coordination-pair"
    )
    repulsion = _subprogram(
        kernel, REPULSION_OUTPUT_ORDER, "gfn2-runtime-repulsion-pair"
    )
    # Production GFN2 validates finite parameters and 0 < r <= 25 bohr before
    # entering these helpers. In that bounded domain the AD quotient products
    # are many orders below FP64 overflow, so direct scaled-bilinear lowering
    # is admitted here; generic scalar lowering keeps the robust default.
    coordination_body = emit_scalar_cpp(
        coordination,
        function_name="gfn2_coordination_pair_tensor",
        input_order=COORDINATION_INPUT_ORDER,
        output_order=COORDINATION_OUTPUT_ORDER,
        direct_scaled_bilinear=True,
        check_intermediates=False,
    )
    repulsion_body = emit_scalar_cpp(
        repulsion,
        function_name="gfn2_repulsion_pair_tensor",
        input_order=REPULSION_INPUT_ORDER,
        output_order=REPULSION_OUTPUT_ORDER,
        direct_scaled_bilinear=True,
        check_intermediates=False,
    )
    return f"""// Generated by tools/generate_gfn2_pair_native.py from TensorIR; do not edit.
#pragma once

#include <algorithm>
#include <cmath>

namespace vibeqc::xtb::generated {{

inline constexpr const char* gfn2_pair_runtime_version =
    "{GFN2_PAIR_RUNTIME_VERSION}";
inline constexpr const char* gfn2_pair_primal_logical_hash =
    "{primal.logical_hash}";
inline constexpr const char* gfn2_pair_distance_jvp_hash =
    "{jvp.derivative_hash}";
inline constexpr const char* gfn2_pair_kernel_logical_hash =
    "{kernel.logical_hash}";
inline constexpr const char* gfn2_coordination_pair_logical_hash =
    "{coordination.logical_hash}";
inline constexpr const char* gfn2_repulsion_pair_logical_hash =
    "{repulsion.logical_hash}";

struct Gfn2CoordinationPairResult {{
  double value = 0.0;
  double distance_derivative = 0.0;
}};

struct Gfn2RepulsionPairResult {{
  double energy = 0.0;
  double distance_derivative = 0.0;
}};

{coordination_body}
{repulsion_body}
inline bool evaluate_gfn2_coordination_pair(
    double distance, double radius, Gfn2CoordinationPairResult& result) noexcept {{
  return gfn2_coordination_pair_tensor(
      distance, radius, 1.0, result.value, result.distance_derivative);
}}

inline bool evaluate_gfn2_repulsion_pair(
    double distance, double pair_alpha, double pair_charge, bool light_pair,
    Gfn2RepulsionPairResult& result) noexcept {{
  return gfn2_repulsion_pair_tensor(
      distance, pair_alpha, pair_charge, light_pair ? 1.0 : 0.0, 1.0,
      result.energy, result.distance_derivative);
}}

}}  // namespace vibeqc::xtb::generated
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
