"""Generate shared CPU/CUDA GFN2 ES3 scalar math from TensorIR."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "python"))

import vibeqc_compiler

for package_name in ("tensor", "method"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python" / "vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)

from vibeqc_compiler.method.gfn2_es3_runtime import (
    GFN2_ES3_RUNTIME_VERSION,
    build_gfn2_es3_kernel,
    build_gfn2_es3_primal,
)
from vibeqc_compiler.tensor.ad_program import linearize
from vibeqc_compiler.tensor.program import Program
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp

INPUT_ORDER = ("gamma3", "charge")


def _subprogram(parent: Program, output: str, kind: str) -> Program:
    return Program(
        {output: parent.outputs[output]},
        parent.nodes,
        provenance={"kind": kind, "parent_logical_hash": parent.logical_hash},
    )


def _host_device(source: str, function_name: str) -> str:
    source = source.replace(
        f"inline bool {function_name}(",
        f"VIBEQC_GFN2_ES3_HD inline bool {function_name}(",
        1,
    )
    return source.replace("std::isfinite(", "gfn2_es3_isfinite(")


def native_header() -> str:
    primal = build_gfn2_es3_primal()
    kernel = build_gfn2_es3_kernel()
    jvp = linearize(primal, ("charge",), outputs=("energy",))

    potential_program = _subprogram(primal, "potential", "gfn2-es3-runtime-potential")
    energy_program = _subprogram(primal, "energy", "gfn2-es3-runtime-energy")
    potential_body = _host_device(
        emit_scalar_cpp(
            potential_program,
            function_name="gfn2_es3_potential_tensor",
            input_order=INPUT_ORDER,
            output_order=("potential",),
        ),
        "gfn2_es3_potential_tensor",
    )
    energy_body = _host_device(
        emit_scalar_cpp(
            energy_program,
            function_name="gfn2_es3_energy_tensor",
            input_order=INPUT_ORDER,
            output_order=("energy",),
        ),
        "gfn2_es3_energy_tensor",
    )

    return f"""// Generated by tools/generate_gfn2_es3_native.py from TensorIR; do not edit.
#pragma once

#include <cmath>
#include <limits>

#if defined(__CUDACC__)
#define VIBEQC_GFN2_ES3_HD __host__ __device__
#else
#define VIBEQC_GFN2_ES3_HD
#endif

namespace vibeqc::xtb::generated {{

inline constexpr const char* gfn2_es3_runtime_version =
    "{GFN2_ES3_RUNTIME_VERSION}";
inline constexpr const char* gfn2_es3_primal_logical_hash =
    "{primal.logical_hash}";
inline constexpr const char* gfn2_es3_charge_jvp_hash =
    "{jvp.derivative_hash}";
inline constexpr const char* gfn2_es3_kernel_logical_hash =
    "{kernel.logical_hash}";

VIBEQC_GFN2_ES3_HD inline bool gfn2_es3_isfinite(double value) noexcept {{
#if defined(__CUDA_ARCH__)
  return isfinite(value);
#else
  return std::isfinite(value);
#endif
}}

VIBEQC_GFN2_ES3_HD inline bool gfn2_es3_isnormal(double value) noexcept {{
  constexpr double kMinNormalDouble = 0x1p-1022;
#if defined(__CUDA_ARCH__)
  return isfinite(value) && fabs(value) >= kMinNormalDouble;
#else
  return std::isfinite(value) && std::abs(value) >= kMinNormalDouble;
#endif
}}

{potential_body}
{energy_body}
VIBEQC_GFN2_ES3_HD inline bool evaluate_gfn2_es3_potential(
    double gamma3, double shell_charge, double* result) noexcept {{
  if (result == nullptr || !gfn2_es3_isfinite(gamma3) ||
      !gfn2_es3_isfinite(shell_charge)) {{
    return false;
  }}
  if (shell_charge == 0.0 || gamma3 == 0.0) {{
    *result = 0.0;
    return true;
  }}

  const double square = shell_charge * shell_charge;
  double direct = 0.0;
  if (gfn2_es3_potential_tensor(gamma3, shell_charge, direct) &&
      gfn2_es3_isnormal(square) && gfn2_es3_isnormal(gamma3) &&
      gfn2_es3_isnormal(direct)) {{
    *result = direct;
    return true;
  }}

#if defined(__CUDA_ARCH__)
  int charge_exponent = 0;
  int gamma_exponent = 0;
  const double charge_mantissa = frexp(shell_charge, &charge_exponent);
  const double gamma_mantissa = frexp(gamma3, &gamma_exponent);
  const double mantissa = charge_mantissa * charge_mantissa * gamma_mantissa;
  const double value = scalbn(mantissa, 2 * charge_exponent + gamma_exponent);
  if (!isfinite(value)) {{
    return false;
  }}
  *result = value;
#else
  const long double wide =
      static_cast<long double>(shell_charge) * static_cast<long double>(shell_charge) *
      static_cast<long double>(gamma3);
  if (!std::isfinite(wide) ||
      std::abs(wide) > static_cast<long double>(std::numeric_limits<double>::max())) {{
    return false;
  }}
  *result = static_cast<double>(wide);
#endif
  return gfn2_es3_isfinite(*result);
}}

VIBEQC_GFN2_ES3_HD inline bool evaluate_gfn2_es3_energy(
    double gamma3, double shell_charge, double* result) noexcept {{
  if (result == nullptr || !gfn2_es3_isfinite(gamma3) ||
      !gfn2_es3_isfinite(shell_charge)) {{
    return false;
  }}
  if (shell_charge == 0.0 || gamma3 == 0.0) {{
    *result = 0.0;
    return true;
  }}

  const double square = shell_charge * shell_charge;
  const double cube = square * shell_charge;
  const double scaled = cube * gamma3;
  double direct = 0.0;
  if (gfn2_es3_energy_tensor(gamma3, shell_charge, direct) &&
      gfn2_es3_isnormal(square) && gfn2_es3_isnormal(cube) &&
      gfn2_es3_isnormal(gamma3) && gfn2_es3_isnormal(scaled) &&
      gfn2_es3_isnormal(direct)) {{
    *result = direct;
    return true;
  }}

#if defined(__CUDA_ARCH__)
  int charge_exponent = 0;
  int gamma_exponent = 0;
  const double charge_mantissa = frexp(shell_charge, &charge_exponent);
  const double gamma_mantissa = frexp(gamma3, &gamma_exponent);
  const double mantissa =
      charge_mantissa * charge_mantissa * charge_mantissa * gamma_mantissa / 3.0;
  const double value = scalbn(mantissa, 3 * charge_exponent + gamma_exponent);
  if (!isfinite(value)) {{
    return false;
  }}
  *result = value;
#else
  const long double wide =
      static_cast<long double>(shell_charge) * static_cast<long double>(shell_charge) *
      static_cast<long double>(shell_charge) * static_cast<long double>(gamma3) / 3.0L;
  if (!std::isfinite(wide) ||
      std::abs(wide) > static_cast<long double>(std::numeric_limits<double>::max())) {{
    return false;
  }}
  *result = static_cast<double>(wide);
#endif
  return gfn2_es3_isfinite(*result);
}}

}}  // namespace vibeqc::xtb::generated

#undef VIBEQC_GFN2_ES3_HD
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
