"""Regenerate strict three/four-root coefficients for the common Rys evaluator.

The existing degree-13 tables have accurate nodes but weight interpolation
errors near 1e-12. This offline tool keeps their 2.5-wide intervals, series
layout, small/large branches and evaluator, replacing interpolation coefficients
with degree-17 values computed at 90 digits. It copies no external table data.
Source generation and runtime do not depend on mpmath.
"""

import argparse
import typing
from pathlib import Path

import mpmath as mp


def quadrature(argument: typing.Any, nroots: typing.Any) -> typing.Any:
    """Construct a Jacobi matrix by high-precision Stieltjes orthogonalization.

    Polynomials use ascending coefficients. The validation oracle instead
    Cholesky-factorizes a scaled Hankel matrix and independently checks every
    defining integral; it does not use this coefficient-generation routine.
    """
    half = mp.mpf("0.5")
    moments = [
        mp.gammainc(k + half, 0, argument) / (2 * argument ** (k + half))
        for k in range(2 * nroots)
    ]

    def inner(
        first: typing.Any, second: typing.Any, shift: typing.Any = 0
    ) -> typing.Any:
        return mp.fsum(
            a * b * moments[i + j + shift]
            for i, a in enumerate(first)
            for j, b in enumerate(second)
        )

    jacobi = mp.matrix(nroots)
    previous, polynomial, beta = [], [1 / mp.sqrt(moments[0])], mp.mpf(0)
    for order in range(nroots):
        alpha = inner(polynomial, polynomial, 1)
        jacobi[order, order] = alpha
        if order + 1 == nroots:
            break
        residual = [mp.mpf(0), *polynomial]
        for i, coefficient in enumerate(polynomial):
            residual[i] -= alpha * coefficient
        for i, coefficient in enumerate(previous):
            residual[i] -= beta * coefficient
        beta = mp.sqrt(inner(residual, residual))
        jacobi[order, order + 1] = jacobi[order + 1, order] = beta
        previous, polynomial = polynomial, [c / beta for c in residual]
    nodes, vectors = mp.eigsy(jacobi)
    # Preserve the common evaluator's decreasing node order in its table branch.
    return tuple(
        value
        for i in reversed(range(nroots))
        for value in (nodes[i], moments[0] * vectors[0, i] ** 2)
    )


def generate() -> typing.Any:
    """Return deterministic FP64 coefficients in series/degree/interval order."""
    degree = 17
    tables = {}
    with mp.workdps(90):
        count = degree + 1
        angles = [mp.pi * (j + mp.mpf("0.5")) / count for j in range(count)]
        cosines = [[mp.cos(k * angle) for angle in angles] for k in range(count)]
        for nroots in (3, 4):
            intervals = (35 + 5 * nroots) * 2 // 5 + 1
            coefficients = {}
            for interval in range(intervals):
                samples = [
                    quadrature(mp.mpf("2.5") * (interval + (1 + mp.cos(a)) / 2), nroots)
                    for a in angles
                ]
                for series in range(2 * nroots):
                    for k in range(count):
                        coefficients[series, k, interval] = float(
                            mp.fsum(
                                samples[j][series] * cosines[k][j] for j in range(count)
                            )
                            * (1 if k == 0 else 2)
                            / count
                        )
            tables[nroots] = (
                intervals,
                tuple(
                    coefficients[series, k, interval]
                    for series in range(2 * nroots)
                    for k in range(count)
                    for interval in range(intervals)
                ),
            )
    lines = [
        '"""High-accuracy coefficients for the existing fixed-root Rys evaluator.',
        "",
        "Generated by tools/generate_rys_high_accuracy_tables.py at 90 decimal digits.",
        "Degree 17, interval width 2.5; layout is series/degree/interval.",
        "Series alternate decreasing nodes and corresponding weights.",
        "Small/large argument constants remain owned by the common Rys tables.",
        '"""',
        "",
        f"HIGH_ACCURACY_DEGREE = {degree}",
    ]
    for nroots, (intervals, coefficients) in tables.items():
        lines += [
            "",
            f"RYS{nroots}_INTERVALS = {intervals}",
            f"RYS{nroots}_RW_DATA = (",
        ]
        lines += [f"    {c!r}," for c in coefficients]
        lines += [")"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("python/vibeqc_compiler/integral/rys_high_accuracy_data.py"),
    )
    args = parser.parse_args()
    args.output.write_text(generate())
