"""Generate bounded native MP2 tile programs from the shared TensorIR."""

import argparse
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "python"))

from tools.vibeqc_mp2.equations import cpu_capacity, energy_program
from tools.vibeqc_posthf.plan_spec import native_header
from tools.vibeqc_tensor.cpu_emit import emit_cpu


def cpu_header():
    lines = [
        "// Generated by tools/generate_mp2_native.py; equations are TensorIR.",
        "#pragma once",
        "#include <algorithm>",
        "#include <cmath>",
        "#include <cstddef>",
        "#include <stdexcept>",
        "#include <vector>",
        "namespace vibeqc::mp2::generated {",
        "using CpuRun = void(*)(const double*,const double*,double,double,const double*,const double*,double*);",
        "struct CpuPlan { CpuRun run; std::size_t numeric_bytes; const char* equation_hash; };",
    ]
    plans = []
    for tile in (1, 2, 4, 8):
        program = energy_program((1, 1, tile, tile))
        lines.append(emit_cpu(program, function_name=f"tile_{tile}"))
        feeds = {"g": "g", "x": "x", "ei": "&ei", "ej": "&ej", "ea": "ea", "eb": "eb"}
        inputs = ",".join(
            feeds[n.attrs["name"]] for n in program.live_nodes if n.op == "input"
        )
        lines.append(
            f"inline void run_{tile}(const double* g,const double* x,double ei,double ej,const double* ea,const double* eb,double* out) {{ const double* inputs[]={{{inputs}}}; double* outputs[]={{out,out+1}}; tile_{tile}(inputs,outputs); }}"
        )
        plans.append(
            f'case {tile}: return {{run_{tile},{cpu_capacity(program)}ULL,"{program.logical_hash}"}};'
        )
    lines.append(
        "inline CpuPlan cpu_plan(unsigned tile) { switch(tile) {"
        + "".join(plans)
        + 'default: throw std::invalid_argument("unsupported MP2 tile"); }}'
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cpu-header", type=Path)
    parser.add_argument("--cuda-dir", type=Path)
    parser.add_argument("--architectures", default="90")
    args = parser.parse_args()
    if args.cpu_header:
        args.cpu_header.parent.mkdir(parents=True, exist_ok=True)
        args.cpu_header.write_text(cpu_header(), encoding="utf-8")
        args.cpu_header.with_name("block_capacity_generated.hpp").write_text(
            native_header(), encoding="utf-8"
        )
    if args.cuda_dir:
        cuda_sources(args.cuda_dir, args.architectures)
    if not args.cpu_header and not args.cuda_dir:
        parser.error("select --cpu-header and/or --cuda-dir")


def _numeric_architectures(value):
    raw = [item.strip() for item in value.split(";") if item.strip()]
    special = {"native", "all", "all-major"}
    unsupported = sorted({item.lower() for item in raw if item.lower() in special})
    if unsupported:
        values = ", ".join(unsupported)
        raise ValueError(
            "MP2 CUDA generation requires numeric architectures; "
            f"CMake special value(s) {values} are unsupported. "
            "Configure with values such as 75;90."
        )
    try:
        result = sorted({int(item.split("-")[0]) for item in raw})
    except ValueError as exc:
        raise ValueError(
            "MP2 CUDA generation requires numeric architectures such as 75;90."
        ) from exc
    if not result:
        raise ValueError(
            "MP2 CUDA generation requires at least one numeric architecture."
        )
    return result


def cuda_sources(directory, architectures):
    from tools.vibeqc_codegen.cuda_target import cuda_target_info
    from tools.vibeqc_tensor.cuda_emit import emit_cuda
    from tools.vibeqc_tensor.cuda_plan import plan_cuda

    archs = _numeric_architectures(architectures)
    directory.mkdir(parents=True, exist_ok=True)
    table = [
        '#include "posthf/mp2_cuda_plan.hpp"',
        "#include <cuda_runtime.h>",
        "#include <stdexcept>",
        "namespace vibeqc::mp2::generated {",
    ]
    choices = []
    for arch in archs:
        for tile in (1, 2, 4, 8):
            program = energy_program((1, 1, tile, tile))
            plan = plan_cuda(program, cuda_target_info(f"sm_{arch}"), max_bytes=1 << 20)
            prefix = f"mp2_sm{arch}_t{tile}_"
            source = emit_cuda(plan, symbol_prefix=prefix)
            feeds = {
                "g": "g",
                "x": "x",
                "ei": "&ei",
                "ej": "&ej",
                "ea": "ea",
                "eb": "eb",
            }
            inputs = ",".join(
                feeds[plan.steps[k].node.attrs["name"]] for k in plan.inputs
            )
            source += f"""\nextern "C" int {prefix}run(void* p,const double* g,const double* x,double ei,double ej,const double* ea,const double* eb,double* out,vibeqc_tensor::Metrics* metrics,char* error,size_t size) {{
const double* inputs[]={{{inputs}}}; double* outputs[]={{out,out+1}};
return {prefix}generated::{prefix}tensor_run(p,inputs,outputs,1,metrics,error,size);
}}\n"""
            (directory / f"{prefix}runtime.cu").write_text(source, encoding="utf-8")
            table += [
                f'extern "C" int {prefix}tensor_create(int,void**,char*,std::size_t);',
                f'extern "C" void {prefix}tensor_destroy(void*);',
                f'extern "C" int {prefix}run(void*,const double*,const double*,double,double,const double*,const double*,double*,vibeqc_tensor::Metrics*,char*,std::size_t);',
            ]
            choices.append(
                f'''if (arch=={arch} && tile=={tile}) return {{{prefix}tensor_create,{prefix}tensor_destroy,{prefix}run,{plan.peak_bytes}ULL,{plan.allocation_bytes}ULL,"{program.logical_hash}"}};'''
            )
    table += [
        'CudaPlan cuda_plan(unsigned tile,int device) { cudaDeviceProp p{}; if (cudaGetDeviceProperties(&p,device)!=cudaSuccess) throw std::runtime_error("CUDA MP2 device probe failed"); const int arch=10*p.major+p.minor;',
        *choices,
        'throw std::runtime_error("MP2 tensor plan is not compiled for this architecture/tile");',
        "}",
        "}",
    ]
    (directory / "mp2_cuda_table.cu").write_text(
        "\n".join(table) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
