"""Generate shared CPU/CUDA GFN2 SCC energy composition from TensorIR."""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

import vibeqc_compiler

for package_name in ("tensor", "method"):
    qualified = f"vibeqc_compiler.{package_name}"
    if qualified not in sys.modules:
        package = types.ModuleType(qualified)
        package.__path__ = [str(ROOT / "python" / "vibeqc_compiler" / package_name)]
        package.__package__ = qualified
        sys.modules[qualified] = package
        setattr(vibeqc_compiler, package_name, package)

from vibeqc_compiler.method.gfn2_scc_free_energy_runtime import (
    GFN2_SCC_FREE_ENERGY_RUNTIME_VERSION,
    build_gfn2_scc_free_energy_program,
    build_gfn2_scc_internal_energy_program,
)
from vibeqc_compiler.tensor.scalar_cpp import emit_scalar_cpp

_INTERNAL_INPUTS = (
    "core", "es2", "es3", "aes2", "spin", "d4_two_body",
    "explicit_point_charge", "electric_field", "periodic_embedding",
)
_FREE_INPUTS = ("electronic_temperature", "entropy", "internal_energy")


def _host_device(source: str, function_name: str) -> str:
    return source.replace(
        f"inline bool {function_name}(",
        f"VIBEQC_GFN2_SCC_FREE_ENERGY_HD inline bool {function_name}(",
        1,
    )


def native_header() -> str:
    internal = build_gfn2_scc_internal_energy_program()
    free = build_gfn2_scc_free_energy_program()
    internal_body = _host_device(
        emit_scalar_cpp(
            internal,
            function_name="compose_gfn2_scc_internal_energy",
            input_order=_INTERNAL_INPUTS,
            output_order=("internal_energy",),
        ),
        "compose_gfn2_scc_internal_energy",
    )
    free_body = _host_device(
        emit_scalar_cpp(
            free,
            function_name="compose_gfn2_scc_free_energy",
            input_order=_FREE_INPUTS,
            output_order=("free_energy",),
            fused_accumulation=True,
        ),
        "compose_gfn2_scc_free_energy",
    )
    return "\n".join(
        [
            "// Generated by tools/generate_gfn2_scc_free_energy_native.py from TensorIR; do not edit.",
            "#pragma once",
            "#include <cmath>",
            "#if defined(__CUDACC__)",
            "#define VIBEQC_GFN2_SCC_FREE_ENERGY_HD __host__ __device__",
            "#else",
            "#define VIBEQC_GFN2_SCC_FREE_ENERGY_HD",
            "#endif",
            "namespace vibeqc::xtb::generated {",
            f'inline constexpr const char* gfn2_scc_free_energy_runtime_version = "{GFN2_SCC_FREE_ENERGY_RUNTIME_VERSION}";',
            f'inline constexpr const char* gfn2_scc_internal_energy_hash = "{internal.logical_hash}";',
            f'inline constexpr const char* gfn2_scc_free_energy_hash = "{free.logical_hash}";',
            internal_body,
            free_body,
            "}  // namespace vibeqc::xtb::generated",
            "#undef VIBEQC_GFN2_SCC_FREE_ENERGY_HD",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(native_header(), encoding="utf-8")


if __name__ == "__main__":
    main()
