"""Emit shared CUDA mean-field setup without runtime/GPU dependencies."""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "python"), str(ROOT)]

# Reuse the existing minimal TensorIR build bootstrap. This imports only
# build-time modules even when CMake's interpreter has no NumPy installation.
from vibeqc_compiler.method.mean_field_setup_cuda import emit_mean_field_setup_cuda

from tools import generate_scf_array_native as _scf_build  # noqa: F401
from tools.generate_df_kernels import write_if_changed


def main() -> None:
    """Keep unchanged generated bytes and object-cache identities stable."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    write_if_changed(args.output, emit_mean_field_setup_cuda())


if __name__ == "__main__":
    main()
