#!/usr/bin/env python3
"""Generate the checked-in H-Ar r2SCAN-3c gCP C++ parameter table."""

import json
import typing
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/parameters/r2scan3c_gcp.json"
OUTPUT = ROOT / "src/dft/dispersion/gcp_r2scan3c_data.hpp"


def _number(value: typing.Any) -> typing.Any:
    value = float(value)
    return str(int(value)) if value.is_integer() else repr(value)


def main() -> None:
    data = json.loads(SOURCE.read_text())
    if data["schema"] != "vibeqc.gcp-r2scan3c-parameters":
        raise SystemExit("unexpected gCP parameter schema")
    elements = data["elements"]
    radii = data["vdw_pair_radii_angstrom"]
    if [row["atomic_number"] for row in elements] != list(range(1, 19)):
        raise SystemExit("expected contiguous H-Ar gCP data")
    if len(radii) != 171:
        raise SystemExit("expected H-Ar lower-triangular vdW radius table")
    lines = [
        "// Generated by tools/parameters/generate_gcp_r2scan3c.py; do not edit.",
        "// SPDX-License-Identifier: LGPL-3.0-or-later",
        "// Numerical data derived from simple-dftd3, LGPL-3.0-or-later.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace vibeqc::dft::dispersion::gcp_data {",
        "struct Element { double emiss; double slater; double xv; int shell; };",
        "inline constexpr std::array<Element, 18> kElements{{",
    ]
    for row in elements:
        lines.append(
            f"  Element{{{_number(row['emiss'])}, {_number(row['slater'])}, "
            f"{_number(row['xv'])}, {row['shell']}}},"
        )
    lines += ["}};", "inline constexpr std::array<double, 171> kVdwAngstrom{{"]
    for i in range(0, len(radii), 6):
        lines.append("  " + ", ".join(_number(v) for v in radii[i : i + 6]) + ",")
    lines += [
        "}};",
        'inline constexpr char kSimpleDftd3Revision[] = "41d5a07b98ce15e97bec7a1815869725f6c7b0c2";',
        "}  // namespace vibeqc::dft::dispersion::gcp_data",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
