#!/usr/bin/env python3
"""Generate the checked-in H-Ar r2SCAN-3c gCP C++ parameter table."""

from __future__ import annotations

import argparse
import json
import sys
import typing
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import source_registry

SOURCE = ROOT / "tools/parameters/r2scan3c_gcp.json"
OUTPUT = ROOT / "src/dft/dispersion/gcp_r2scan3c_data.hpp"
PRODUCT_ID = "r2scan3c-gcp"
PRODUCT_INPUTS = ("simple-dftd3-gcp",)
PRODUCT_CANONICAL_INPUTS = ("tools/parameters/r2scan3c_gcp.json",)


def _number(value: typing.Any) -> typing.Any:
    value = float(value)
    return str(int(value)) if value.is_integer() else repr(value)


def render(data: dict[str, typing.Any], source: dict[str, typing.Any]) -> str:
    """Render gCP data after matching its canonical input to the registry."""
    if data["schema"] != "vibeqc.gcp-r2scan3c-parameters":
        raise source_registry.SourceRegistryError("unexpected gCP parameter schema")
    upstream = data.get("upstream", {})
    repository = source["repository"].removeprefix("https://github.com/")
    registered_hashes = {
        item.get("upstream_path", name): item["sha256"]
        for name, item in source["files"].items()
    }
    expected = {
        "repository": repository,
        "commit": source["revision"],
        "license": source["license"],
        "param_sha256": registered_hashes["src/dftd3/gcp/param.f90"],
        "implementation_sha256": registered_hashes["src/dftd3/gcp.f90"],
        "vdwrad_sha256": registered_hashes["src/dftd3/data/vdwrad.f90"],
    }
    if upstream != expected:
        raise source_registry.SourceRegistryError(
            "canonical gCP input does not match its registered upstream identity"
        )
    elements = data["elements"]
    radii = data["vdw_pair_radii_angstrom"]
    if [row["atomic_number"] for row in elements] != list(range(1, 19)):
        raise source_registry.SourceRegistryError("expected contiguous H-Ar gCP data")
    if len(radii) != 171:
        raise source_registry.SourceRegistryError(
            "expected H-Ar lower-triangular vdW radius table"
        )
    lines = [
        "// Generated by tools/parameters/generate_gcp_r2scan3c.py; do not edit.",
        f"// SPDX-License-Identifier: {source['license']}",
        f"// Numerical data derived from simple-dftd3, {source['license']}.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace vibeqc::dft::dispersion::gcp_data {",
        "struct Element {",
        "  double emiss;",
        "  double slater;",
        "  double xv;",
        "  int shell;",
        "};",
        "inline constexpr std::array<Element, 18> kElements{{",
    ]
    for row in elements:
        lines.append(
            f"    Element{{{_number(row['emiss'])}, {_number(row['slater'])}, "
            f"{_number(row['xv'])}, {row['shell']}}},"
        )
    lines += ["}};", "inline constexpr std::array<double, 171> kVdwAngstrom{{"]
    for i in range(0, len(radii), 12):
        tokens = [f"{_number(value)}," for value in radii[i : i + 12]]
        lines.append(
            "    " + "".join(token.ljust(8) for token in tokens[:-1]) + tokens[-1]
        )
    lines += [
        "}};",
        f'inline constexpr char kSimpleDftd3Revision[] = "{source["revision"]}";',
        "}  // namespace vibeqc::dft::dispersion::gcp_data",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=source_registry.REGISTRY)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    registered = source_registry.load_product_sources(
        PRODUCT_ID,
        generator=Path(__file__),
        expected_inputs=PRODUCT_INPUTS,
        expected_canonical_inputs=PRODUCT_CANONICAL_INPUTS,
        registry_path=args.registry,
    )
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    output = render(data, registered["simple-dftd3-gcp"])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
