#!/usr/bin/env python3
"""Generate pinned EEQ-D4 reference and EEQ2019 charge-model data."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import generate_d4 as base

DFTD4_REVISION = "6e1f59c3f39d919a2dbef0601d2576727c8b30e8"
MULTICHARGE_REVISION = "6a5d63f9e9e29dcf13cc47cc27f33bf9015681bf"
MCTC_REVISION = "e9de066d89f250d1cfb6de3a33f0c27c0e2f855d"
MULTICHARGE_SOURCE = "src/multicharge/param/eeq2019.f90"
ELEMENT_COUNT = base.ELEMENT_COUNT


def source_record(git_dir: Path, revision: str, path: str) -> dict[str, object]:
    text = base.git_show(git_dir, revision, path)
    return {
        "path": path,
        "git_blob": base.git_value(git_dir, "rev-parse", f"{revision}:{path}"),
        "sha256": hashlib.sha256(text.encode()).hexdigest(),
        "size": len(text.encode()),
    }


def render(
    elements: list[dict[str, float | int]],
    references: list[dict[str, float | int]],
    c6_standard: list[float],
    charge_params: list[tuple[float, float, float, float]],
) -> str:
    if len(elements) != ELEMENT_COUNT:
        raise base.D4DataError(
            f"EEQ element table has {len(elements)} entries, expected {ELEMENT_COUNT}"
        )
    nref = len(references)
    reference_rows = [
        "    D4ReferenceData{"
        + ", ".join(
            [
                base.format_double(float(r["coordination_number"])),
                base.format_double(float(r["charge"])),
                str(r["gaussian_count"]),
            ]
        )
        + "},"
        for r in references
    ]
    charge_rows = [
        "    EEQChargeElementData{"
        + ", ".join(base.format_double(v) for v in values)
        + "},"
        for values in charge_params
    ]
    packed_standard = [
        c6_standard[i * nref + j] for i in range(nref) for j in range(i + 1)
    ]
    return f"""// clang-format off
// Generated by tools/parameters/generate_d4_eeq.py; do not edit.
// DFT-D4 numerical tables: LGPL-3.0-or-later.
// EEQ2019 parameters: Apache-2.0.
#pragma once

#include <array>
#include <cstddef>

#include "dft/dispersion/d4_element_data.hpp"

namespace vibeqc::dft::dispersion::eeq_data {{

using data::D4ReferenceData;
using data::kElementCount;
using data::kElements;

inline constexpr char kDftd4Revision[] = "{DFTD4_REVISION}";
inline constexpr char kMultichargeRevision[] = "{MULTICHARGE_REVISION}";
inline constexpr char kMctcRevision[] = "{MCTC_REVISION}";
inline constexpr std::size_t kReferenceCount = {len(references)}u;

struct EEQChargeElementData {{
  double chi;
  double eta;
  double kcnchi;
  double radius;
}};

inline constexpr std::array<D4ReferenceData, kReferenceCount> kReferences{{{{
{chr(10).join(reference_rows)}
}}}};

inline constexpr std::array<EEQChargeElementData, kElementCount> kChargeElements{{{{
{chr(10).join(charge_rows)}
}}}};

inline constexpr std::array<double, kReferenceCount * (kReferenceCount + 1) / 2>
    kReferenceC6Standard{{{{
{base.format_array(packed_standard)}
}}}};

}}  // namespace vibeqc::dft::dispersion::eeq_data
// clang-format on
"""


def render_r2scan_c6(
    references: list[dict[str, float | int]],
    c6_r2scan3c: list[float],
) -> str:
    nref = len(references)
    packed = [c6_r2scan3c[i * nref + j] for i in range(nref) for j in range(i + 1)]
    return f"""// clang-format off
// Generated by tools/parameters/generate_d4_eeq.py; do not edit.
// DFT-D4 numerical tables: LGPL-3.0-or-later.
#pragma once

#include "dft/dispersion/d4_eeq_data.hpp"

namespace vibeqc::dft::dispersion::eeq_data {{

inline constexpr std::array<double, kReferenceCount * (kReferenceCount + 1) / 2>
    kReferenceC6R2SCAN3C{{{{
{base.format_array(packed)}
}}}};

}}  // namespace vibeqc::dft::dispersion::eeq_data
// clang-format on
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dftd4-git-dir", type=Path, required=True)
    parser.add_argument("--multicharge-git-dir", type=Path, required=True)
    parser.add_argument("--mctc-git-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    dft_sources = {
        path: base.git_show(args.dftd4_git_dir, DFTD4_REVISION, path)
        for path in base.SOURCE_PATHS
    }
    elements, references, c6_standard = base.build_tables(
        dft_sources, reference_model="eeq", ga=3.0, gc=2.0
    )
    elements2, references2, c6_r2scan3c = base.build_tables(
        dft_sources, reference_model="eeq", ga=2.0, gc=1.0
    )
    if elements != elements2 or references != references2:
        raise base.D4DataError(
            "EEQ reference identity unexpectedly depends on zeta profile"
        )

    mctc_covrad = base.parameter_array(
        base.git_show(
            args.mctc_git_dir,
            MCTC_REVISION,
            "src/mctc/data/covrad.f90",
        ),
        "covalent_rad_2009",
    )
    dft_covrad = base.parameter_array(
        dft_sources["src/dftd4/data/covrad.f90"], "covalent_rad_2009"
    )
    if mctc_covrad[:ELEMENT_COUNT] != dft_covrad[:ELEMENT_COUNT]:
        raise base.D4DataError("EEQ and D4 covalent-radius tables disagree")

    mchrg = base.git_show(
        args.multicharge_git_dir, MULTICHARGE_REVISION, MULTICHARGE_SOURCE
    )
    arrays = [
        base.parameter_array(mchrg, name, expected=103)[:ELEMENT_COUNT]
        for name in ("eeq_chi", "eeq_eta", "eeq_kcnchi", "eeq_rad")
    ]
    charge_params = list(zip(*arrays, strict=True))
    header = render(elements, references, c6_standard, charge_params)
    r2scan_header = render_r2scan_c6(references, c6_r2scan3c)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    output = args.output_dir / "d4_eeq_data.hpp"
    r2scan_output = args.output_dir / "d4_eeq_r2scan3c_c6.hpp"
    output.write_text(header, encoding="utf-8", newline="\n")
    r2scan_output.write_text(r2scan_header, encoding="utf-8", newline="\n")
    output_hashes = {
        output.name: hashlib.sha256(header.encode()).hexdigest(),
        r2scan_output.name: hashlib.sha256(r2scan_header.encode()).hexdigest(),
    }
    bundle_identity = "".join(
        f"{name}:{output_hashes[name]}\n" for name in sorted(output_hashes)
    )
    manifest = {
        "generator": "tools/parameters/generate_d4_eeq.py",
        "dftd4_revision": DFTD4_REVISION,
        "multicharge_revision": MULTICHARGE_REVISION,
        "mctc_revision": MCTC_REVISION,
        "reference_model": "eeq",
        "profiles": {
            "standard": {"ga": 3.0, "gc": 2.0},
            "r2scan-3c": {"ga": 2.0, "gc": 1.0},
        },
        "element_count": len(elements),
        "shared_element_table": "d4_element_data.hpp",
        "reference_count": len(references),
        "storage": "lower-triangle-including-diagonal",
        "outputs": output_hashes,
        "bundle_sha256": hashlib.sha256(bundle_identity.encode()).hexdigest(),
        "licenses": {
            "dftd4": "LGPL-3.0-or-later",
            "multicharge": "Apache-2.0",
            "mctc-lib": "Apache-2.0",
        },
        "sources": {
            "dftd4": [
                source_record(args.dftd4_git_dir, DFTD4_REVISION, path)
                for path in base.SOURCE_PATHS
            ],
            "multicharge": [
                source_record(
                    args.multicharge_git_dir, MULTICHARGE_REVISION, MULTICHARGE_SOURCE
                )
            ],
            "mctc-lib": [
                source_record(
                    args.mctc_git_dir,
                    MCTC_REVISION,
                    "src/mctc/data/covrad.f90",
                ),
                source_record(
                    args.mctc_git_dir,
                    MCTC_REVISION,
                    "src/mctc/ncoord/erf.f90",
                ),
                source_record(
                    args.mctc_git_dir,
                    MCTC_REVISION,
                    "src/mctc/ncoord/type.f90",
                ),
            ],
        },
    }
    (args.output_dir / "d4_eeq_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
