#!/usr/bin/env python3
"""Generate pinned EEQ-D4 reference and EEQ2019 charge-model data."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import generate_d4 as base

from tools import source_registry

PRODUCT_ID = "d4-eeq-tables"
PRODUCT_INPUTS = ("dftd4-reference", "multicharge-eeq2019", "mctc-lib-eeq")
PRODUCT_CANONICAL_INPUTS: tuple[str, ...] = ()
ELEMENT_COUNT = base.ELEMENT_COUNT


def source_record(source: dict[str, object], path: str) -> dict[str, object]:
    item = source["files"][path]
    return {
        "path": path,
        "git_blob": item["git_blob"],
        "sha256": item["sha256"],
        "size": item["size"],
    }


def render(
    elements: list[dict[str, float | int]],
    references: list[dict[str, float | int]],
    c6_standard: list[float],
    charge_params: list[tuple[float, float, float, float]],
    *,
    dftd4_revision: str,
    multicharge_revision: str,
    mctc_revision: str,
    dftd4_license: str,
    multicharge_license: str,
) -> str:
    if len(elements) != ELEMENT_COUNT:
        raise base.D4DataError(
            f"EEQ element table has {len(elements)} entries, expected {ELEMENT_COUNT}"
        )
    nref = len(references)
    reference_rows = [
        "    D4ReferenceData{"
        + ", ".join(
            [
                base.format_double(float(r["coordination_number"])),
                base.format_double(float(r["charge"])),
                str(r["gaussian_count"]),
            ]
        )
        + "},"
        for r in references
    ]
    charge_rows = [
        "    EEQChargeElementData{"
        + ", ".join(base.format_double(v) for v in values)
        + "},"
        for values in charge_params
    ]
    packed_standard = [
        c6_standard[i * nref + j] for i in range(nref) for j in range(i + 1)
    ]
    return f"""// clang-format off
// Generated by tools/parameters/generate_d4_eeq.py; do not edit.
// DFT-D4 numerical tables: {dftd4_license}.
// EEQ2019 parameters: {multicharge_license}.
#pragma once

#include <array>
#include <cstddef>

#include "dft/dispersion/d4_element_data.hpp"

namespace vibeqc::dft::dispersion::eeq_data {{

using data::D4ReferenceData;
using data::kElementCount;
using data::kElements;

inline constexpr char kDftd4Revision[] = "{dftd4_revision}";
inline constexpr char kMultichargeRevision[] = "{multicharge_revision}";
inline constexpr char kMctcRevision[] = "{mctc_revision}";
inline constexpr std::size_t kReferenceCount = {len(references)}u;

struct EEQChargeElementData {{
  double chi;
  double eta;
  double kcnchi;
  double radius;
}};

inline constexpr std::array<D4ReferenceData, kReferenceCount> kReferences{{{{
{chr(10).join(reference_rows)}
}}}};

inline constexpr std::array<EEQChargeElementData, kElementCount> kChargeElements{{{{
{chr(10).join(charge_rows)}
}}}};

inline constexpr std::array<double, kReferenceCount * (kReferenceCount + 1) / 2>
    kReferenceC6Standard{{{{
{base.format_array(packed_standard)}
}}}};

}}  // namespace vibeqc::dft::dispersion::eeq_data
// clang-format on
"""


def render_r2scan_c6(
    references: list[dict[str, float | int]],
    c6_r2scan3c: list[float],
    *,
    dftd4_license: str,
) -> str:
    nref = len(references)
    packed = [c6_r2scan3c[i * nref + j] for i in range(nref) for j in range(i + 1)]
    return f"""// clang-format off
// Generated by tools/parameters/generate_d4_eeq.py; do not edit.
// DFT-D4 numerical tables: {dftd4_license}.
#pragma once

#include "dft/dispersion/d4_eeq_data.hpp"

namespace vibeqc::dft::dispersion::eeq_data {{

inline constexpr std::array<double, kReferenceCount * (kReferenceCount + 1) / 2>
    kReferenceC6R2SCAN3C{{{{
{base.format_array(packed)}
}}}};

}}  // namespace vibeqc::dft::dispersion::eeq_data
// clang-format on
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=source_registry.REGISTRY)
    parser.add_argument(
        "--cache-root", type=Path, default=source_registry.DEFAULT_CACHE
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    registered = source_registry.load_product_sources(
        PRODUCT_ID,
        generator=Path(__file__),
        expected_inputs=PRODUCT_INPUTS,
        expected_canonical_inputs=PRODUCT_CANONICAL_INPUTS,
        registry_path=args.registry,
    )
    dftd4 = registered["dftd4-reference"]
    multicharge = registered["multicharge-eeq2019"]
    mctc = registered["mctc-lib-eeq"]
    dft_sources = source_registry.read_source_texts(
        "dftd4-reference",
        dftd4,
        cache_root=args.cache_root,
        collection=base.D4_SOURCE_COLLECTION,
    )
    multicharge_sources = source_registry.read_source_texts(
        "multicharge-eeq2019", multicharge, cache_root=args.cache_root
    )
    mctc_sources = source_registry.read_source_texts(
        "mctc-lib-eeq", mctc, cache_root=args.cache_root
    )
    elements, references, c6_standard = base.build_tables(
        dft_sources, reference_model="eeq", ga=3.0, gc=2.0
    )
    elements2, references2, c6_r2scan3c = base.build_tables(
        dft_sources, reference_model="eeq", ga=2.0, gc=1.0
    )
    if elements != elements2 or references != references2:
        raise base.D4DataError(
            "EEQ reference identity unexpectedly depends on zeta profile"
        )

    mctc_covrad = base.parameter_array(
        mctc_sources["src/mctc/data/covrad.f90"],
        "covalent_rad_2009",
    )
    dft_covrad = base.parameter_array(
        dft_sources["src/dftd4/data/covrad.f90"], "covalent_rad_2009"
    )
    if mctc_covrad[:ELEMENT_COUNT] != dft_covrad[:ELEMENT_COUNT]:
        raise base.D4DataError("EEQ and D4 covalent-radius tables disagree")

    if len(multicharge_sources) != 1:
        raise base.D4DataError("EEQ registry source must contain one parameter file")
    mchrg = next(iter(multicharge_sources.values()))
    arrays = [
        base.parameter_array(mchrg, name, expected=103)[:ELEMENT_COUNT]
        for name in ("eeq_chi", "eeq_eta", "eeq_kcnchi", "eeq_rad")
    ]
    charge_params = list(zip(*arrays, strict=True))
    header = render(
        elements,
        references,
        c6_standard,
        charge_params,
        dftd4_revision=dftd4["revision"],
        multicharge_revision=multicharge["revision"],
        mctc_revision=mctc["revision"],
        dftd4_license=dftd4["license"],
        multicharge_license=multicharge["license"],
    )
    r2scan_header = render_r2scan_c6(
        references, c6_r2scan3c, dftd4_license=dftd4["license"]
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    output = args.output_dir / "d4_eeq_data.hpp"
    r2scan_output = args.output_dir / "d4_eeq_r2scan3c_c6.hpp"
    output.write_text(header, encoding="utf-8", newline="\n")
    r2scan_output.write_text(r2scan_header, encoding="utf-8", newline="\n")
    output_hashes = {
        output.name: hashlib.sha256(header.encode()).hexdigest(),
        r2scan_output.name: hashlib.sha256(r2scan_header.encode()).hexdigest(),
    }
    bundle_identity = "".join(
        f"{name}:{output_hashes[name]}\n" for name in sorted(output_hashes)
    )
    manifest = {
        "generator": "tools/parameters/generate_d4_eeq.py",
        "dftd4_revision": dftd4["revision"],
        "multicharge_revision": multicharge["revision"],
        "mctc_revision": mctc["revision"],
        "reference_model": "eeq",
        "profiles": {
            "standard": {"ga": 3.0, "gc": 2.0},
            "r2scan-3c": {"ga": 2.0, "gc": 1.0},
        },
        "element_count": len(elements),
        "shared_element_table": "d4_element_data.hpp",
        "reference_count": len(references),
        "storage": "lower-triangle-including-diagonal",
        "outputs": output_hashes,
        "bundle_sha256": hashlib.sha256(bundle_identity.encode()).hexdigest(),
        "licenses": {
            "dftd4": dftd4["license"],
            "multicharge": multicharge["license"],
            "mctc-lib": mctc["license"],
        },
        "sources": {
            "dftd4": [source_record(dftd4, path) for path in dft_sources],
            "multicharge": [
                source_record(multicharge, path) for path in multicharge_sources
            ],
            "mctc-lib": [source_record(mctc, path) for path in mctc_sources],
        },
    }
    (args.output_dir / "d4_eeq_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
